CREATE TABLE [dbo].[cleaned-credible-ledger] (

	[visit_id] int NULL, 
	[client_visit_id] int NULL, 
	[claim_id] varchar(50) NULL, 
	[time_in] varchar(50) NULL, 
	[client_id] int NULL, 
	[cpt_code] varchar(10) NULL, 
	[program_description] varchar(255) NULL, 
	[status] varchar(50) NULL, 
	[rate] float NULL, 
	[balance] float NULL, 
	[billing_review_status_id] int NULL, 
	[lookup_description] varchar(255) NULL, 
	[payer_description] varchar(255) NULL, 
	[employee_name] varchar(255) NULL, 
	[service_description] varchar(500) NULL, 
	[visit_type] varchar(100) NULL, 
	[sign_date] varchar(50) NULL, 
	[client_last_name] varchar(100) NULL, 
	[client_first_name] varchar(100) NULL, 
	[visit_type_id] int NULL, 
	[icn] varchar(50) NULL, 
	[action_date] varchar(50) NULL, 
	[notes] varchar(8000) NULL, 
	[created_date] varchar(50) NULL, 
	[data_source] varchar(50) NULL
);