CREATE TABLE [dbo].[cleaned-credible-ledger-v2] (

	[visit_id] int NULL, 
	[service_id] int NULL, 
	[claim_id] varchar(50) NULL, 
	[service_date] date NULL, 
	[client_name] varchar(255) NULL, 
	[client_last_name] varchar(100) NULL, 
	[client_first_name] varchar(100) NULL, 
	[service_type] varchar(255) NULL, 
	[cpt_code] varchar(10) NULL, 
	[modifier] varchar(10) NULL, 
	[program] varchar(255) NULL, 
	[location] varchar(255) NULL, 
	[recipient] varchar(255) NULL, 
	[employee_name] varchar(255) NULL, 
	[status] varchar(50) NULL, 
	[rate] float NULL, 
	[primary_payer_code] varchar(50) NULL, 
	[date_batched] date NULL, 
	[balance] float NULL, 
	[approval_date] date NULL, 
	[revenue_code] varchar(50) NULL, 
	[billing_batch] varchar(100) NULL, 
	[icn] varchar(50) NULL, 
	[created_date] varchar(50) NULL, 
	[data_source] varchar(50) NULL
);