CREATE TABLE [dbo].[raw-credible-brs-v2] (

	[clientvisit_id] varchar(8000) NULL, 
	[max_timein] varchar(8000) NULL, 
	[max_client_id] varchar(8000) NULL, 
	[max_cptcode] varchar(8000) NULL, 
	[max_program_desc] varchar(8000) NULL, 
	[max_status] varchar(8000) NULL, 
	[avg_rate] float NULL, 
	[max_balance] float NULL, 
	[max_billing_review_status_id] varchar(8000) NULL, 
	[max_lookup_desc] varchar(8000) NULL, 
	[max_payer_description] varchar(8000) NULL, 
	[max_emp_name] varchar(8000) NULL, 
	[max_visittype] varchar(8000) NULL, 
	[sign_date] date NULL, 
	[max_last_name] varchar(8000) NULL, 
	[max_first_name] varchar(8000) NULL, 
	[max_visittype_id] varchar(8000) NULL, 
	[icn] varchar(8000) NULL, 
	[max_action_date] date NULL, 
	[max_claim_id] varchar(8000) NULL, 
	[adjustment_group_code] varchar(8000) NULL, 
	[adjustment_reason_code] varchar(8000) NULL, 
	[max_description] varchar(8000) NULL, 
	[adjustmenttype_id] varchar(8000) NULL, 
	[max_notes] varchar(8000) NULL
);