CREATE TABLE [dbo].[raw-cisdm-accred-studentdrill-warehouse] (

	[Organization] varchar(8000) NULL, 
	[Home School] varchar(8000) NULL, 
	[Site ID] bigint NULL, 
	[NCES ID] bigint NULL, 
	[# of Grading Periods] bigint NULL, 
	[Student ID] bigint NULL, 
	[Student System ID] bigint NULL, 
	[Student Name] varchar(8000) NULL, 
	[Race/Ethnicity] varchar(8000) NULL, 
	[Sex/Gender] varchar(8000) NULL, 
	[Ethnicity] varchar(8000) NULL, 
	[Case Managed Status] varchar(8000) NULL, 
	[Case Management Intensity Level] varchar(8000) NULL, 
	[Grade Level] varchar(8000) NULL, 
	[Case Manager] varchar(8000) NULL, 
	[Current Enrollment Status] varchar(8000) NULL, 
	[Enrollment Begin Date] date NULL, 
	[Student Needs Assessment Entered?] varchar(8000) NULL, 
	[Student Support Plan Entered?] varchar(8000) NULL, 
	[# of Tier II/III Supports] bigint NULL, 
	[# of Check-Ins] bigint NULL, 
	[On Track for Monthly Check-Ins?] varchar(8000) NULL, 
	[# Goal Areas] bigint NULL, 
	[# ABCS Metrics Assigned] bigint NULL, 
	[# Non-ABCS Metrics Assigned] bigint NULL, 
	[# Progress Entries] bigint NULL, 
	[Expected Progress Entries for the Year] bigint NULL, 
	[# of Metrics with Goal Achievement entered] bigint NULL, 
	[Goal Achievement Entered for ALL assigned goals?] varchar(8000) NULL, 
	[EOY Status Entered] varchar(8000) NULL
);