CREATE TABLE [dbo].[raw_cis_caselist] (

	[Home School] varchar(8000) NULL, 
	[Site Model Status] varchar(8000) NULL, 
	[School Year] varchar(8000) NULL, 
	[Student System ID] varchar(8000) NULL, 
	[Student ID] varchar(8000) NULL, 
	[Student] varchar(8000) NULL, 
	[Sex/Gender] varchar(8000) NULL, 
	[Race/Ethnicity] varchar(8000) NULL, 
	[Ethnicity] varchar(8000) NULL, 
	[Tribe] varchar(8000) NULL, 
	[Languages] varchar(8000) NULL, 
	[Public Assisstance Program_s_] varchar(8000) NULL, 
	[Employment Status] varchar(8000) NULL, 
	[Birth Date] varchar(8000) NULL, 
	[Case Managed Status] varchar(8000) NULL, 
	[Case Management _Intensity Level] varchar(8000) NULL, 
	[Case Manager] varchar(8000) NULL, 
	[Grade Level] varchar(8000) NULL, 
	[Enrollment Status] varchar(8000) NULL, 
	[Enrollment _Begin Date] varchar(8000) NULL, 
	[Enrollment_Exit Date] varchar(8000) NULL, 
	[First CIS Enrollment Date] varchar(8000) NULL, 
	[Most Recent_ Referral Date] varchar(8000) NULL, 
	[Most Recent _Referral Reason_s_] varchar(8000) NULL, 
	[Most Recent _Referral Source] varchar(8000) NULL, 
	[All Referral Reason_s_] varchar(8000) NULL, 
	[Student Attributes] varchar(8000) NULL, 
	[Individual Student Risk Factors] varchar(8000) NULL, 
	[Family Risk Factors] varchar(8000) NULL, 
	[Initiatives] varchar(8000) NULL, 
	[Organization ID] bigint NULL, 
	[Site ID] bigint NULL, 
	[NCES ID] bigint NULL
);