CREATE TABLE [dbo].[raw_referrals] (

	[Id] varchar(8000) NULL, 
	[Title] varchar(8000) NULL, 
	[ReferralStatus] varchar(8000) NULL, 
	[ReferralOutcome] varchar(8000) NULL, 
	[DateClientEnteredProgram_i] datetime2(6) NULL, 
	[ReferralDate] date NULL, 
	[ReferralSource] varchar(8000) NULL, 
	[ReferralPhone] varchar(8000) NULL, 
	[LastName] varchar(8000) NULL, 
	[FirstName] varchar(8000) NULL, 
	[PhoneNumber] varchar(8000) NULL, 
	[BehavioralHealth] varchar(8000) NULL, 
	[Housing] varchar(8000) NULL, 
	[Lighthouse] varchar(8000) NULL, 
	[ClientE-mail] varchar(8000) NULL, 
	[ReferralProgram] varchar(8000) NULL, 
	[Last4] varchar(8000) NULL, 
	[Outcome ID] varchar(8000) NULL, 
	[Age] varchar(8000) NULL, 
	[School] varchar(8000) NULL, 
	[CurrentGrade] varchar(8000) NULL, 
	[PreviousHospitalization?] varchar(8000) NULL, 
	[Wheredidyoustaylastnight?] varchar(8000) NULL, 
	[ClientGender] varchar(8000) NULL, 
	[Address] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[Zip] varchar(8000) NULL, 
	[AdditionalComments] varchar(8000) NULL, 
	[ReferringOrganization] varchar(8000) NULL, 
	[VI-SPDATScore] varchar(8000) NULL, 
	[StaffGivenReferralId] varchar(8000) NULL, 
	[StaffGivenReferralStringId] varchar(8000) NULL, 
	[AssignedAssessorId] varchar(8000) NULL, 
	[Created] datetime2(6) NULL, 
	[Index] varchar(8000) NULL
);