CREATE TABLE [dbo].[raw_lsndc_services] (

	[Client ID] bigint NULL, 
	[Service Start Date] date NULL, 
	[Provider Specific Service] varchar(8000) NULL, 
	[Provider Creating] varchar(8000) NULL, 
	[Service Staff] varchar(8000) NULL, 
	[Completed Follow Up Date] varchar(8000) NULL, 
	[Call Record ID] varchar(8000) NULL, 
	[Client ID_1] bigint NULL, 
	[Code] varchar(8000) NULL, 
	[Destination Other] varchar(8000) NULL, 
	[Destination] varchar(8000) NULL, 
	[Follow Up Made] varchar(8000) NULL, 
	[Follow Up User] varchar(8000) NULL, 
	[Group ID] bigint NULL, 
	[HOPWA Financial Assistance Amount] varchar(8000) NULL, 
	[HOPWA Financial Assistance Type] varchar(8000) NULL, 
	[HOPWA Service Type] varchar(8000) NULL, 
	[Household ID] bigint NULL, 
	[HPRP Financial Assistance Type _Retired_] varchar(8000) NULL, 
	[HPRP Financial Assistance End Date _Retired_] varchar(8000) NULL, 
	[HPRP Financial Assistance Start Date _Retired_] varchar(8000) NULL, 
	[HPRP Housing Relocation And Stabilization Service _Retired_] varchar(8000) NULL, 
	[Moving On Other] varchar(8000) NULL, 
	[Moving On Assistance] varchar(8000) NULL, 
	[MAP Call Recordset ID] varchar(8000) NULL, 
	[Need ID] bigint NULL, 
	[PATH Referral Outcome] varchar(8000) NULL, 
	[PATH Referral Type] varchar(8000) NULL, 
	[PATH Service Type] varchar(8000) NULL, 
	[Service Provider] varchar(8000) NULL, 
	[Needs Referral Date] varchar(8000) NULL, 
	[Shelter Bed] varchar(8000) NULL, 
	[Shelter Bedlist] varchar(8000) NULL, 
	[Shelter Behavior Notes] varchar(8000) NULL, 
	[Shelter Item] varchar(8000) NULL, 
	[Shelter On Premises] varchar(8000) NULL, 
	[Shelter Supplies Given] varchar(8000) NULL, 
	[Shelter Supplies Returned] varchar(8000) NULL, 
	[SSVF Direct Public Benefits] varchar(8000) NULL, 
	[SSVF Financial Assistance Amount] float NULL, 
	[SSVF Financial Assistance Type] varchar(8000) NULL, 
	[SSVF Other Public Benefits] varchar(8000) NULL, 
	[SSVF Other Supportive Service] varchar(8000) NULL, 
	[SSVF Service Type] varchar(8000) NULL, 
	[SSVF VA Benefits] varchar(8000) NULL, 
	[Service ID] bigint NULL
);