table 'Grades - Client Grade Breakdown'
	lineageTag: 875284e7-668f-41ef-96da-40d3003c509c

	column sasid
		dataType: string
		lineageTag: 32fcb5e7-dad6-4be9-8753-1032404264df
		summarizeBy: none
		sourceColumn: sasid

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: 326eaff6-e662-4195-93e9-f482e6074510
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column client_full_name
		dataType: string
		lineageTag: 1b23837b-1e03-4519-a9fb-b3cbc59c1f28
		summarizeBy: none
		sourceColumn: client_full_name

		annotation SummarizationSetBy = Automatic

	column school_name
		dataType: string
		lineageTag: 9d7fc441-26d0-4497-a726-523e0238b504
		summarizeBy: none
		sourceColumn: school_name

		annotation SummarizationSetBy = Automatic

	column grade
		dataType: int64
		formatString: 0
		lineageTag: 75316adb-668c-43d8-97c1-0eeec8f1cb4a
		summarizeBy: sum
		sourceColumn: grade

		annotation SummarizationSetBy = Automatic

	column course
		dataType: string
		lineageTag: 8792748b-332b-4ed0-97b3-d14ea53ddc73
		summarizeBy: none
		sourceColumn: course

		annotation SummarizationSetBy = Automatic

	column short_name_academics
		dataType: string
		lineageTag: d2421d62-a3f7-47cc-b013-8e50fea822c4
		summarizeBy: none
		sourceColumn: short_name_academics

		annotation SummarizationSetBy = Automatic

	column 1st_9_GPA
		dataType: double
		lineageTag: ca52e396-8713-4419-85e0-82c42cc5c982
		summarizeBy: sum
		sourceColumn: 1st_9_GPA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 1st_9_grade_value
		dataType: double
		lineageTag: 6ad2f992-cd6f-4724-8ca2-d0a509705258
		summarizeBy: sum
		sourceColumn: 1st_9_grade_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 1st_9_letter_grade
		dataType: string
		lineageTag: b443d106-9566-4f12-b85a-5e32dc7a041e
		summarizeBy: none
		sourceColumn: 1st_9_letter_grade

		annotation SummarizationSetBy = Automatic

	column 'cis_behavior_goal_clients.goal'
		dataType: string
		lineageTag: eefe44ad-3932-4461-9bc5-12505246287b
		summarizeBy: none
		sourceColumn: cis_behavior_goal_clients.goal

		annotation SummarizationSetBy = Automatic

	column 'cis_behavior_goal_clients.metric'
		dataType: string
		lineageTag: dda1d55b-3271-4fcf-924f-0a59cf9c46b7
		summarizeBy: none
		sourceColumn: cis_behavior_goal_clients.metric

		annotation SummarizationSetBy = Automatic

	column 'cis_behavior_goal_clients.baseline'
		dataType: double
		lineageTag: b1a92718-1d0e-4bf9-a4ed-bec68f91f2c0
		summarizeBy: sum
		sourceColumn: cis_behavior_goal_clients.baseline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'cis_behavior_goal_clients.target'
		dataType: double
		formatString: 0
		lineageTag: 634c7ba0-38eb-40f8-8fd7-d8aa76b12f87
		summarizeBy: sum
		sourceColumn: cis_behavior_goal_clients.target

		annotation SummarizationSetBy = Automatic

	column 'cis_behavior_goal_clients.latest_progress'
		dataType: string
		lineageTag: f794e914-0069-4f88-baa2-a0e1c4df01df
		summarizeBy: none
		sourceColumn: cis_behavior_goal_clients.latest_progress

		annotation SummarizationSetBy = Automatic

	partition 'Grades - Client Grade Breakdown' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    cis_active_client_grade_breakdown = Source{[Schema="cis",Item="active_client_grade_breakdown"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(cis_active_client_grade_breakdown, {"client_id", "short_name_academics"}, cis_academics_goal_clients, {"client_id", "short_name_academics"}, "cis_behavior_goal_clients", JoinKind.Inner),
				    #"Expanded cis_behavior_goal_clients1" = Table.ExpandTableColumn(#"Merged Queries", "cis_behavior_goal_clients", {"goal", "metric", "baseline", "target", "latest_progress"}, {"cis_behavior_goal_clients.goal", "cis_behavior_goal_clients.metric", "cis_behavior_goal_clients.baseline", "cis_behavior_goal_clients.target", "cis_behavior_goal_clients.latest_progress"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded cis_behavior_goal_clients1","Caddo Heights Elementary","Caddo Heights",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Westwood Elementary","Westwood",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Midway Professional Development Center","Midway",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Creswell Elementary School","Creswell",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Broadmoor STEM Academy","Broadmoor",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Atkins Technology Elementary School","Atkins",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Woodlawn High School","Woodlawn",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Bethune-Oak Park","Bethune",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Caddo Middle Career and Technology School","CMCTS",Replacer.ReplaceText,{"school_name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value8",{{"cis_behavior_goal_clients.baseline", type number}, {"cis_behavior_goal_clients.target", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

