table 'ProgMon - Attendance Detail'
	lineageTag: 75823f36-f611-41e1-9dfc-49e4bef36e8e

	column school_name
		dataType: string
		lineageTag: d7b7a44a-dc27-43c3-967f-3a876dd0e9b6
		summarizeBy: none
		sourceColumn: school_name

		annotation SummarizationSetBy = Automatic

	column sasid
		dataType: string
		lineageTag: 02682f6e-522f-4d0a-a4a2-7268101a8552
		summarizeBy: none
		sourceColumn: sasid

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: 52a3df3b-9d43-46f7-b567-106ce15bd5bd
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column client_full_name
		dataType: string
		lineageTag: ae3ed63d-fc9f-4ddc-bc40-824786dc4b03
		summarizeBy: none
		sourceColumn: client_full_name

		annotation SummarizationSetBy = Automatic

	column grade
		dataType: string
		lineageTag: b72dade4-632f-4d68-be0d-9fbc21521a5c
		summarizeBy: none
		sourceColumn: grade

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 94474fb1-9406-48c8-aa70-55b24a8ce3e3
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column race
		dataType: string
		lineageTag: 530c5d00-0854-4e25-9cfd-4bb515a46190
		summarizeBy: none
		sourceColumn: race

		annotation SummarizationSetBy = Automatic

	column ethnicity
		dataType: string
		lineageTag: eeb3e750-b7d7-416a-a8f4-09c4093ab8c3
		summarizeBy: none
		sourceColumn: ethnicity

		annotation SummarizationSetBy = Automatic

	column case_manager
		dataType: string
		lineageTag: aefd3eec-6c77-400b-bdb5-03f98b1ddc96
		summarizeBy: none
		sourceColumn: case_manager

		annotation SummarizationSetBy = Automatic

	column goal
		dataType: string
		lineageTag: 366cc9cc-0d56-4f0e-b653-9aee871da43d
		summarizeBy: none
		sourceColumn: goal

		annotation SummarizationSetBy = Automatic

	column metric
		dataType: string
		lineageTag: e6d175c5-2d85-470f-a63d-1079c89f274b
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column baseline
		dataType: double
		formatString: 0
		lineageTag: 1c23029d-d575-44db-b040-10d9f4d4e261
		summarizeBy: sum
		sourceColumn: baseline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column target
		dataType: int64
		formatString: 0
		lineageTag: 2508a5f3-00b9-4292-9701-73a59d05e080
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

	column baseline_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f9995038-74f8-49ce-b70f-0fd14cadc355
		summarizeBy: none
		sourceColumn: baseline_date

		variation Variation
			isDefault
			relationship: 1c53d425-1b2a-4455-9e84-b5398ab8fe8c
			defaultHierarchy: LocalDateTable_38c986f2-252a-48c0-b744-84bd2273f22d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column baseline_report_period
		dataType: string
		lineageTag: fa32ac29-d95f-4078-a534-93bd40c9271a
		summarizeBy: none
		sourceColumn: baseline_report_period

		annotation SummarizationSetBy = Automatic

	column target_set_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0c96d43-ec01-4c0b-9231-3bbe716f696d
		summarizeBy: none
		sourceColumn: target_set_date

		variation Variation
			isDefault
			relationship: 71214e10-0d9e-4c49-9eb1-98f68b50135c
			defaultHierarchy: LocalDateTable_569c32c1-9567-43e0-bf93-32e28db75b0f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column grading_period
		dataType: string
		lineageTag: 4996bcb8-a13d-4cff-9019-375660004803
		summarizeBy: none
		sourceColumn: grading_period

		annotation SummarizationSetBy = Automatic

	column grading_period_progress
		dataType: string
		lineageTag: cff50332-67b0-4039-b730-134685f3bd1c
		summarizeBy: none
		sourceColumn: grading_period_progress

		annotation SummarizationSetBy = Automatic

	column nonNumeric_value
		dataType: int64
		formatString: 0
		lineageTag: b9f64eb7-37ea-4995-9a4a-f42ce3ca0f5a
		summarizeBy: sum
		sourceColumn: nonNumeric_value

		annotation SummarizationSetBy = Automatic

	column metric_value
		dataType: int64
		formatString: 0
		lineageTag: ed8c61ec-a51f-46ad-9763-edaced7cc14f
		summarizeBy: sum
		sourceColumn: metric_value

		annotation SummarizationSetBy = Automatic

	column days_in_report_prd
		dataType: string
		lineageTag: f1b926f5-04c7-456a-9729-c7f84262c7ff
		summarizeBy: none
		sourceColumn: days_in_report_prd

		annotation SummarizationSetBy = Automatic

	column excused_absences
		dataType: string
		lineageTag: 2e4331dc-480b-4179-be5c-cfddaa68ccca
		summarizeBy: none
		sourceColumn: excused_absences

		annotation SummarizationSetBy = Automatic

	column unexcused_absences
		dataType: string
		lineageTag: b0939ef0-2566-49d3-80b6-b91ef6df68f7
		summarizeBy: none
		sourceColumn: unexcused_absences

		annotation SummarizationSetBy = Automatic

	column review_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 90c56938-e275-4cec-a859-13642ac1b3c4
		summarizeBy: none
		sourceColumn: review_date

		variation Variation
			isDefault
			relationship: b523166b-44d2-4f4a-9b21-6bd5e0c2bc91
			defaultHierarchy: LocalDateTable_f6725728-78dd-4b87-a4f2-36c207e85b6c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column latest_progress
		dataType: string
		lineageTag: 9384d745-7933-4087-a55f-cc05c302c5ee
		summarizeBy: none
		sourceColumn: latest_progress

		annotation SummarizationSetBy = Automatic

	column progress_notes
		dataType: string
		lineageTag: 49708787-622c-41c6-b12d-d0700f275c36
		summarizeBy: none
		sourceColumn: progress_notes

		annotation SummarizationSetBy = Automatic

	column goal_narrative
		dataType: string
		lineageTag: 438dc35c-06ed-4dbb-af18-9f6df7470325
		summarizeBy: none
		sourceColumn: goal_narrative

		annotation SummarizationSetBy = Automatic

	column entry_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: acc7d38c-1fcc-4672-bbe8-07dcb7f7149e
		summarizeBy: none
		sourceColumn: entry_date

		variation Variation
			isDefault
			relationship: ef2ab912-e7e7-4bdd-aaf5-f386c379b953
			defaultHierarchy: LocalDateTable_d87dcb2d-63e2-4434-9c30-e3c109b4401b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column exit_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b9e68146-aa8b-4ef9-a5e2-defcf958e631
		summarizeBy: none
		sourceColumn: exit_date

		variation Variation
			isDefault
			relationship: b6ef5d9b-81ea-4f2a-942f-16c13c94da01
			defaultHierarchy: LocalDateTable_597a7e3c-f157-4082-a7c7-6e91939d3d43.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column enrollment_status
		dataType: string
		lineageTag: d2a1dae5-683f-4e73-afc2-23a92634783f
		summarizeBy: none
		sourceColumn: enrollment_status

		annotation SummarizationSetBy = Automatic

	column school_year
		dataType: string
		lineageTag: 418baf98-b649-455d-80f2-c8ed3cb99a22
		summarizeBy: none
		sourceColumn: school_year

		annotation SummarizationSetBy = Automatic

	column jcampus_unexcused
		dataType: int64
		lineageTag: 64096298-bc2a-4580-add7-ec8c8e46a469
		summarizeBy: sum
		sourceColumn: jcampus_unexcused

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column short_name_academics
		dataType: string
		lineageTag: 9649b338-6e5f-4f5c-bf6d-c0c0bb9a48e6
		summarizeBy: none
		sourceColumn: short_name_academics

		annotation SummarizationSetBy = Automatic

	column attendance_type
		dataType: string
		lineageTag: ad4dc1a9-cce2-4ac7-9fc0-2fb5641365eb
		summarizeBy: none
		sourceColumn: attendance_type

		annotation SummarizationSetBy = Automatic

	partition 'ProgMon - Attendance Detail' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    dbo_cis_attendance_goal_clients = Source{[Schema="dbo",Item="cis_attendance_goal_clients"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(dbo_cis_attendance_goal_clients, {"sasid"}, #"Attendance JCampus - Active CIS Clients", {"sasid"}, "Attendance JCampus - Active CIS Clients", JoinKind.LeftOuter),
				    #"Expanded Attendance JCampus - Active CIS Clients" = Table.ExpandTableColumn(#"Merged Queries", "Attendance JCampus - Active CIS Clients", {"Count"}, {"Attendance JCampus - Active CIS Clients.Count"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Attendance JCampus - Active CIS Clients",null,0,Replacer.ReplaceValue,{"Attendance JCampus - Active CIS Clients.Count"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Attendance JCampus - Active CIS Clients.Count", "jcampus_unexcused"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

