CREATE TABLE [active-clients].[credible-active-clients] (

	[employeeid] varchar(8000) NULL, 
	[Client Name] varchar(8000) NULL, 
	[programs] varchar(8000) NULL, 
	[Client ID] varchar(8000) NULL, 
	[external_id] varchar(8000) NULL, 
	[Status] varchar(8000) NULL, 
	[Client Status Date] date NULL, 
	[Date Created] date NULL, 
	[Date Updated] date NULL, 
	[First Name] varchar(8000) NULL, 
	[Last Name] varchar(8000) NULL, 
	[DOB] date NULL, 
	[Age] bigint NULL, 
	[SSN] varchar(8000) NULL, 
	[Gender] varchar(8000) NULL, 
	[Zip] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[county] varchar(8000) NULL, 
	[preferred_language] varchar(8000) NULL, 
	[Admission Date] date NULL, 
	[Date Diagnosis Updated] date NULL, 
	[Diagnosis 1] varchar(8000) NULL, 
	[race_omb] varchar(8000) NULL, 
	[race_omb2] varchar(8000) NULL, 
	[ethnicity_omb] varchar(8000) NULL, 
	[Client Type] varchar(8000) NULL, 
	[dd1] varchar(8000) NULL, 
	[Phone] varchar(8000) NULL, 
	[address1] varchar(8000) NULL, 
	[state] varchar(8000) NULL, 
	[last_svc_date] date NULL, 
	[Profile Auth End Date] date NULL, 
	[teams] varchar(8000) NULL, 
	[show_pbm_medhistory] varchar(8000) NULL, 
	[Diagnosis 2] varchar(8000) NULL, 
	[mobile_phone] varchar(8000) NULL, 
	[client_email] varchar(8000) NULL, 
	[address2] varchar(8000) NULL, 
	[Diagnosis 3] varchar(8000) NULL, 
	[Case Manager Emp ID] varchar(8000) NULL, 
	[dd7] varchar(8000) NULL, 
	[dd6] varchar(8000) NULL, 
	[Discharge Date] date NULL, 
	[dd4] varchar(8000) NULL, 
	[Redzone] varchar(8000) NULL, 
	[axis_1e] varchar(8000) NULL, 
	[maritalstatus] varchar(8000) NULL, 
	[maritalstatupdate] varchar(8000) NULL, 
	[currentschool] varchar(8000) NULL, 
	[currentschoolupdate] varchar(8000) NULL, 
	[axis_1f] varchar(8000) NULL, 
	[Employee Flag] varchar(8000) NULL, 
	[6020 Flag] varchar(8000) NULL, 
	[IBHH Flag] varchar(8000) NULL, 
	[6021 Flag] varchar(8000) NULL, 
	[6401 Flag] varchar(8000) NULL, 
	[OfficeSvs Flag] varchar(8000) NULL, 
	[EpiCenter Flag] varchar(8000) NULL, 
	[Text before delimiter] varchar(8000) NULL, 
	[DOB - Copy] bigint NULL, 
	[Full Address] varchar(8000) NULL, 
	[Text after delimiter] varchar(8000) NULL, 
	[Int ID] varchar(8000) NULL, 
	[Client Name - Copy] varchar(8000) NULL, 
	[Long ID] varchar(8000) NULL, 
	[Today] date NULL, 
	[Days Between Auth] bigint NULL, 
	[Clinician Team] varchar(8000) NULL, 
	[Episode Status] varchar(8000) NULL, 
	[Assessment Date] date NULL, 
	[Admission Date.1] date NULL, 
	[Program ID] varchar(8000) NULL, 
	[Date Episode Created] date NULL, 
	[Discharge Date.1] date NULL, 
	[Referral Date] date NULL
);