[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared #"BRS Cross" = let
  Source = Excel.Workbook(Web.Contents("https://voanorthlaorg-my.sharepoint.com/personal/russell_irby_voanorthla_org/Documents/Apps/Microsoft Power Query/Uploaded Files/Updated_Billing Review Status Template and Crosswalk 4 (1).xlsx"), null, false),
  Crosswalk_sheet = Source{[Item = "Crosswalk", Kind = "Sheet"]}[Data],
  #"Filter null and whitespace" = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
  #"Transposed table" = Table.Transpose(Crosswalk_sheet),
  #"Removed bottom rows" = Table.RemoveLastN(#"Transposed table", each try List.IsEmpty(List.Skip(#"Filter null and whitespace"(Record.FieldValues(_)), 1)) otherwise false),
  #"Transposed table1" = Table.Transpose(#"Removed bottom rows"),
  #"Removed bottom rows1" = Table.RemoveLastN(#"Transposed table1", each try List.IsEmpty(List.Skip(#"Filter null and whitespace"(Record.FieldValues(_)), 1)) otherwise false),
  #"Promoted headers" = Table.PromoteHeaders(#"Removed bottom rows1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Description", type text}, {"Action", type text}, {"Billing Review Status", type text}, {"Notes", type text}, {"Adjustment Code", type text}}),
  #"Replaced value" = Table.ReplaceValue(#"Changed column type", "B7", "B07", Replacer.ReplaceValue, {"Adjustment Code"}),
  #"Removed duplicates" = Table.Distinct(#"Replaced value", {"Adjustment Code"})
in
  #"Removed duplicates";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "raw_credible_brs_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared raw_credible_brs = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2r309sURypsXrRtrWKpewbmQ__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3=")),
  #"Navigation 1" = Source{1}[Table],
  #"Expanded Table" = Table.ExpandTableColumn(#"Navigation 1", "Table", {"Name", "Table"}, {"Name.1", "Table.1"}),
  #"Expanded Table.1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}),
  #"Expanded Table 2" = Table.ExpandTableColumn(#"Expanded Table.1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}),
  #"Expanded Table.1 2" = Table.ExpandTableColumn(#"Expanded Table 2", "Table.1", {"clientvisit_id", "max_timein", "max_client_id", "max_cptcode", "max_program_desc", "max_status", "avg_rate", "max_balance", "max_billing_review_status_id", "max_lookup_desc", "max_payer_description", "max_emp_name", "max_visittype", "sign_date", "max_last_name", "max_first_name", "max_visittype_id", "icn", "max_action_date", "appr_date", "signature_datetime", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "max_claim_id", "adjustment_group_code", "adjustment_reason_code", "max_description", "adjustmenttype_id", "max_notes"}, {"clientvisit_id", "max_timein", "max_client_id", "max_cptcode", "max_program_desc", "max_status", "avg_rate", "max_balance", "max_billing_review_status_id", "max_lookup_desc", "max_payer_description", "max_emp_name", "max_visittype", "sign_date", "max_last_name", "max_first_name", "max_visittype_id", "icn", "max_action_date", "appr_date", "signature_datetime", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "max_claim_id", "adjustment_group_code", "adjustment_reason_code", "max_description", "adjustmenttype_id", "max_notes"}),
  #"Removed columns" = Table.RemoveColumns(#"Expanded Table.1 2", {"Name", "Name.1", "Name.2", "Name.3", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Removed columns", {"sign_date", type datetime}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type",  {"sign_date", type date}),
  #"Extracted text before delimiter" = Table.TransformColumns(#"Changed column type 1", {{"max_action_date", each Text.BeforeDelimiter(Text.From(_), "T", 0), type text}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Extracted text before delimiter", {{"max_action_date", type date}}),
  #"Extracted text before delimiter 1" = Table.TransformColumns(#"Changed column type 2", {{"max_timein", each Text.BeforeDelimiter(Text.From(_), "T", 0), type text}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Extracted text before delimiter 1", {{"max_timein", type date}}),
  #"Renamed columns" = Table.RenameColumns(#"Changed column type 3", {{"max_claim_id", "Claim ID"}, {"max_action_date", "Action Date"}, {"icn", "ICN"}, {"max_visittype_id", "Visit Type ID"}, {"max_emp_name", "Emp Name"}, {"max_visittype", "Visit Type"}, {"max_payer_description", "Payer"}, {"max_lookup_desc", "BRS"}, {"max_billing_review_status_id", "BRS ID"}, {"max_balance", "Balance"}, {"avg_rate", "Rate"}, {"max_status", "Status"}, {"max_program_desc", "Program"}, {"max_cptcode", "CPT Code"}, {"max_client_id", "Client ID"}, {"max_timein", "Service Date"}, {"sign_date", "Signature Date"}, {"max_notes", "Notes"}, {"max_description", "Action Description"}}),
  #"Transform columns" = Table.TransformColumnTypes(#"Renamed columns", {{"Client ID", type text}, {"CPT Code", type text}, {"Program", type text}, {"Status", type text}, {"Rate", type text}, {"Balance", type text}, {"BRS ID", type text}, {"BRS", type text}, {"Payer", type text}, {"Emp Name", type text}, {"Visit Type", type text}, {"max_last_name", type text}, {"max_first_name", type text}, {"Visit Type ID", type text}, {"ICN", type text}, {"Claim ID", type text}, {"Action Description", type text}, {"Notes", type text}}),
  #"Replace errors" = Table.ReplaceErrorValues(#"Transform columns", {{"Client ID", null}, {"CPT Code", null}, {"Program", null}, {"Status", null}, {"Rate", null}, {"Balance", null}, {"BRS ID", null}, {"BRS", null}, {"Payer", null}, {"Emp Name", null}, {"Visit Type", null}, {"max_last_name", null}, {"max_first_name", null}, {"Visit Type ID", null}, {"ICN", null}, {"Claim ID", null}, {"Action Description", null}, {"Notes", null}}),
  #"Renamed columns 1" = Table.RenameColumns(#"Replace errors", {{"clientvisit_id", "Service ID"}}),
  #"Transform columns 1" = Table.TransformColumnTypes(#"Renamed columns 1", {{"Service ID", type text}}),
  #"Replace errors 1" = Table.ReplaceErrorValues(#"Transform columns 1", {{"Service ID", null}}),
  #"Replaced value" = Table.ReplaceValue(#"Replace errors 1", null, "", Replacer.ReplaceValue, {"Action Description"}),
  #"Inserted conditional column" = Table.AddColumn(#"Replaced value", "Custom", each if Text.Contains([Action Description], "KPeters") then [Action Date] else if Text.Contains([Action Description], "KP") then [Action Date] else if [Action Description] = null then null else ""),
  #"Added custom" = Table.AddColumn(#"Inserted conditional column", "Days since Service", each Duration.Days (Date.From(DateTime.FixedLocalNow())- Date.From([Service Date]))),
  #"Added custom 1" = Table.AddColumn(#"Added custom", "Custom (2)", each Duration.Days (Date.From(DateTime.FixedLocalNow())- Date.From([Action Date]))),
  #"Renamed columns 6" = Table.RenameColumns(#"Added custom 1", {{"Custom (2)", "Days since last Kati Action"}, {"Custom", "Date of Kati Action"}}),
  #"Inserted conditional column 1" = Table.AddColumn(#"Renamed columns 6", "Corrected Aging Days", each if [Date of Kati Action] <> "" then [Days since last Kati Action] else [Days since Service]),
  #"Inserted Range" = Table.TransformColumnTypes(Table.AddColumn(#"Inserted conditional column 1", "Range", each let rangeSize = 30, offset = 0, inclusive = false, rangeIndex = Number.RoundDown(([Corrected Aging Days] - offset) / rangeSize) in Text.From(rangeIndex * rangeSize + offset, "en-US") & "-" & Text.From((rangeIndex + 1) * rangeSize + offset - (if inclusive then 1 else 0), "en-US")), {{"Range", type text}}),
  #"Renamed columns 8" = Table.RenameColumns(#"Inserted Range", {{"Range", "Buckets"}, {"BRS", "Billing Review Status"}}),
  #"Replaced value 1" = Table.ReplaceValue(#"Renamed columns 8", "990-1020", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 2" = Table.ReplaceValue(#"Replaced value 1", "960-990", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 3" = Table.ReplaceValue(#"Replaced value 2", "930-960", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 4" = Table.ReplaceValue(#"Replaced value 3", "900-930", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 5" = Table.ReplaceValue(#"Replaced value 4", "870-900", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 6" = Table.ReplaceValue(#"Replaced value 5", "840-870", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 7" = Table.ReplaceValue(#"Replaced value 6", "810-840", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 8" = Table.ReplaceValue(#"Replaced value 7", "750-780", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 9" = Table.ReplaceValue(#"Replaced value 8", "720-750", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 10" = Table.ReplaceValue(#"Replaced value 9", "690-720", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 11" = Table.ReplaceValue(#"Replaced value 10", "660-690", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 12" = Table.ReplaceValue(#"Replaced value 11", "780-810", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 13" = Table.ReplaceValue(#"Replaced value 12", "630-660", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 14" = Table.ReplaceValue(#"Replaced value 13", "600-630", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 15" = Table.ReplaceValue(#"Replaced value 14", "570-600", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 16" = Table.ReplaceValue(#"Replaced value 15", "540-570", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 17" = Table.ReplaceValue(#"Replaced value 16", "510-540", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 18" = Table.ReplaceValue(#"Replaced value 17", "480-510", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 19" = Table.ReplaceValue(#"Replaced value 18", "450-480", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 20" = Table.ReplaceValue(#"Replaced value 19", "420-450", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 21" = Table.ReplaceValue(#"Replaced value 20", "390-420", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 22" = Table.ReplaceValue(#"Replaced value 21", "330-360", "180-365", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 23" = Table.ReplaceValue(#"Replaced value 22", "360-390", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Sorted rows 1" = Table.Sort(#"Replaced value 23", {{"Buckets", Order.Ascending}}),
  #"Replaced value 24" = Table.ReplaceValue(#"Sorted rows 1", "1020-1050", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 25" = Table.ReplaceValue(#"Replaced value 24", "1050-1080", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 26" = Table.ReplaceValue(#"Replaced value 25", "1080-1110", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 27" = Table.ReplaceValue(#"Replaced value 26", "120-150", "120-180", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 28" = Table.ReplaceValue(#"Replaced value 27", "1110-1140", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 29" = Table.ReplaceValue(#"Replaced value 28", "1140-1170", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 30" = Table.ReplaceValue(#"Replaced value 29", "1170-1200", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 31" = Table.ReplaceValue(#"Replaced value 30", "1260-1290", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 32" = Table.ReplaceValue(#"Replaced value 31", "1200-1230", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 33" = Table.ReplaceValue(#"Replaced value 32", "1230-1260", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 34" = Table.ReplaceValue(#"Replaced value 33", "1290-1320", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 35" = Table.ReplaceValue(#"Replaced value 34", "1320-1350", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 36" = Table.ReplaceValue(#"Replaced value 35", "1350-1380", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 37" = Table.ReplaceValue(#"Replaced value 36", "150-180", "120-180", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 38" = Table.ReplaceValue(#"Replaced value 37", "1380-1410", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 39" = Table.ReplaceValue(#"Replaced value 38", "180-210", "180-365", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 40" = Table.ReplaceValue(#"Replaced value 39", "210-240", "180-365", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 41" = Table.ReplaceValue(#"Replaced value 40", "240-270", "180-365", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 42" = Table.ReplaceValue(#"Replaced value 41", "300-330", "180-365", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 43" = Table.ReplaceValue(#"Replaced value 42", "270-300", "180-365", Replacer.ReplaceValue, {"Buckets"}),
  #"Transform columns 2" = Table.TransformColumnTypes(#"Replaced value 43", {{"Date of Kati Action", type text}, {"Days since Service", type text}, {"Days since last Kati Action", type text}, {"Corrected Aging Days", type text}}),
  #"Replace errors 2" = Table.ReplaceErrorValues(#"Transform columns 2", {{"Date of Kati Action", null}, {"Days since Service", null}, {"Days since last Kati Action", null}, {"Corrected Aging Days", null}}),
  #"Transform columns 3" = Table.TransformColumnTypes(#"Replace errors 2", {{"adjustment_group_code", type text}, {"adjustment_reason_code", type text}, {"adjustmenttype_id", type text}}),
  #"Replace errors 3" = Table.ReplaceErrorValues(#"Transform columns 3", {{"adjustment_group_code", null}, {"adjustment_reason_code", null}, {"adjustmenttype_id", null}}),
  #"Replaced value 44" = Table.ReplaceValue(#"Replace errors 3", "Partner2fFixCredentialing", "Clinician Credentialing Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 45" = Table.ReplaceValue(#"Replaced value 44", "Partner2FixPendingWOAdjustment", "JW to Writeoff", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 46" = Table.ReplaceValue(#"Replaced value 45", "Partner2FixTimelyFiling", "VOA Investigate Timely Filing", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 47" = Table.ReplaceValue(#"Replaced value 46", "P2fixMCO2FixEscalation", "Escalated to MCO", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 48" = Table.ReplaceValue(#"Replaced value 47", "Partner2FixEligibility", "Client Eligibility Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 49" = Table.ReplaceValue(#"Replaced value 48", "P2FixCPTIMOD", "Modifier Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 50" = Table.ReplaceValue(#"Replaced value 49", "P2FixNotCoveredByPayer", "Secondary Insurance Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 51" = Table.ReplaceValue(#"Replaced value 50", "P2FixDocumentation", "VOA to fix Missing Documentation", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 52" = Table.ReplaceValue(#"Replaced value 51", "C2FixClaiminprocess", "Credible Reconsideration to Payer", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 53" = Table.ReplaceValue(#"Replaced value 52", "C2FixAppealUnderReview", "Credible Appeal", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 54" = Table.ReplaceValue(#"Replaced value 53", "C2FixConfiguration", "Credible Fix Configuration", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 55" = Table.ReplaceValue(#"Replaced value 54", "C2FixDuplicate", "Credible to fix Corrective Claim", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 56" = Table.ReplaceValue(#"Replaced value 55", "C2FixAppeal", "Credible to Fix Appeal", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 57" = Table.ReplaceValue(#"Replaced value 56", "C2FixPosting", "Credible to Fix Posting", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 58" = Table.ReplaceValue(#"Replaced value 57", "C2FixRejection", "Credible to Fix Rejection", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 59" = Table.ReplaceValue(#"Replaced value 58", "C2FixTimely", "Credible to Fix Timely", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 60" = Table.ReplaceValue(#"Replaced value 59", "P2FixBenefitsMaxed", "VOA Exceeded Units", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 61" = Table.ReplaceValue(#"Replaced value 60", "P2FixDemographics", "Demographic Error(s)", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 62" = Table.ReplaceValue(#"Replaced value 61", "P2FixInfoRequestfromPatientByPayer", "Medicaid Portal Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 63" = Table.ReplaceValue(#"Replaced value 62", "Credible2FixCallinsurance", "Credible to Call Insurance", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 64" = Table.ReplaceValue(#"Replaced value 63", "Credible2FixCorrectedClaim", "Credible to Fix Corrected Claim", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 65" = Table.ReplaceValue(#"Replaced value 64", "Credible2FixDropToPaper", "Credible Drop to Paper", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 66" = Table.ReplaceValue(#"Replaced value 65", "Partner2FixInvalidModifier", "Invalid Modifier", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 67" = Table.ReplaceValue(#"Replaced value 66", "P2FixLocation", "Service Location Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 68" = Table.ReplaceValue(#"Replaced value 67", "P2FixMcaidEnrollmentPend", "Medicaid Portal Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 69" = Table.ReplaceValue(#"Replaced value 68", "Partner2FixAuth", "Authorization Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 70" = Table.ReplaceValue(#"Replaced value 69", "Partner2FixInsurance", "Client Insurance Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 71" = Table.ReplaceValue(#"Replaced value 70", "Partner2Fix", "General Problem", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 72" = Table.ReplaceValue(#"Replaced value 71", "Partner2ReviewAccounting", "Accounting Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 73" = Table.ReplaceValue(#"Replaced value 72", "Partner2ReviewClinical", "Clinical Issue", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Replaced value 74" = Table.ReplaceValue(#"Replaced value 73", "Credible2Fix", "Credible General Problem", Replacer.ReplaceValue, {"Billing Review Status"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Replaced value 74", {{"adjustment_reason_code", "Crosswalk Codes"}}),
  #"Merged queries" = Table.NestedJoin(#"Renamed columns 2", {"Crosswalk Codes"}, #"BRS Cross", {"Adjustment Code"}, "BRS Cross", JoinKind.LeftOuter),
  #"Expanded BRS Cross" = Table.ExpandTableColumn(#"Merged queries", "BRS Cross", {"Description"}, {"Description"}),
  #"Extracted text before delimiter 2" = Table.TransformColumns(#"Expanded BRS Cross", {{"appr_date", each Text.BeforeDelimiter(Text.From(_), "T", 0), type text}}),
  #"Extracted text before delimiter 3" = Table.TransformColumns(#"Extracted text before delimiter 2", {{"signature_datetime", each Text.BeforeDelimiter(Text.From(_), "T", 0), type text}}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Extracted text before delimiter 3", {{"signature_datetime", type date}, {"appr_date", type date}}),
  #"Added custom 2" = Table.AddColumn(#"Changed column type 4", "Custom", each Duration.Days (Date.From(DateTime.FixedLocalNow())- Date.From([appr_date]))),
  #"Renamed columns 3" = Table.RenameColumns(#"Added custom 2", {{"Custom", "Days Since Approval"}}),
  #"Added custom 3" = Table.AddColumn(#"Renamed columns 3", "Custom", each let rangeSize = 30, offset = 0, inclusive = false, rangeIndex = Number.RoundDown(([Days Since Approval] - offset) / rangeSize) in Text.From(rangeIndex * rangeSize + offset, "en-US") & "-" & Text.From((rangeIndex + 1) * rangeSize + offset - (if inclusive then 1 else 0), "en-US")),
  #"Renamed columns 4" = Table.RenameColumns(#"Added custom 3", {{"Custom", "Approval Buckets"}}),
  #"Transform columns 4" = Table.TransformColumnTypes(#"Renamed columns 4", {{"Days Since Approval", type text}, {"Approval Buckets", type text}}),
  #"Replace errors 4" = Table.ReplaceErrorValues(#"Transform columns 4", {{"Days Since Approval", null}, {"Approval Buckets", null}}),
  #"Replaced value 75" = Table.ReplaceValue(#"Replace errors 4", "1650-1680", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 76" = Table.ReplaceValue(#"Replaced value 75", "1620-1650", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 77" = Table.ReplaceValue(#"Replaced value 76", "1590-1620", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 78" = Table.ReplaceValue(#"Replaced value 77", "1560-1590", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 79" = Table.ReplaceValue(#"Replaced value 78", "1410-1440", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 80" = Table.ReplaceValue(#"Replaced value 79", "1530-1560", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 81" = Table.ReplaceValue(#"Replaced value 80", "1500-1530", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 82" = Table.ReplaceValue(#"Replaced value 81", "1470-1500", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Replaced value 83" = Table.ReplaceValue(#"Replaced value 82", "1440-1470", "365+", Replacer.ReplaceValue, {"Buckets"}),
  #"Inserted conditional column 2" = Table.AddColumn(#"Replaced value 83", "BRS Categories", each if [Billing Review Status] = "Accounting Issue" then "General" else if Text.Contains([Billing Review Status], "Credentialing") then "Clinician Credentials" else if Text.Contains([Billing Review Status], "Eligibility") then "Client Issues" else ""),
  #"Transform columns 5" = Table.TransformColumnTypes(#"Inserted conditional column 2", {{"BRS Categories", type text}}),
  #"Replace errors 5" = Table.ReplaceErrorValues(#"Transform columns 5", {{"BRS Categories", null}}),
  #"Inserted conditional column 3" = Table.AddColumn(#"Replace errors 5", "Custom", each if Text.Contains([Action Description], "Status:") then [Action Description] else if Text.Contains([Action Description], "status:") then [Action Description] else ""),
  #"Extracted text after delimiter" = Table.TransformColumns(#"Inserted conditional column 3", {{"Custom", each Text.AfterDelimiter(Text.From(_), ": ", 0), type text}}),
  #"Renamed columns 5" = Table.RenameColumns(#"Extracted text after delimiter", {{"Custom", "Prior BRS"}})
in
  #"Renamed columns 5";
shared raw_credible_brs_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f12b0505-9183-40c7-a6d8-3b9e2314ca9a"]}[Data],
  TableNavigation = Navigation_2{[Id = "raw_credible_brs", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
