[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "API - Outreach Service_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared #"API - Outreach Service" = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2r1OkQYY7dl3jpHEC3CGjVlQ__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3="), null, 65001),
  #"Navigation 1" = Source{1}[Table],
  #"Expanded Table" = Table.ExpandTableColumn(#"Navigation 1", "Table", {"Name", "Table"}, {"Name.1", "Table.1"}),
  #"Expanded Table.1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}),
  #"Expanded Table 1" = Table.ExpandTableColumn(#"Expanded Table.1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}),
  #"Expanded Table.1 1" = Table.ExpandTableColumn(#"Expanded Table 1", "Table.1", {"clientvisit_id", "font_colornavytarget_categoryf_559762_university_1012132", "i_select_universityi_559763", "font_colornavynumber_of_people_559765", "font_colornavymarketing_materi_559767_push_cards_1012189", "font_colornavybrief_summary_of_559770_notes", "font_colornavyfollowup_planned_559771", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "supported_education_or_employm_559749_education_1012105", "type_of_contact_559750", "was_the_client_present_559755", "name_of_contact_or_persons_pre_559753", "name_of_institutionschoolcolle_559754", "brief_description_of_contact_559756_notes", "are_there_any_notable_problems_559757", "progress_since_last_session_559758", "next_scheduled_checkin_559759", "ihomework_what_will_be_address_559761_notes", "font_colornavytarget_categoryf_559762_public_school_1012131", "font_colornavyname_of_outreach_559963", "font_colornavytarget_categoryf_559762_community_organization_1012137", "font_colornavymarketing_materi_559767_fliers_1012188", "are_there_any_notable_problems_559757_notes", "supported_education_or_employm_559749_employment_1012106", "font_colornavytarget_categoryf_559762_medical_professional_1012130", "font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "font_colornavytarget_categoryf_559762_policeprison_1012135", "font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "font_colorpurplenumber_of_flie_559768", "font_colorpurplenumber_of_push_559769", "i_select_mental_health_profess_559764", "location_of_contact_559751", "purpose_of_this_sed_service_559752_transition_planning_1012118", "purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "were_other_individuals_present_574585", "purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "purpose_of_this_sed_service_559752_identification_of_educational__1012114", "purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "purpose_of_this_sed_service_559752_employment_skills_training_1035701", "purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "bdescription_of_serviceb_585056", "bdescription_of_serviceb_585056_notes", "location_of_contact_559751_notes", "purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "font_colornavyprograms_include_594438_epicenter_1066407", "font_colornavyother_voa_staff__594468", "font_colornavytype_of_contactf_594470_inperson_1066517", "font_colornavypersons_spoke_to_594469", "font_colornavyfollowup_planned_559771_notes", "font_colornavyprograms_include_594438_visions_of_hope_groups_1066409", "font_colornavymarketing_materi_559767_foodsnacks_1066748", "font_colorpurpletype_of_foodsn_594624", "font_colornavymarketing_materi_559767_marketing_swag_1066749", "font_colornavymarketing_materi_559767_notes"}, {"clientvisit_id", "font_colornavytarget_categoryf_559762_university_1012132", "i_select_universityi_559763", "font_colornavynumber_of_people_559765", "font_colornavymarketing_materi_559767_push_cards_1012189", "font_colornavybrief_summary_of_559770_notes", "font_colornavyfollowup_planned_559771", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "supported_education_or_employm_559749_education_1012105", "type_of_contact_559750", "was_the_client_present_559755", "name_of_contact_or_persons_pre_559753", "name_of_institutionschoolcolle_559754", "brief_description_of_contact_559756_notes", "are_there_any_notable_problems_559757", "progress_since_last_session_559758", "next_scheduled_checkin_559759", "ihomework_what_will_be_address_559761_notes", "font_colornavytarget_categoryf_559762_public_school_1012131", "font_colornavyname_of_outreach_559963", "font_colornavytarget_categoryf_559762_community_organization_1012137", "font_colornavymarketing_materi_559767_fliers_1012188", "are_there_any_notable_problems_559757_notes", "supported_education_or_employm_559749_employment_1012106", "font_colornavytarget_categoryf_559762_medical_professional_1012130", "font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "font_colornavytarget_categoryf_559762_policeprison_1012135", "font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "font_colorpurplenumber_of_flie_559768", "font_colorpurplenumber_of_push_559769", "i_select_mental_health_profess_559764", "location_of_contact_559751", "purpose_of_this_sed_service_559752_transition_planning_1012118", "purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "were_other_individuals_present_574585", "purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "purpose_of_this_sed_service_559752_identification_of_educational__1012114", "purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "purpose_of_this_sed_service_559752_employment_skills_training_1035701", "purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "bdescription_of_serviceb_585056", "bdescription_of_serviceb_585056_notes", "location_of_contact_559751_notes", "purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "font_colornavyprograms_include_594438_epicenter_1066407", "font_colornavyother_voa_staff__594468", "font_colornavytype_of_contactf_594470_inperson_1066517", "font_colornavypersons_spoke_to_594469", "font_colornavyfollowup_planned_559771_notes", "font_colornavyprograms_include_594438_visions_of_hope_groups_1066409", "font_colornavymarketing_materi_559767_foodsnacks_1066748", "font_colorpurpletype_of_foodsn_594624", "font_colornavymarketing_materi_559767_marketing_swag_1066749", "font_colornavymarketing_materi_559767_notes"}),
  #"Removed columns" = Table.RemoveColumns(#"Expanded Table.1 1", {"Name", "Name.1", "Name.2", "Name.3"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"clientvisit_id", "service_id"}, {"font_colornavytarget_categoryf_559762_university_1012132", "university_flag"}, {"i_select_universityi_559763", "university_name"}, {"font_colornavynumber_of_people_559765", "num_of_people"}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed columns", {{"num_of_people", Int64.Type}}),
  #"Renamed columns 1" = Table.RenameColumns(#"Changed column type", {{"font_colornavymarketing_materi_559767_push_cards_1012189", "pushCard_flag"}, {"font_colornavybrief_summary_of_559770_notes", "summary"}, {"font_colornavyfollowup_planned_559771", "follow_up"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns 1", {"urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Removed columns 1", {{"supported_education_or_employm_559749_education_1012105", "supportedED_or_Employment"}, {"type_of_contact_559750", "contact_type"}, {"was_the_client_present_559755", "client_present"}, {"name_of_contact_or_persons_pre_559753", "contact_name"}, {"name_of_institutionschoolcolle_559754", "institution_name"}, {"brief_description_of_contact_559756_notes", "desc_of_contact\"}, {"are_there_any_notable_problems_559757", "notable_problems"}}),
  #"Removed columns 2" = Table.RemoveColumns(#"Renamed columns 2", {"desc_of_contact\", "notable_problems", "progress_since_last_session_559758", "next_scheduled_checkin_559759", "ihomework_what_will_be_address_559761_notes"}),
  #"Renamed columns 3" = Table.RenameColumns(#"Removed columns 2", {{"font_colornavytarget_categoryf_559762_public_school_1012131", "public_school_flag"}, {"font_colornavyname_of_outreach_559963", "outreach_name"}, {"font_colornavytarget_categoryf_559762_community_organization_1012137", "commORG_flag"}, {"font_colornavymarketing_materi_559767_fliers_1012188", "fliers_flag"}}),
  #"Removed columns 3" = Table.RemoveColumns(#"Renamed columns 3", {"are_there_any_notable_problems_559757_notes", "supported_education_or_employm_559749_employment_1012106"}),
  #"Renamed columns 4" = Table.RenameColumns(#"Removed columns 3", {{"font_colornavytarget_categoryf_559762_medical_professional_1012130", "medical_flag"}, {"font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "substance_flag"}, {"font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "mhp_flag"}, {"font_colornavytarget_categoryf_559762_policeprison_1012135", "police_flag"}, {"font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "social_flag"}, {"font_colorpurplenumber_of_flie_559768", "num_of_fliers"}, {"font_colorpurplenumber_of_push_559769", "num_of_pushcards"}, {"i_select_mental_health_profess_559764", "mhp_name"}, {"location_of_contact_559751", "location"}}),
  #"Removed columns 4" = Table.RemoveColumns(#"Renamed columns 4", {"purpose_of_this_sed_service_559752_transition_planning_1012118", "purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "were_other_individuals_present_574585", "purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "purpose_of_this_sed_service_559752_identification_of_educational__1012114", "purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "purpose_of_this_sed_service_559752_employment_skills_training_1035701", "purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "bdescription_of_serviceb_585056", "bdescription_of_serviceb_585056_notes"}),
  #"Renamed columns 5" = Table.RenameColumns(#"Removed columns 4", {{"location_of_contact_559751_notes", "location_notes"}}),
  #"Removed columns 5" = Table.RemoveColumns(#"Renamed columns 5", {"purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "font_colornavyprograms_include_594438_epicenter_1066407"}),
  #"Renamed columns 6" = Table.RenameColumns(#"Removed columns 5", {{"font_colornavyother_voa_staff__594468", "other_voa"}, {"font_colornavytype_of_contactf_594470_inperson_1066517", "inperson_flag"}, {"font_colornavypersons_spoke_to_594469", "spoke_to"}}),
  #"Removed columns 6" = Table.RemoveColumns(#"Renamed columns 6", {"font_colornavyfollowup_planned_559771_notes", "font_colornavyprograms_include_594438_visions_of_hope_groups_1066409"}),
  #"Renamed columns 7" = Table.RenameColumns(#"Removed columns 6", {{"font_colornavymarketing_materi_559767_foodsnacks_1066748", "food_flag"}, {"font_colorpurpletype_of_foodsn_594624", "food_desc"}, {"font_colornavymarketing_materi_559767_marketing_swag_1066749", "swag_flag"}, {"font_colornavymarketing_materi_559767_notes", "swag_desc"}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Renamed columns 7", {{"swag_desc", type text}, {"swag_flag", type text}, {"food_desc", type text}, {"food_flag", type text}, {"spoke_to", type text}, {"inperson_flag", type text}, {"other_voa", type text}, {"location_notes", type text}, {"location", type text}, {"mhp_name", type text}, {"num_of_pushcards", Int64.Type}, {"num_of_fliers", Int64.Type}, {"social_flag", type text}, {"police_flag", type text}, {"mhp_flag", type text}, {"substance_flag", type text}, {"medical_flag", type text}, {"fliers_flag", type text}, {"commORG_flag", type text}, {"outreach_name", type text}, {"public_school_flag", type text}, {"institution_name", type text}, {"service_id", type text}, {"university_flag", type text}, {"university_name", type text}, {"pushCard_flag", type text}, {"summary", type text}, {"follow_up", type text}, {"supportedED_or_Employment", type text}, {"contact_type", type text}, {"client_present", type text}, {"contact_name", type text}}),
  #"Replaced value 1" = Table.ReplaceValue(#"Changed column type 1", null, "n/a", Replacer.ReplaceValue, {"outreach_name"}),
  #"Replaced value" = Table.ReplaceValue(#"Replaced value 1", null, "n/a", Replacer.ReplaceValue, {"institution_name"}),
  #"Inserted conditional column" = Table.AddColumn(#"Replaced value", "address", each if Text.Contains([institution_name], "Apollo") then "2400 Viking Dr, Bossier City, LA 71111" else if Text.Contains([institution_name], "Captain") then "6115 E Kings Hwy, Shreveport, LA 71105" else if Text.Contains([institution_name], "Lighthouse") then "802 Travis Street, Shreveport, LA 71101" else if Text.Contains([institution_name], "Louisiana State") then "1 University Pl, Shreveport, LA 71115" else if Text.Contains([outreach_name], "Bossier Parish School Board") then "3228 Barksdale Blvd, Bossier City, LA 71112" else if Text.Contains([outreach_name], "Minden Behavioral Health Clinic") then "502 Nella St, Minden, LA 71055" else if Text.Contains([outreach_name], "Provision Rehab") then "733 Keyser Ave, Natchitoches, LA 71457 " else if Text.Contains([outreach_name], "NWLTCC") then "2010 N Market St, Shreveport, LA 71107" else if Text.Contains([outreach_name], "Peaceful Alternatives Counseling and Therapy") then "3020 Knight St, Shreveport, LA 71105" else if Text.Contains([outreach_name], "Shreve Memorial Libraries - Hamilton/South Caddo") then "2111 Bert Kouns Industrial Loop, Shreveport, LA 71118" else if Text.Contains([outreach_name], "Natchitoches Sheriff Department") then "200 Church St, Natchitoches, LA 71457" else if Text.Contains([outreach_name], "Claiborne Parish School Board") then "415 E Main St, Homer, LA 71040" else ""),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Inserted conditional column", {{"address", type text}})
in
  #"Changed column type 2";
shared #"API - Outreach Service_DataDestination" = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "74be8ffb-fa88-4278-9a30-358e88a4f13a"]}[Data],
  TableNavigation = Navigation_2{[Id = "API - Outreach Service", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
