[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "raw_cred_assess_assign_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared raw_cred_assess_assign = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2rrTVR2S6-g91kod-AOKJFUQ__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3=")),
  #"Navigation 1" = Source{1}[Table],
  #"Expanded Table" = Table.ExpandTableColumn(#"Navigation 1", "Table", {"Name", "Table"}, {"Name.1", "Table.1"}),
  #"Expanded Table.1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}),
  #"Expanded Table 1" = Table.ExpandTableColumn(#"Expanded Table.1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}),
  #"Expanded Table.1 1" = Table.ExpandTableColumn(#"Expanded Table 1", "Table.1", {"clientvisit_id", "what_month_was_the_clients_eli_594260", "check_type_of_insurances_was_c_594261_medicaid_1065987", "has_mco_changed_594263_no_1065998", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "check_type_of_insurances_was_c_594261_medicare_traditional_1065988", "check_type_of_insurances_was_c_594261_medicare_advantage_plan_1065989", "what_is_the_payer_level_for_th_594384_primary_1066226", "what_is_the_payer_level_for_th_594384_tertiary_1066228", "additional_notes_regarding_eli_594386", "additional_notes_regarding_eli_594386_notes", "what_is_the_payer_level_for_th_594384_secondary_1066227", "if_medicare_switched_from_trad_594385", "has_mco_changed_594263_yes_1065997", "if_yes_who_is_the_new_insuranc_594264_medicare_advantage_plan_1066028", "check_type_of_insurances_was_c_594261_commercial_1065990", "if_yes_who_is_the_new_insuranc_594264_medicaid_united_healthcare_1066022", "if_yes_who_is_the_new_insuranc_594264_commercial_united_healthcare_1066024", "if_yes_who_is_the_new_insuranc_594264_medicaid_humana_1065994"}, {"clientvisit_id", "what_month_was_the_clients_eli_594260", "check_type_of_insurances_was_c_594261_medicaid_1065987", "has_mco_changed_594263_no_1065998", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "check_type_of_insurances_was_c_594261_medicare_traditional_1065988", "check_type_of_insurances_was_c_594261_medicare_advantage_plan_1065989", "what_is_the_payer_level_for_th_594384_primary_1066226", "what_is_the_payer_level_for_th_594384_tertiary_1066228", "additional_notes_regarding_eli_594386", "additional_notes_regarding_eli_594386_notes", "what_is_the_payer_level_for_th_594384_secondary_1066227", "if_medicare_switched_from_trad_594385", "has_mco_changed_594263_yes_1065997", "if_yes_who_is_the_new_insuranc_594264_medicare_advantage_plan_1066028", "check_type_of_insurances_was_c_594261_commercial_1065990", "if_yes_who_is_the_new_insuranc_594264_medicaid_united_healthcare_1066022", "if_yes_who_is_the_new_insuranc_594264_commercial_united_healthcare_1066024", "if_yes_who_is_the_new_insuranc_594264_medicaid_humana_1065994"}),
  #"Removed columns" = Table.RemoveColumns(#"Expanded Table.1 1", {"Name", "Name.1", "Name.2", "Name.3"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"clientvisit_id", "Service ID"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns", {"urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Removed columns 1", {{"what_month_was_the_clients_eli_594260", "Month"}, {"check_type_of_insurances_was_c_594261_medicaid_1065987", "medicaid"}, {"has_mco_changed_594263_no_1065998", "mco_change"}, {"check_type_of_insurances_was_c_594261_medicare_traditional_1065988", "medicare"}, {"check_type_of_insurances_was_c_594261_medicare_advantage_plan_1065989", "medicare_adv"}, {"what_is_the_payer_level_for_th_594384_primary_1066226", "payer_level"}, {"what_is_the_payer_level_for_th_594384_tertiary_1066228", "payer_level_tert"}, {"additional_notes_regarding_eli_594386", "notes"}, {"additional_notes_regarding_eli_594386_notes", "addt_notes"}, {"what_is_the_payer_level_for_th_594384_secondary_1066227", "secondary"}, {"if_medicare_switched_from_trad_594385", "medicare_switch"}}),
  #"Transform columns" = Table.TransformColumnTypes(#"Renamed columns 1", {{"Service ID", type text}, {"Month", type text}, {"medicaid", type text}, {"mco_change", type text}, {"medicare", type text}, {"medicare_adv", type text}, {"payer_level", type text}, {"payer_level_tert", type text}, {"notes", type text}, {"addt_notes", type text}, {"secondary", type text}, {"medicare_switch", type text}, {"has_mco_changed_594263_yes_1065997", type text}, {"if_yes_who_is_the_new_insuranc_594264_medicare_advantage_plan_1066028", type text}, {"check_type_of_insurances_was_c_594261_commercial_1065990", type text}, {"if_yes_who_is_the_new_insuranc_594264_medicaid_united_healthcare_1066022", type text}, {"if_yes_who_is_the_new_insuranc_594264_commercial_united_healthcare_1066024", type text}, {"if_yes_who_is_the_new_insuranc_594264_medicaid_humana_1065994", type text}}),
  #"Replace errors" = Table.ReplaceErrorValues(#"Transform columns", {{"Service ID", null}, {"Month", null}, {"medicaid", null}, {"mco_change", null}, {"medicare", null}, {"medicare_adv", null}, {"payer_level", null}, {"payer_level_tert", null}, {"notes", null}, {"addt_notes", null}, {"secondary", null}, {"medicare_switch", null}, {"has_mco_changed_594263_yes_1065997", null}, {"if_yes_who_is_the_new_insuranc_594264_medicare_advantage_plan_1066028", null}, {"check_type_of_insurances_was_c_594261_commercial_1065990", null}, {"if_yes_who_is_the_new_insuranc_594264_medicaid_united_healthcare_1066022", null}, {"if_yes_who_is_the_new_insuranc_594264_commercial_united_healthcare_1066024", null}, {"if_yes_who_is_the_new_insuranc_594264_medicaid_humana_1065994", null}}),
  #"Renamed columns 2" = Table.RenameColumns(#"Replace errors", {{"Service ID", "service_id"}, {"Month", "month"}, {"has_mco_changed_594263_yes_1065997", "mco_change_yes"}, {"if_yes_who_is_the_new_insuranc_594264_medicare_advantage_plan_1066028", "new_medicare_adv"}, {"check_type_of_insurances_was_c_594261_commercial_1065990", "new_commercial"}, {"if_yes_who_is_the_new_insuranc_594264_medicaid_united_healthcare_1066022", "new_uhc"}, {"if_yes_who_is_the_new_insuranc_594264_commercial_united_healthcare_1066024", "new_commercial_uhc"}, {"if_yes_who_is_the_new_insuranc_594264_medicaid_humana_1065994", "new_humana"}})
in
  #"Renamed columns 2";
shared raw_cred_assess_assign_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "1b643108-97a2-432c-a0c0-391df26e0eea"]}[Data],
  TableNavigation = Navigation_2{[Id = "raw_cred_eligibility", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
