table 'Aggregated Any Goals'
	lineageTag: ba894b60-3250-4c48-9754-25f0330fea78

	column goal
		dataType: string
		lineageTag: 0cb6ea7a-1d50-4c94-b373-922cba88e909
		summarizeBy: none
		sourceColumn: goal

		annotation SummarizationSetBy = Automatic

	column positive_progress
		dataType: double
		formatString: 0
		lineageTag: 3ce14c3a-fd57-4d27-a8ab-26a3f1ac0d20
		summarizeBy: none
		sourceColumn: positive_progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column all_monitored
		dataType: double
		formatString: 0
		lineageTag: a8b011df-5efa-43f4-b981-79f222942deb
		summarizeBy: none
		sourceColumn: all_monitored

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column positive_perc
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: 25e96150-317c-459c-a0a7-84ba410ac1ef
		summarizeBy: none
		sourceColumn: positive_perc

		annotation SummarizationSetBy = Automatic

	partition 'Aggregated Any Goals' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"All Goals - Any Progress by School", #"cis cis_behavior_positive_count", #"cis cis_academics_positive_count", #"Attendance - Positive Progress by School"}),
				    #"Replaced Value" = Table.ReplaceValue(Source,"Broadmoor STEM Academy","Broadmoor",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Caddo Middle Career and Technology School","CMCTS",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Woodlawn High School","Woodlawn",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Westwood Elementary","Westwood",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Caddo Heights Elementary","Caddo Heights",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Bethune-Oak Park","Bethune",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Midway Professional Development Center","Midway",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Creswell Elementary School","Creswell",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Atkins Technology Elementary School","Atkins",Replacer.ReplaceText,{"school_name"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value8", each ([goal] = "Any Goal")),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"goal"}, {{"positive_progress", each List.Sum([positive_progress]), type nullable number}, {"all_monitored", each List.Sum([all_monitored]), type nullable number}}),
				    #"Inserted Division" = Table.AddColumn(#"Grouped Rows", "Division", each [positive_progress] / [all_monitored], type number),
				    #"Changed Type" = Table.TransformColumnTypes(#"Inserted Division",{{"Division", Percentage.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Division", "positive_perc"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

