table 'All Goals - Any Progress by School'
	lineageTag: f066d393-985d-4f97-b52d-41c8b126a28f

	column school_name
		dataType: string
		lineageTag: 069df4a4-86f6-4543-884d-e4b7ecdb89cd
		summarizeBy: none
		sourceColumn: school_name

		annotation SummarizationSetBy = Automatic

	column positive_progress
		dataType: int64
		formatString: 0
		lineageTag: 69297dd8-94dd-4fcf-a533-b4d495e352ac
		summarizeBy: sum
		sourceColumn: positive_progress

		annotation SummarizationSetBy = Automatic

	column all_monitored
		dataType: int64
		formatString: 0
		lineageTag: 772cafe8-82b1-4dbc-8b41-c3a28c459545
		summarizeBy: sum
		sourceColumn: all_monitored

		annotation SummarizationSetBy = Automatic

	column positive_percentage
		dataType: double
		lineageTag: b3c2e0f5-9acc-4355-95bb-cdaa577e0c8c
		summarizeBy: sum
		sourceColumn: positive_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goal
		dataType: string
		lineageTag: 17bb12de-4582-4ffe-a73a-b35cd1f77f00
		summarizeBy: none
		sourceColumn: goal

		annotation SummarizationSetBy = Automatic

	partition 'All Goals - Any Progress by School' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    #"dbo_cis_positive_prog_withRaw_%" = Source{[Schema="dbo",Item="cis_positive_prog_withRaw_%"]}[Data],
				    #"Added Custom" = Table.AddColumn(#"dbo_cis_positive_prog_withRaw_%", "goal", each "Any Goal"),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"cis_progressing", "positive_percentage"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

