table 'Attendance - Positive Progress by School'
	lineageTag: afa4c9de-0e61-4624-b1f9-254145cfc931

	measure 'All Attendance Clients' = SUM('Attendance - Positive Progress by School'[all_monitored])
		formatString: 0
		lineageTag: 139aa746-8713-4c75-91cc-652cca21246e

	measure 'Positive Attendance Clients' = SUM('Attendance - Positive Progress by School'[positive_progress])
		formatString: 0
		lineageTag: 356b1397-c299-431a-b2c1-8bf33e2968d7

	measure 'Cumulative Attendance Percentage' = DIVIDE([Positive Attendance Clients], [All Attendance Clients])
		formatString: 0%;-0%;0%
		lineageTag: 9f9b6f4c-09c7-427d-bf11-10ddf974feb5

	measure 'Leader and Support meeting tooltip' = "The Power BI figures are a replacement for these elements on the old QA Master"
		lineageTag: 23340431-aec8-453d-affe-65b094602c6a

	column school_name
		dataType: string
		lineageTag: 1167cd43-a71d-400c-a2ca-369fa87471ed
		summarizeBy: none
		sourceColumn: school_name

		annotation SummarizationSetBy = Automatic

	column positive_progress
		dataType: int64
		formatString: 0
		lineageTag: 2db3c79d-3463-4178-83c9-97ae1b02c5c9
		summarizeBy: none
		sourceColumn: positive_progress

		annotation SummarizationSetBy = Automatic

	column all_monitored
		dataType: int64
		formatString: 0
		lineageTag: ebc2226b-9b77-4b2a-8858-70d7fe3aa275
		summarizeBy: none
		sourceColumn: all_monitored

		annotation SummarizationSetBy = Automatic

	column positive_percentage
		dataType: double
		lineageTag: c2f31b93-16d3-4069-894c-1036aaee3988
		summarizeBy: none
		sourceColumn: positive_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goal
		dataType: string
		lineageTag: ba8eb0ec-0b80-441e-8136-0ea70ee74bc2
		summarizeBy: none
		sourceColumn: goal

		annotation SummarizationSetBy = Automatic

	partition 'Attendance - Positive Progress by School' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    #"dbo_cis_attendance_pos_wRaw_%" = Source{[Schema="dbo",Item="cis_attendance_pos_wRaw_%"]}[Data],
				    #"Added Custom" = Table.AddColumn(#"dbo_cis_attendance_pos_wRaw_%", "goal", each "Attendance")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

