table 'cis leadership_support_counter'
	lineageTag: 355b898b-6a5e-4354-b349-17deacd1de0f

	measure 'Leader Support Tooltip' =
			"Each site needs 4 meetings with the support staff and school leadership.
			
			These are cumulative over the course of the school year."
		lineageTag: 0ed557d8-f977-4cd0-a4e2-7331ebe08cda

	column org
		dataType: string
		lineageTag: 9ca4b960-53b0-4d78-98d7-66b87a383355
		summarizeBy: none
		sourceColumn: org

		annotation SummarizationSetBy = Automatic

	column support_count
		dataType: int64
		formatString: 0
		lineageTag: d46f0f58-6fa9-406b-afc9-94a689645ee4
		summarizeBy: sum
		sourceColumn: support_count

		annotation SummarizationSetBy = Automatic

	column leadership_count
		dataType: int64
		formatString: 0
		lineageTag: bfa34b60-3558-4c44-887b-85e6a5286cc8
		summarizeBy: sum
		sourceColumn: leadership_count

		annotation SummarizationSetBy = Automatic

	column school_count
		dataType: int64
		formatString: 0
		lineageTag: 6329a526-d9e1-4b83-aa03-3d1089f6dce1
		summarizeBy: sum
		sourceColumn: school_count

		annotation SummarizationSetBy = Automatic

	column support_perc = DIVIDE('cis leadership_support_counter'[support_count], 'cis leadership_support_counter'[school_count])
		formatString: 0%;-0%;0%
		lineageTag: 48f023ec-7aa6-417f-9598-478c7bce3a0a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column leadership_perc = DIVIDE('cis leadership_support_counter'[leadership_count], 'cis leadership_support_counter'[school_count])
		formatString: 0%;-0%;0%
		lineageTag: 528b043d-ae0f-440a-a78d-15587a43957e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'cis leadership_support_counter' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    cis_leadership_support_counter = Source{[Schema="cis",Item="leadership_support_counter"]}[Data]
				in
				    cis_leadership_support_counter

	annotation PBI_ResultType = Table

