table 'Matching Goals Counter'
	lineageTag: 5dd32af9-5477-4d65-9697-50cf5606ab41

	measure matching_goals_percent = DIVIDE(sum('Matching Goals Counter'[Count]),SUM('Quarterly All Planned supports'[Count]))
		formatString: 0%;-0%;0%
		lineageTag: f2f2507f-a94f-4f78-9c45-cb6685bce488

	column matching_school_goal
		dataType: string
		lineageTag: 66e91a98-5515-4e8b-9df3-0ed65d3200e7
		summarizeBy: none
		sourceColumn: matching_school_goal

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: 34d2dad5-6c8c-42fe-9c45-e84060ee31eb
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition 'Matching Goals Counter' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    cis_matching_school_goal_count = Source{[Schema="cis",Item="matching_school_goal_count"]}[Data]
				in
				    cis_matching_school_goal_count

	changedProperty = Name

