table 'stagine unexcused'
	lineageTag: e89a40e8-2800-4352-8e1b-f4964f298b46

	column jcampus_unexcused
		dataType: double
		lineageTag: 2e558aa5-8cee-49d5-bea2-4eb96b2e7d77
		summarizeBy: sum
		sourceColumn: jcampus_unexcused

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target
		dataType: int64
		formatString: 0
		lineageTag: b125a7d3-3ba1-4b25-9eb3-a4ab8336bb81
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

	column metric
		dataType: string
		lineageTag: 88067680-5ee4-4243-bc8b-067e49557b41
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column goal
		dataType: string
		lineageTag: ba529b1e-2497-487c-8b3e-d9d71df222a5
		summarizeBy: none
		sourceColumn: goal

		annotation SummarizationSetBy = Automatic

	column client_full_name
		dataType: string
		lineageTag: 00e0dea8-4cb2-4e15-ace7-b05238adcc1f
		summarizeBy: none
		sourceColumn: client_full_name

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: a0a91130-e2b2-4884-84d3-9947762f709a
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column sasid
		dataType: string
		lineageTag: c0bcb153-041c-42e0-ac02-2d9605805175
		summarizeBy: none
		sourceColumn: sasid

		annotation SummarizationSetBy = Automatic

	column school_name
		dataType: string
		lineageTag: 002866e4-3df8-4eae-81f1-af94fee0a332
		summarizeBy: none
		sourceColumn: school_name

		annotation SummarizationSetBy = Automatic

	column unexcused_bad_flag
		dataType: string
		lineageTag: 8e3d7416-ae28-4b85-9a6f-56eb254fb45e
		summarizeBy: none
		sourceColumn: unexcused_bad_flag

		annotation SummarizationSetBy = Automatic

	partition 'stagine unexcused' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    dbo_cis_attendance_goal_clients = Source{[Schema="dbo",Item="cis_attendance_goal_clients"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(dbo_cis_attendance_goal_clients, {"sasid"}, #"Attendance JCampus - Active CIS Clients", {"sasid"}, "Attendance JCampus - Active CIS Clients", JoinKind.LeftOuter),
				    #"Expanded Attendance JCampus - Active CIS Clients" = Table.ExpandTableColumn(#"Merged Queries", "Attendance JCampus - Active CIS Clients", {"Count"}, {"Attendance JCampus - Active CIS Clients.Count"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Attendance JCampus - Active CIS Clients",null,0,Replacer.ReplaceValue,{"Attendance JCampus - Active CIS Clients.Count"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Attendance JCampus - Active CIS Clients.Count", "jcampus_unexcused"}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Renamed Columns", {"client_id"}, #"cis cis_tardies_by_student", {"client_id"}, "cis cis_tardies_by_student", JoinKind.LeftOuter),
				    #"Expanded cis cis_tardies_by_student" = Table.ExpandTableColumn(#"Merged Queries1", "cis cis_tardies_by_student", {"tardies"}, {"cis cis_tardies_by_student.tardies"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Expanded cis cis_tardies_by_student",null,0,Replacer.ReplaceValue,{"cis cis_tardies_by_student.tardies"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value1",{{"cis cis_tardies_by_student.tardies", "tardies"}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns1","Midway Professional Development Center","Midway",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Woodlawn High School","Woodlawn",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Caddo Middle Career and Technology School","CMCTS",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Caddo Heights Elementary","Caddo Heights",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Westwood Elementary","Westwood",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Broadmoor STEM Academy","Broadmoor",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Creswell Elementary School","Creswell",Replacer.ReplaceText,{"school_name"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","Bethune-Oak Park","Bethune",Replacer.ReplaceText,{"school_name"}),
				    #"Sorted Rows" = Table.Sort(#"Replaced Value9",{{"school_name", Order.Ascending}}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Sorted Rows","Atkins Technology Elementary School","Atkins",Replacer.ReplaceText,{"school_name"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Replaced Value10", {"client_id"}, #"staging tardies", {"client_id"}, "ProgMon - Attendance Detail (2)", JoinKind.LeftOuter),
				    #"Expanded ProgMon - Attendance Detail (2)" = Table.ExpandTableColumn(#"Merged Queries2", "ProgMon - Attendance Detail (2)", {"bad_flag"}, {"ProgMon - Attendance Detail (2).bad_flag"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Expanded ProgMon - Attendance Detail (2)",null,-1,Replacer.ReplaceValue,{"ProgMon - Attendance Detail (2).bad_flag"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Replaced Value11",{{"ProgMon - Attendance Detail (2).bad_flag", "tardies_bad_flag"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns2", each ([metric] <> "Tardies")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"jcampus_unexcused", "target", "metric", "goal", "client_full_name", "client_id", "sasid", "school_name"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Other Columns", "unexcused_bad_flag", each if [target] < [jcampus_unexcused] then 1 else 0)
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

