table '2. Employee Measures'
	lineageTag: 6183c611-0231-4d8d-be36-0cac28897b50

	measure 'Expired License Count' =
			CALCULATE(
			    DISTINCTCOUNT('API - Employees'[Employee ID]),
			    FILTER('API - Employees', 'API - Employees'[Days Left in License]<=0)
			)
		formatString: 0
		lineageTag: 61eaadb8-881b-473a-ae92-026980aee953

	measure 'Total License Count' =
			CALCULATE(
			    DISTINCTCOUNT('API - Employees'[Employee ID]),
			    FILTER('API - Employees', 'API - Employees'[license_expire]<>BLANK())
			)
		formatString: 0
		lineageTag: a8e7574f-3010-4728-b18b-a3598384f032

	column Value
		formatString: 0
		lineageTag: fb05377f-b719-4a62-b093-8eaa71ed4723
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition '2. Employee Measures' = calculated
		mode: import
		source = {0}

	annotation PBI_Id = d071a7f9c0c74921831ec4ad0dc091e5

