table 'API - Employees'
	lineageTag: 16f42713-151b-4b03-9dc9-16cea58c5454

	column 'Employee ID'
		dataType: string
		lineageTag: 231ae99f-84c7-4e61-9355-141fd9564c02
		summarizeBy: none
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	column 'Employee Name'
		dataType: string
		lineageTag: 6e236a4e-568e-4ba9-9eb7-8f12f910a54a
		summarizeBy: none
		sourceColumn: Employee Name

		annotation SummarizationSetBy = Automatic

	column 'Employee Status'
		dataType: string
		lineageTag: 6ce53588-2bf9-4f2b-a080-2bd095b53473
		summarizeBy: none
		sourceColumn: Employee Status

		annotation SummarizationSetBy = Automatic

	column username
		dataType: string
		lineageTag: 1ddda669-5f0b-4200-81b3-4e1fef62b244
		summarizeBy: none
		sourceColumn: username

		annotation SummarizationSetBy = Automatic

	column 'Is Supervisor'
		dataType: string
		lineageTag: 671d4eef-6b9f-4c82-ada2-bdd0cd92353b
		summarizeBy: none
		sourceColumn: Is Supervisor

		annotation SummarizationSetBy = Automatic

	column is_doctor
		dataType: string
		lineageTag: ca29c9cd-aeb5-4115-8463-26426da8980f
		summarizeBy: none
		sourceColumn: is_doctor

		annotation SummarizationSetBy = Automatic

	column is_nurse
		dataType: string
		lineageTag: 3509e88e-42f2-401e-9708-f815a89378f8
		summarizeBy: none
		sourceColumn: is_nurse

		annotation SummarizationSetBy = Automatic

	column is_incident_to
		dataType: string
		lineageTag: b003ebd8-5e7e-462f-88ef-a2b6a397cc04
		summarizeBy: none
		sourceColumn: is_incident_to

		annotation SummarizationSetBy = Automatic

	column is_licensed_health_prof
		dataType: string
		lineageTag: a45a06b8-cb8b-439e-9cb2-1e0127f23dd2
		summarizeBy: none
		sourceColumn: is_licensed_health_prof

		annotation SummarizationSetBy = Automatic

	column is_mu_provider
		dataType: string
		lineageTag: 19e957ad-8958-4c84-a5c7-20a2e4b91c0b
		summarizeBy: none
		sourceColumn: is_mu_provider

		annotation SummarizationSetBy = Automatic

	column is_billing_supervisor
		dataType: string
		lineageTag: 9451a6ab-e3f4-4bc7-ac60-5cf32b326123
		summarizeBy: none
		sourceColumn: is_billing_supervisor

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: f48b4e90-a36e-4bd0-869b-4d3972e3467c
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		lineageTag: 319b7fc0-acff-4a5d-beb9-dca5e697a426
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	column Credentials
		dataType: string
		lineageTag: 737ab08b-20f6-48b0-9a4c-83705990bf5b
		summarizeBy: none
		sourceColumn: Credentials

		annotation SummarizationSetBy = Automatic

	column NPI
		dataType: string
		lineageTag: 008f5d11-6965-41d6-9d7f-277829fab051
		summarizeBy: none
		sourceColumn: NPI

		annotation SummarizationSetBy = Automatic

	column 'Hire Date'
		dataType: string
		lineageTag: dc342176-17cf-4262-9154-7c64d2a12e2a
		summarizeBy: none
		sourceColumn: Hire Date

		annotation SummarizationSetBy = Automatic

	column 'Termination Date'
		dataType: string
		lineageTag: e382dd1d-528f-49e3-8315-c2200ae3a563
		summarizeBy: none
		sourceColumn: Termination Date

		annotation SummarizationSetBy = Automatic

	column provider_number
		dataType: string
		lineageTag: 51ebb886-b441-4530-b3c4-5a85d19f6733
		summarizeBy: none
		sourceColumn: provider_number

		annotation SummarizationSetBy = Automatic

	column email_office
		dataType: string
		lineageTag: 8cac19a8-6441-4688-8340-dff1d2aca4f1
		summarizeBy: none
		sourceColumn: email_office

		annotation SummarizationSetBy = Automatic

	column 'Program ID'
		dataType: string
		lineageTag: b809fb34-f321-4601-9456-2cc92e8af85d
		summarizeBy: none
		sourceColumn: Program ID

		annotation SummarizationSetBy = Automatic

	column 'First Name'
		dataType: string
		lineageTag: 6d43a158-a9c1-4029-9995-cb1ea4549f3a
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: e87afc6d-8224-4b2f-a458-fc9374d61e48
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column 'Internal Team'
		dataType: string
		lineageTag: c401125f-7ceb-4ce0-9d7f-51651e2471d0
		summarizeBy: none
		sourceColumn: Internal Team

		annotation SummarizationSetBy = Automatic

	column license_expire
		dataType: dateTime
		formatString: Short Date
		lineageTag: 047ea7ce-b143-4ecd-8a72-4eb320757e17
		summarizeBy: none
		sourceColumn: license_expire

		variation Variation
			isDefault
			relationship: 6f9ff73c-c88c-4833-88e5-b8fb2737920d
			defaultHierarchy: LocalDateTable_07bb3da8-af2e-4e7b-bfcd-1638c7c1f088.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column effective_dates
		dataType: string
		lineageTag: dbdb4d39-93d1-4ab5-9bbc-7b00a9496fc9
		summarizeBy: none
		sourceColumn: effective_dates

		annotation SummarizationSetBy = Automatic

	column Custom
		dataType: dateTime
		formatString: Long Date
		lineageTag: b53a9e9c-67e8-414e-a6ad-87da2fc81191
		summarizeBy: none
		sourceColumn: Custom

		variation Variation
			isDefault
			relationship: 2a53b40b-8552-4013-bca5-8760becbed1e
			defaultHierarchy: LocalDateTable_cac8b401-38e4-4b23-8ca4-5e522daf8609.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Days Left in License'
		dataType: double
		formatString: 0
		lineageTag: 2e83165f-e3ba-4df8-9b33-95e2423e1a3c
		summarizeBy: sum
		sourceColumn: Days Left in License

		annotation SummarizationSetBy = Automatic

	column 'Expired Flag'
		dataType: int64
		formatString: 0
		lineageTag: ad5192ca-10b5-4ac3-af59-08f98ad61e3e
		summarizeBy: sum
		sourceColumn: Expired Flag

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Expired Filter' = ```
			IF('API - Employees'[Expired Flag]=1, "Yes", IF('API - Employees'[Expired Flag]=2, "Less than a month", "No")) 
			```
		lineageTag: b4504541-af05-4a42-b829-e300fc6a36c0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column work_phone
		dataType: string
		lineageTag: 16dc2641-98b2-494f-9313-679da268a641
		summarizeBy: none
		sourceColumn: work_phone

		annotation SummarizationSetBy = Automatic

	column dob
		dataType: dateTime
		formatString: Long Date
		lineageTag: 90b3a6e6-3629-48c6-b7c7-22863cd8c6d7
		summarizeBy: none
		sourceColumn: dob

		variation Variation
			isDefault
			relationship: e2a0d16f-4791-4a5d-8780-74d3735211fb
			defaultHierarchy: LocalDateTable_983b2fc7-a779-41d6-a1ef-f3d71746a6a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column text4
		dataType: string
		lineageTag: e4ebb1e8-6dc8-4a52-aea5-c83962911027
		summarizeBy: none
		sourceColumn: text4

		annotation SummarizationSetBy = Automatic

	column text2
		dataType: string
		lineageTag: da48c7a7-54db-4950-84c1-63b2fa55a1ec
		summarizeBy: none
		sourceColumn: text2

		annotation SummarizationSetBy = Automatic

	column text1
		dataType: string
		lineageTag: 1d5aa38c-74dc-44a8-a4d5-9a0f4c2df271
		summarizeBy: none
		sourceColumn: text1

		annotation SummarizationSetBy = Automatic

	column text3
		dataType: string
		lineageTag: 2aca15c3-6be2-4f7c-a9e8-5aeeb584e676
		summarizeBy: none
		sourceColumn: text3

		annotation SummarizationSetBy = Automatic

	column home_phone
		dataType: string
		lineageTag: 1b53aeb7-8ce2-4d02-a674-69857c369837
		summarizeBy: none
		sourceColumn: home_phone

		annotation SummarizationSetBy = Automatic

	column mobile_phone
		dataType: string
		lineageTag: 05519e1e-3514-4446-952f-4ea295a6ac6f
		summarizeBy: none
		sourceColumn: mobile_phone

		annotation SummarizationSetBy = Automatic

	partition 'API - Employees' = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"2e078b2f-481a-42df-8fee-6d81b3c2dac1" = Workspaces{[workspaceId="2e078b2f-481a-42df-8fee-6d81b3c2dac1"]}[Data],
				    #"14444098-6553-4c81-9fbd-a2a48b9ff763" = #"2e078b2f-481a-42df-8fee-6d81b3c2dac1"{[dataflowId="14444098-6553-4c81-9fbd-a2a48b9ff763"]}[Data],
				    #"API - Employees_" = #"14444098-6553-4c81-9fbd-a2a48b9ff763"{[entity="API - Employees",version=""]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(#"API - Employees_","Martha","Kelly",Replacer.ReplaceText,{"First Name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"license_expire", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Custom", each DateTime.LocalNow()),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Custom", type date}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Custom.1", each [license_expire]-[Custom]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Custom.1", Int64.Type}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type2",null,999,Replacer.ReplaceValue,{"Custom.1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value1",{{"Custom.1", "Days Left in License"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "Expired Flag", each if [Days Left in License] <= 0 then 1 else if [Days Left in License] < 31 then 2 else 0)
				in
				    #"Added Conditional Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

