table 'cis aggregated_planned_supports_good'
	lineageTag: eec0a6a5-308e-49da-b20e-afea062b32c0

	measure 'good quarterly supports percent' = DIVIDE(SUM('cis aggregated_planned_supports_good'[Count]), SUM('cis aggregated_all_planned_supports'[Count]))
		formatString: 0%;-0%;0%
		lineageTag: bd8d0a74-7392-48a5-aa7b-5738a8d6cc3c

	column org
		dataType: string
		lineageTag: f1591a77-f437-4df5-978f-4f9770eecad2
		summarizeBy: none
		sourceColumn: org

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: c8a7d116-73b0-4414-897a-16fa6b584c80
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition 'cis aggregated_planned_supports_good' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    cis_aggregated_planned_supports_good = Source{[Schema="cis",Item="aggregated_planned_supports_good"]}[Data]
				in
				    cis_aggregated_planned_supports_good

	annotation PBI_ResultType = Table

