[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "raw_caddo_grades_export_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared raw_caddo_grades_export = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "1b643108-97a2-432c-a0c0-391df26e0eea"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "raw_caddo_grades_export", ItemKind = "Table"]}[Data],
  #"Inserted conditional column" = Table.AddColumn(#"Navigation 2", "short_name_academics", each if Text.Contains([course], "LANG ART") then "ELA" else if Text.Contains([course], "LANG ARTS") then "ELA" else if Text.Contains([course], "CHEMISTRY") then "Science" else if Text.Contains([course], "LIFE SCIE") then "Science" else if Text.Contains([course], "SOC ST") then "Social Studies" else if Text.Contains([course], "ENGLISH") then "ELA" else if Text.Contains([course], "READING") then "ELA" else if Text.Contains([course], "BIOLOGY") then "Science" else if Text.Contains([course], "ALGEBRA") then "Math" else if Text.Contains([course], "GEOMETRY") then "Math" else if Text.Contains([course], "ELA") then "ELA" else if Text.Contains([course], "SCIENCE") then "Science" else if Text.Contains([course], "HEALTH") then "Elective" else if Text.Contains([course], "MUSIC") then "Elective" else if Text.Contains([course], "H&PE;ELEM GRADES") then "Elective" else if Text.Contains([course], "MATH") then "Math" else if Text.Contains([course], "SCI AL") then "Science" else if Text.Contains([course], "CONDUCT") then "Conduct" else if Text.Contains([course], "READ AL") then "ELA" else if Text.Contains([course], "HIST") then "History" else if Text.Contains([course], "PE ") then "Elective" else if Text.Contains([course], "ALT HOME") then "Elective" else if Text.Contains([course], "SPEECH") then "Elective" else if Text.Contains([course], "ADAPTIVE PE") then "Elective" else if Text.Contains([course], "BAND") then "Elective" else if Text.Contains([course], "LIFE SKILLS") then "Elective" else if Text.Contains([course], "STEM") then "Science" else if Text.Contains([course], "CHOIR") then "Elective" else if Text.Contains([course], "COMP LIT") then "Elective" else if Text.Contains([course], "STUDY SKILL") then "Elective" else if Text.Contains([course], "PIANO") then "Elective" else if Text.Contains([course], "QUEST") then "Elective" else if Text.Contains([course], "IBCA") then "Elective" else if Text.Contains([course], "ROBOTICS") then "Elective" else if Text.Contains([course], "ENG AL") then "ELA" else if Text.Contains([course], "ACADEMIC READ") then "Elective" else if Text.Contains([course], "GUITAR") then "Elective" else if Text.Contains([course], "CMC LAB") then "Elective" else if Text.Contains([course], "COMPUTER LIT") then "Elective" else if Text.Contains([course], "4 SUCC") then "Elective" else if Text.Contains([course], "ACAD READ") then "Elective" else if Text.Contains([course], "EUROP HIS") then "History" else if Text.Contains([course], "JAG") then "Elective" else if Text.Contains([course], "KEYBOARD") then "Elective" else if Text.Contains([course], "ENGR/COMP") then "ELA" else if Text.Contains([course], "SPANISH") then "Elective" else if Text.Contains([course], "WELDING") then "Elective" else if [course] = "FRENCH" then "Elective" else if Text.Contains([course], "BUSINESS") then "Elective" else if Text.Contains([course], "CYBER") then "Elective" else if Text.Contains([course], "FORENSICS") then "Elective" else if Text.Contains([course], "ENG ") then "ELA" else if Text.Contains([course], "BIO ") then "Science" else if Text.Contains([course], "HUM AN") then "Elective" else if Text.Contains([course], "PHYSICS") then "Science" else if Text.Contains([course], "GEOGRAPHY") then "History" else if Text.Contains([course], "LAW") then "Elective" else if Text.Contains([course], "ANIME") then "Elective" else if Text.Contains([course], "STATS") then "Math" else if Text.Contains([course], "CALC ") then "Math" else if Text.Contains([course], "PSYCH ") then "Elective" else if Text.Contains([course], "FINANCIAL") then "Elective" else if Text.Contains([course], "ACT ") then "Elective" else if Text.Contains([course], "WORLD GEO") then "History" else if Text.Contains([course], "MYTHOLOGY") then "Elective" else if Text.Contains([course], "MAC ECON") then "Elective" else if Text.Contains([course], "WORKPLACE") then "Elective" else if Text.Contains([course], "CC-FASH") then "Elective" else if Text.Contains([course], "CREAT WRIT") then "Elective" else if Text.Contains([course], "SOCIOLOGY") then "Elective" else if Text.Contains([course], "CHEM ") then "Science" else if Text.Contains([course], "INTR HLTH") then "Elective" else if Text.Contains([course], "DRAMA") then "Elective" else if Text.Contains([course], "BARBER") then "Elective" else if Text.Contains([course], "FINANC LIT") then "Elective" else if Text.Contains([course], "ANIMATION") then "Elective" else if Text.Contains([course], "BUS COMP") then "Elective" else if Text.Contains([course], "CALCULUS") then "Math" else if Text.Contains([course], "NC CDF") then "Elective" else if Text.Contains([course], "VIR WP") then "Elective" else if Text.Contains([course], "MARKETING") then "Elective" else if Text.Contains([course], "FRENCH ") then "Elective" else if Text.Contains([course], "TECHNICAL") then "Elective" else if Text.Contains([course], "SOCIAL MEDIA") then "Elective" else if Text.Contains([course], "FILM") then "Elective" else if Text.Contains([course], "SCIEN") then "Science" else if Text.Contains([course], "GERMAN") then "Elective" else if Text.Contains([course], "COMP SCI") then "Elective" else if Text.Contains([course], "CC-") then "Elective" else if Text.Contains([course], "JROTC") then "Elective" else if Text.Contains([course], "WRLD HIS") then "History" else if Text.Contains([course], "PHILOS") then "Elective" else if Text.Contains([course], "DIG GRPX") then "Elective" else if Text.Contains([course], "TRANS:") then "Elective" else if Text.Contains([course], "PRIN OF") then "Elective" else if Text.Contains([course], "MULTI") then "Elective" else if Text.Contains([course], "ENTREPREN") then "Elective" else if Text.Contains([course], "TECH READ") then "Elective" else if Text.Contains([course], "VIRTUAL") then "Elective" else if Text.Contains([course], "VOCAL") then "Elective" else if Text.Contains([course], "ASL") then "Elective" else if Text.Contains([course], "HUMAN ANT") then "Elective" else if Text.Contains([course], "PERSONAL FINA") then "Elective" else if Text.Contains([course], "ENTRE") then "Elective" else if Text.Contains([course], "ENGI") then "ELA" else if Text.Contains([course], "ALGEBR") then "Math" else if Text.Contains([course], "CIVICS") then "Civics" else if Text.Contains([course], "USHIS") then "History" else if Text.Contains([course], "LATIN") then "Elective" else if Text.Contains([course], "ENV SCI") then "Science" else if Text.Contains([course], "US HIS") then "History" else if Text.Contains([course], "WEST CIVIL") then "History" else if Text.Contains([course], "ART") then "Elective" else ""),
  #"Filtered rows" = Table.SelectRows(#"Inserted conditional column", each ([course] <> "1ST ROBOTICS I" and [course] <> "21ST CEN IS&AN E" and [course] <> "ACADEMIC READINE" and [course] <> "ACCOUNTING I E" and [course] <> "ACT PREP" and [course] <> "ACT PREP E" and [course] <> "ACT PREP E S1" and [course] <> "ACT PREP H" and [course] <> "ACTPREP 4X4S" and [course] <> "AD NUTR&FOOD 1CR" and [course] <> "AD STRNG ORC4X4S" and [course] <> "ADAPTIVE PE" and [course] <> "ADVANCED BD II" and [course] <> "ADVANCED BD III" and [course] <> "AFR AMER STUD" and [course] <> "AFR AMER STUD E" and [course] <> "ALT HOME LIV SE6" and [course] <> "ALT HOME LIV SE7" and [course] <> "AM SIGN LNG II E" and [course] <> "AP MUSICTHEO4X4S" and [course] <> "BASEBALL IV" and [course] <> "BASKETBALL I F" and [course] <> "BASKETBALL I M" and [course] <> "BASKETBALL II M" and [course] <> "BASKETBALL III F" and [course] <> "BASKETBALL III M" and [course] <> "BASKETBALL IV F" and [course] <> "BEGIN BAND" and [course] <> "BEGIN. ORCHESTRA" and [course] <> "BROAD/JOURN 8 1S" and [course] <> "BROADCAST I H" and [course] <> "BROADCAST II" and [course] <> "BROADCAST II H" and [course] <> "BROADCASTING I" and [course] <> "BT-BARBER-II" and [course] <> "BT-COSMETOLOGY-2" and [course] <> "CIW INET BUS" and [course] <> "CIW INTERNET BUS" and [course] <> "CIW NETWORK TECH" and [course] <> "CIW WEB DEV 4X4S" and [course] <> "CIW WEB DEVELOP" and [course] <> "CMC LAB 6" and [course] <> "CMC LAB 7" and [course] <> "CMC LAB 8" and [course] <> "COND STRAT I G" and [course] <> "COND STRAT II B" and [course] <> "COND STRAT III B" and [course] <> "COND STRAT III G" and [course] <> "COND STRAT IV B" and [course] <> "COND STRATII4X4S" and [course] <> "COND STRATIV4X4S" and [course] <> "COND.STRATGIESI" and [course] <> "COOP MARK ED I" and [course] <> "COOP MRK ED I" and [course] <> "CUL OCC II (1)" and [course] <> "CULINARY ARTS I" and [course] <> "CYBER LIT (7TH)" and [course] <> "CYBER LIT (8TH)" and [course] <> "CYBER SCI 7 HS" and [course] <> "CYBER SCI 8 HS" and [course] <> "CYBERSECURITY E" and [course] <> "CYBERSOCNICERC" and [course] <> "CYBERSOCNICERC 8" and [course] <> "DANCE I" and [course] <> "DANCE IV" and [course] <> "DEBATE" and [course] <> "DEBATE I" and [course] <> "DEBATE II E" and [course] <> "DEBATE IV E" and [course] <> "DESKTOP PUBLISH" and [course] <> "DIG GRPX & ANIM" and [course] <> "DIGITAL MEDIA 1" and [course] <> "DIGITAL MEDIA II" and [course] <> "DIGITAL PHOTO" and [course] <> "DISCOVERIES 6")),
  Custom = #"Filtered rows",
  #"Inserted conditional column 1" = Table.AddColumn(Custom, "1st_9_GPA", each if Text.Contains([1st_9_weeks], "A") then 4 else if Text.Contains([1st_9_weeks], "B") then 3 else if Text.Contains([1st_9_weeks], "C") then 2 else if Text.Contains([1st_9_weeks], "D") then 1 else if Text.Contains([1st_9_weeks], "F") then 0 else if [1st_9_weeks] = "E" then 0 else ""),
  #"Reordered columns" = Table.ReorderColumns(#"Inserted conditional column 1", {"student_name", "sidno", "sasid", "grade", "gender", "dob", "school_name", "course", "1st_9_weeks", "1st_9_GPA", "2nd_9_weeks", "3rd_9_weeks", "4th_9_weeks", "iep_status", "504_status", "lep_status", "short_name_academics"}),
  #"Inserted conditional column 2" = Table.AddColumn(#"Reordered columns", "2nd_9_GPA", each if Text.Contains([2nd_9_weeks], "A") then 4 else if Text.Contains([2nd_9_weeks], "B") then 3 else if Text.Contains([2nd_9_weeks], "C") then 2 else if Text.Contains([2nd_9_weeks], "D") then 1 else if Text.Contains([2nd_9_weeks], "F") then 0 else if Text.Contains([2nd_9_weeks], "E") then 0 else ""),
  #"Reordered columns 1" = Table.ReorderColumns(#"Inserted conditional column 2", {"student_name", "sidno", "sasid", "grade", "gender", "dob", "school_name", "course", "1st_9_weeks", "1st_9_GPA", "2nd_9_weeks", "2nd_9_GPA", "3rd_9_weeks", "4th_9_weeks", "iep_status", "504_status", "lep_status", "short_name_academics"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Reordered columns 1", {{"1st_9_GPA", type number}, {"2nd_9_GPA", Int64.Type}}),
  #"Inserted conditional column 3" = Table.AddColumn(#"Changed column type", "3rd_9_gpa", each if Text.Contains([3rd_9_weeks], "A") then 4 else if Text.Contains([3rd_9_weeks], "B") then 3 else if Text.Contains([3rd_9_weeks], "C") then 2 else if Text.Contains([3rd_9_weeks], "D") then 1 else if Text.Contains([3rd_9_weeks], "F") then 0 else if [3rd_9_weeks] = "E" then 0 else ""),
  #"Reordered columns 2" = Table.ReorderColumns(#"Inserted conditional column 3", {"student_name", "sidno", "sasid", "grade", "gender", "dob", "school_name", "course", "1st_9_weeks", "1st_9_GPA", "2nd_9_weeks", "2nd_9_GPA", "3rd_9_weeks", "3rd_9_gpa", "4th_9_weeks", "iep_status", "504_status", "lep_status", "short_name_academics"}),
  #"Filtered rows 3" = Table.SelectRows(#"Reordered columns 2", each ([1st_9_GPA] <> null)),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Filtered rows 3", {{"short_name_academics", type text}, {"3rd_9_gpa", type number}, {"1st_9_GPA", type number}, {"2nd_9_GPA", type number}}),
  #"Inserted text before delimiter" = Table.AddColumn(#"Changed column type 1", "Text before delimiter", each Text.BeforeDelimiter([1st_9_weeks], " ", 0), type text),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Inserted text before delimiter", {{"Text before delimiter", type number}}),
  #"Reordered columns 3" = Table.ReorderColumns(#"Changed column type 2", {"student_name", "sidno", "sasid", "grade", "gender", "dob", "school_name", "course", "1st_9_weeks", "Text before delimiter", "1st_9_GPA", "2nd_9_weeks", "2nd_9_GPA", "3rd_9_weeks", "3rd_9_gpa", "4th_9_weeks", "iep_status", "504_status", "lep_status", "short_name_academics"}),
  #"Renamed columns" = Table.RenameColumns(#"Reordered columns 3", {{"Text before delimiter", "1st_9_grade_value"}}),
  #"Inserted text before delimiter 1" = Table.AddColumn(#"Renamed columns", "Text before delimiter", each Text.BeforeDelimiter([2nd_9_weeks], " ", 0), type text),
  #"Reordered columns 4" = Table.ReorderColumns(#"Inserted text before delimiter 1", {"student_name", "sidno", "sasid", "grade", "gender", "dob", "school_name", "course", "1st_9_weeks", "1st_9_grade_value", "1st_9_GPA", "2nd_9_weeks", "Text before delimiter", "2nd_9_GPA", "3rd_9_weeks", "3rd_9_gpa", "4th_9_weeks", "iep_status", "504_status", "lep_status", "short_name_academics"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Reordered columns 4", {{"Text before delimiter", "2nd_9_grade_value"}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Renamed columns 1", {{"2nd_9_grade_value", type number}}),
  #"Inserted text after delimiter" = Table.AddColumn(#"Changed column type 3", "Text after delimiter", each Text.AfterDelimiter([1st_9_weeks], " ", 0), type text),
  #"Reordered columns 5" = Table.ReorderColumns(#"Inserted text after delimiter", {"student_name", "sidno", "sasid", "grade", "gender", "dob", "school_name", "course", "1st_9_weeks", "Text after delimiter", "1st_9_grade_value", "1st_9_GPA", "2nd_9_weeks", "2nd_9_grade_value", "2nd_9_GPA", "3rd_9_weeks", "3rd_9_gpa", "4th_9_weeks", "iep_status", "504_status", "lep_status", "short_name_academics"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Reordered columns 5", {{"Text after delimiter", "1st_9_letter_grade"}}),
  #"Trimmed text" = Table.TransformColumns(#"Renamed columns 2", {{"1st_9_letter_grade", each Text.Trim(_), type text}}),
  #"Cleaned text" = Table.TransformColumns(#"Trimmed text", {{"1st_9_letter_grade", each Text.Clean(_), type text}})
in
  #"Cleaned text";
shared raw_caddo_grades_export_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "1b643108-97a2-432c-a0c0-391df26e0eea"]}[Data],
  TableNavigation = Navigation_2{[Id = "cleaned_caddo_grades", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
