CREATE TABLE [dbo].[raw_lighthouse_registration] (

	[Client ID] varchar(8000) NULL, 
	[Address] varchar(8000) NULL, 
	[Bus number:] varchar(8000) NULL, 
	[VOANLA - Zip Code] bigint NULL, 
	[Cell Phone] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[Does child ride the bus?] varchar(8000) NULL, 
	[Does your child receive behavioral health services?] varchar(8000) NULL, 
	[Education Release Effective for School Year:] varchar(8000) NULL, 
	[Education Release on file?] varchar(8000) NULL, 
	[Email Address] varchar(8000) NULL, 
	[Food Stamps] varchar(8000) NULL, 
	[Household Type] varchar(8000) NULL, 
	[If yes_ please list the provider] varchar(8000) NULL, 
	[Is student enrolled in CIS?] varchar(8000) NULL, 
	[JCAMPUS signed permission on file?] varchar(8000) NULL, 
	[JCAMPUS/School Loop Password:] varchar(8000) NULL, 
	[JCAMPUS/School Loop Username:] varchar(8000) NULL, 
	[Media Release Effective for School Year:] varchar(8000) NULL, 
	[Media Release on file?] varchar(8000) NULL, 
	[Name Of Teacher/Homeroom Teacher] varchar(8000) NULL, 
	[Program Contract Effective for School Year:] varchar(8000) NULL, 
	[Program Contract Signed and On File?] varchar(8000) NULL, 
	[School Year] varchar(8000) NULL, 
	[ServicePoint Release of Information on File?] varchar(8000) NULL, 
	[State] varchar(8000) NULL, 
	[Student ID#] varchar(8000) NULL, 
	[Summer Session] varchar(8000) NULL, 
	[Total number of Persons Living at the Address] bigint NULL, 
	[Allergy/Medical Condition?] varchar(8000) NULL, 
	[Application Date] date NULL, 
	[Contact #1 Name] varchar(8000) NULL, 
	[Contact #1 Phone] varchar(8000) NULL, 
	[Contact #2 Name] varchar(8000) NULL, 
	[Contact #2 Phone] varchar(8000) NULL, 
	[Clinic or Doctor's Name] varchar(8000) NULL, 
	[Doctor's Phone] varchar(8000) NULL, 
	[Does your child have an Individual Education Plan _IEP_?] varchar(8000) NULL, 
	[Drop-off location:] varchar(8000) NULL, 
	[If yes_ pickup location:] varchar(8000) NULL, 
	[Current Grade Level] varchar(8000) NULL, 
	[Has your child been placed in special education by the school system?] varchar(8000) NULL, 
	[Home Phone] varchar(8000) NULL, 
	[If yes_ please explain:] varchar(8000) NULL, 
	[If yes_ please list:] varchar(8000) NULL, 
	[Lighthouse Location Enrolling] varchar(8000) NULL, 
	[Medication at site during program hours?] varchar(8000) NULL, 
	[Parent/Guardian Name] varchar(8000) NULL, 
	[Place of Employment] varchar(8000) NULL, 
	[School District] varchar(8000) NULL, 
	[School Name] varchar(8000) NULL, 
	[School Phone Number] varchar(8000) NULL, 
	[Social Security] varchar(8000) NULL, 
	[SSI] varchar(8000) NULL, 
	[Total Annual Income] varchar(8000) NULL, 
	[Van Information] varchar(8000) NULL, 
	[Welfare _TANF_] varchar(8000) NULL, 
	[Does the child need to be picked up in a VOA van before Camp Glow?] varchar(8000) NULL, 
	[Relationship to Child] varchar(8000) NULL, 
	[WIOA?] varchar(8000) NULL, 
	[Will this provider want to visit during the program?] varchar(8000) NULL, 
	[Work Phone] varchar(8000) NULL
);