[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "raw-credible-services_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "service_id", DestinationColumnName = "service_id"], [SourceColumnName = "client_id", DestinationColumnName = "client_id"], [SourceColumnName = "employee_id", DestinationColumnName = "employee_id"], [SourceColumnName = "service_type", DestinationColumnName = "service_type"], [SourceColumnName = "service_status", DestinationColumnName = "service_status"], [SourceColumnName = "duration", DestinationColumnName = "duration"], [SourceColumnName = "client_first_name", DestinationColumnName = "client_first_name"], [SourceColumnName = "client_last_name", DestinationColumnName = "client_last_name"], [SourceColumnName = "emp_name", DestinationColumnName = "emp_name"], [SourceColumnName = "rate", DestinationColumnName = "rate"], [SourceColumnName = "units", DestinationColumnName = "units"], [SourceColumnName = "signature_datetime", DestinationColumnName = "signature_datetime"], [SourceColumnName = "appr_date", DestinationColumnName = "appr_date"], [SourceColumnName = "program_id", DestinationColumnName = "program_id"], [SourceColumnName = "non_billable", DestinationColumnName = "non_billable"], [SourceColumnName = "contract_rate", DestinationColumnName = "contract_rate"], [SourceColumnName = "ins_paid_amount", DestinationColumnName = "ins_paid_amount"], [SourceColumnName = "ins_due", DestinationColumnName = "ins_due"], [SourceColumnName = "is_late", DestinationColumnName = "is_late"], [SourceColumnName = "manual_update_to_modifier", DestinationColumnName = "manual_update_to_modifier"], [SourceColumnName = "auth_id", DestinationColumnName = "auth_id"], [SourceColumnName = "manual_redx", DestinationColumnName = "manual_redx"], [SourceColumnName = "manual_redx_note", DestinationColumnName = "manual_redx_note"], [SourceColumnName = "appr", DestinationColumnName = "appr"], [SourceColumnName = "cotherapist", DestinationColumnName = "cotherapist"], [SourceColumnName = "comb_primary", DestinationColumnName = "comb_primary"], [SourceColumnName = "comb_secondary", DestinationColumnName = "comb_secondary"], [SourceColumnName = "comb_units", DestinationColumnName = "comb_units"], [SourceColumnName = "comb_rate", DestinationColumnName = "comb_rate"], [SourceColumnName = "episode_id", DestinationColumnName = "episode_id"], [SourceColumnName = "delayed_reason_code", DestinationColumnName = "delayed_reason_code"], [SourceColumnName = "service_date", DestinationColumnName = "service_date"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared #"raw-credible-services" = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2rfRvTPNU2S5FtAXPwjqgHzA__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3=")),
  Navigation = Source{1}[Table],
  #"Expanded Table" = Table.ExpandTableColumn(Navigation, "Table", {"Name", "Table"}, {"Name.1", "Table.1"}),
  #"Expanded Table.1 1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}),
  #"Expanded Table 2" = Table.ExpandTableColumn(#"Expanded Table.1 1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}),
  #"Expanded Table.1 2" = Table.ExpandTableColumn(#"Expanded Table 2", "Table.1", {"clientvisit_id", "client_id", "emp_id", "visittype", "status", "duration", "clientfirstname", "clientlastname", "emp_name", "rate", "units_of_svc", "signature_datetime", "appr_date", "program_id", "non_billable", "contract_rate", "ins_paid_amount", "ins_due", "timeout", "is_late", "manual_update_to_modifier", "auth_id", "timein", "manual_redx", "manual_redx_note", "appr", "cotherapist", "comb_primary", "comb_secondary", "comb_units", "comb_rate", "episode_id", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "delayed_reason_code"}, {"clientvisit_id", "client_id", "emp_id", "visittype", "status", "duration", "clientfirstname", "clientlastname", "emp_name", "rate", "units_of_svc", "signature_datetime", "appr_date", "program_id", "non_billable", "contract_rate", "ins_paid_amount", "ins_due", "timeout", "is_late", "manual_update_to_modifier", "auth_id", "timein", "manual_redx", "manual_redx_note", "appr", "cotherapist", "comb_primary", "comb_secondary", "comb_units", "comb_rate", "episode_id", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "delayed_reason_code"}),
  #"Renamed columns" = Table.RenameColumns(#"Expanded Table.1 2", {{"clientvisit_id", "Service ID"}, {"client_id", "Client ID"}, {"emp_id", "Employee ID"}, {"visittype", "Service Type"}, {"status", "Status"}, {"duration", "Duration"}}),
  #"Changed column type 14" = Table.TransformColumnTypes(#"Renamed columns", {{"comb_units", type number}, {"comb_rate", type number}}),
  #"Renamed columns 1" = Table.RenameColumns(#"Changed column type 14", {{"units_of_svc", "Units"}}),
  
  // FIX: Clean up data types and handle nulls
  #"Remove Problem Columns" = Table.RemoveColumns(#"Renamed columns 1", {"urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}),
  #"Replace Nulls" = Table.ReplaceValue(#"Remove Problem Columns", null, "", Replacer.ReplaceValue, Table.ColumnNames(#"Remove Problem Columns")),
  #"Convert All Text" = Table.TransformColumnTypes(#"Replace Nulls", List.Transform(Table.ColumnNames(#"Replace Nulls"), each {_, type text})),
  #"Final Type Cleanup" = Table.TransformColumnTypes(#"Convert All Text", {
    {"Service ID", type text},
    {"Client ID", type text}, 
    {"Employee ID", type text},
    {"Service Type", type text},
    {"Duration", type number},
    {"Units", type number},
    {"rate", type number}
  }),
  #"Sorted rows" = Table.Sort(#"Final Type Cleanup", {{"rate", Order.Descending}}),
  #"Removed columns" = Table.RemoveColumns(#"Sorted rows", {"Name", "Name.1", "Name.2", "Name.3"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Removed columns", {{"Service ID", "service_id"}, {"Client ID", "client_id"}, {"Employee ID", "employee_id"}, {"Service Type", "service_type"}, {"Status", "service_status"}, {"Duration", "duration"}, {"clientfirstname", "client_first_name"}, {"clientlastname", "client_last_name"}, {"Units", "units"}}),
  #"Inserted text range" = Table.AddColumn(#"Renamed columns 2", "Text range", each Text.Middle([timein], 0, 10), type text),
  #"Changed column type" = Table.TransformColumnTypes(#"Inserted text range", {{"Text range", type date}}),
  #"Renamed columns 3" = Table.RenameColumns(#"Changed column type", {{"Text range", "service_date"}}),
  #"Sorted rows 1" = Table.Sort(#"Renamed columns 3", {{"service_date", Order.Ascending}}),
  #"Extracted text range" = Table.TransformColumns(#"Sorted rows 1", {{"signature_datetime", each Text.Middle(_, 0, 10), type text}}),
  #"Extracted text range 1" = Table.TransformColumns(#"Extracted text range", {{"appr_date", each Text.Middle(_, 0, 10), type text}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Extracted text range 1", {{"timein", type datetimezone}, {"signature_datetime", type date}, {"appr_date", type date}}),
  #"Extracted time" = Table.TransformColumns(#"Changed column type 1", {{"timein", each DateTime.Time(_), type nullable time}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Extracted time", {{"timeout", type datetimezone}}),
  #"Extracted time 1" = Table.TransformColumns(#"Changed column type 2", {{"timeout", each DateTime.Time(_), type nullable time}}),
  #"Sorted rows 2" = Table.Sort(#"Extracted time 1", {{"service_date", Order.Descending}})
in
  #"Sorted rows 2";
shared NavigationQuery = let
  Source = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation = Source{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  #"Navigation 1" = Navigation{[warehouseId = "e4d2de35-5f5d-457f-8e5b-43f758299057"]}[Data]
in
  #"Navigation 1";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "API - Outreach_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared #"API - Outreach" = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2r1OkQYY7dl3jpHEC3CGjVlQ__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3="), null, 65001),
  #"Navigation 1" = Source{1}[Table],
  #"Expanded Table" = Table.ExpandTableColumn(#"Navigation 1", "Table", {"Name", "Table"}, {"Name.1", "Table.1"}),
  #"Expanded Table.1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}),
  #"Expanded Table 1" = Table.ExpandTableColumn(#"Expanded Table.1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}),
  #"Expanded Table.1 1" = Table.ExpandTableColumn(#"Expanded Table 1", "Table.1", {"clientvisit_id", "font_colornavytarget_categoryf_559762_university_1012132", "i_select_universityi_559763", "font_colornavynumber_of_people_559765", "font_colornavymarketing_materi_559767_push_cards_1012189", "font_colornavybrief_summary_of_559770_notes", "font_colornavyfollowup_planned_559771", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "supported_education_or_employm_559749_education_1012105", "type_of_contact_559750", "was_the_client_present_559755", "name_of_contact_or_persons_pre_559753", "name_of_institutionschoolcolle_559754", "brief_description_of_contact_559756_notes", "are_there_any_notable_problems_559757", "progress_since_last_session_559758", "next_scheduled_checkin_559759", "ihomework_what_will_be_address_559761_notes", "are_there_any_notable_problems_559757_notes", "font_colornavytarget_categoryf_559762_community_organization_1012137", "font_colornavyname_of_outreach_559963", "font_colornavymarketing_materi_559767_fliers_1012188", "font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "font_colornavytarget_categoryf_559762_policeprison_1012135", "font_colornavytarget_categoryf_559762_public_school_1012131", "font_colorpurplenumber_of_flie_559768", "supported_education_or_employm_559749_employment_1012106", "font_colornavytarget_categoryf_559762_medical_professional_1012130", "font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "i_select_mental_health_profess_559764", "font_colorpurplenumber_of_push_559769", "location_of_contact_559751", "purpose_of_this_sed_service_559752_transition_planning_1012118", "purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "were_other_individuals_present_574585", "font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "purpose_of_this_sed_service_559752_identification_of_educational__1012114", "purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "bdescription_of_serviceb_585056", "bdescription_of_serviceb_585056_notes", "purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "location_of_contact_559751_notes", "purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "purpose_of_this_sed_service_559752_employment_skills_training_1035701", "purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "font_colornavyprograms_include_594438_epicenter_1066407", "font_colornavyother_voa_staff__594468", "font_colornavytype_of_contactf_594470_inperson_1066517", "font_colornavypersons_spoke_to_594469", "font_colornavyfollowup_planned_559771_notes", "font_colornavyprograms_include_594438_visions_of_hope_groups_1066409", "font_colornavymarketing_materi_559767_foodsnacks_1066748", "font_colorpurpletype_of_foodsn_594624"}, {"clientvisit_id", "font_colornavytarget_categoryf_559762_university_1012132", "i_select_universityi_559763", "font_colornavynumber_of_people_559765", "font_colornavymarketing_materi_559767_push_cards_1012189", "font_colornavybrief_summary_of_559770_notes", "font_colornavyfollowup_planned_559771", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "supported_education_or_employm_559749_education_1012105", "type_of_contact_559750", "was_the_client_present_559755", "name_of_contact_or_persons_pre_559753", "name_of_institutionschoolcolle_559754", "brief_description_of_contact_559756_notes", "are_there_any_notable_problems_559757", "progress_since_last_session_559758", "next_scheduled_checkin_559759", "ihomework_what_will_be_address_559761_notes", "are_there_any_notable_problems_559757_notes", "font_colornavytarget_categoryf_559762_community_organization_1012137", "font_colornavyname_of_outreach_559963", "font_colornavymarketing_materi_559767_fliers_1012188", "font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "font_colornavytarget_categoryf_559762_policeprison_1012135", "font_colornavytarget_categoryf_559762_public_school_1012131", "font_colorpurplenumber_of_flie_559768", "supported_education_or_employm_559749_employment_1012106", "font_colornavytarget_categoryf_559762_medical_professional_1012130", "font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "i_select_mental_health_profess_559764", "font_colorpurplenumber_of_push_559769", "location_of_contact_559751", "purpose_of_this_sed_service_559752_transition_planning_1012118", "purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "were_other_individuals_present_574585", "font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "purpose_of_this_sed_service_559752_identification_of_educational__1012114", "purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "bdescription_of_serviceb_585056", "bdescription_of_serviceb_585056_notes", "purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "location_of_contact_559751_notes", "purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "purpose_of_this_sed_service_559752_employment_skills_training_1035701", "purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "font_colornavyprograms_include_594438_epicenter_1066407", "font_colornavyother_voa_staff__594468", "font_colornavytype_of_contactf_594470_inperson_1066517", "font_colornavypersons_spoke_to_594469", "font_colornavyfollowup_planned_559771_notes", "font_colornavyprograms_include_594438_visions_of_hope_groups_1066409", "font_colornavymarketing_materi_559767_foodsnacks_1066748", "font_colorpurpletype_of_foodsn_594624"}),
  #"Removed columns" = Table.RemoveColumns(#"Expanded Table.1 1", {"Name.3", "Name.2", "Name.1", "Name", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"font_colornavynumber_of_people_559765", "num_of_people"}, {"font_colornavymarketing_materi_559767_push_cards_1012189", "push_cards"}, {"font_colornavybrief_summary_of_559770_notes", "summary"}, {"font_colornavyfollowup_planned_559771", "planned_followup"}, {"supported_education_or_employm_559749_education_1012105", "employment_or_education"}, {"type_of_contact_559750", "contact_type"}, {"was_the_client_present_559755", "client_present"}, {"name_of_contact_or_persons_pre_559753", "contact_name"}, {"name_of_institutionschoolcolle_559754", "school"}, {"brief_description_of_contact_559756_notes", "contact_notes"}, {"are_there_any_notable_problems_559757", "notable_problems"}, {"progress_since_last_session_559758", "progress_since_last"}, {"next_scheduled_checkin_559759", "next_checkin"}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed columns", {{"next_checkin", type date}}),
  #"Renamed columns 1" = Table.RenameColumns(#"Changed column type", {{"ihomework_what_will_be_address_559761_notes", "homework_notes"}, {"are_there_any_notable_problems_559757_notes", "school_problems"}, {"font_colornavytarget_categoryf_559762_community_organization_1012137", "community_organization"}, {"font_colornavyname_of_outreach_559963", "name_of_outreach"}, {"font_colornavymarketing_materi_559767_fliers_1012188", "fliers"}, {"font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "mental_health_professional"}, {"font_colorpurpletype_of_foodsn_594624", "food"}, {"font_colornavymarketing_materi_559767_foodsnacks_1066748", "food_snacks"}, {"font_colornavyprograms_include_594438_visions_of_hope_groups_1066409", "group"}, {"font_colornavyfollowup_planned_559771_notes", "planned_fu"}, {"font_colornavypersons_spoke_to_594469", "contact_name_1"}, {"font_colornavytype_of_contactf_594470_inperson_1066517", "inPerson_virtual"}, {"font_colornavyother_voa_staff__594468", "other_voa_staff"}, {"font_colornavyprograms_include_594438_epicenter_1066407", "epicenter"}, {"purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "id_of_resources"}, {"purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "link_to_resources"}, {"purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "link_to_ed_resources"}, {"purpose_of_this_sed_service_559752_employment_skills_training_1035701", "skills_training"}, {"purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "job_fair"}, {"location_of_contact_559751_notes", "location_notes"}, {"purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "time_management"}, {"purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "iep_consult"}, {"bdescription_of_serviceb_585056_notes", "desc_of_services"}, {"bdescription_of_serviceb_585056", "desc_of_serv_1"}, {"purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "completing_applications"}, {"purpose_of_this_sed_service_559752_identification_of_educational__1012114", "id_ed_goals"}, {"purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "parental_skills_building"}, {"purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "ind_living_skills"}, {"font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "social_human_provider"}, {"were_other_individuals_present_574585", "others_present"}, {"purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "coord_of_care"}, {"purpose_of_this_sed_service_559752_transition_planning_1012118", "transition_planning"}, {"location_of_contact_559751", "location_notes_2"}, {"font_colorpurplenumber_of_push_559769", "num_of_push_cards"}, {"i_select_mental_health_profess_559764", "mhp"}, {"font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "substance_use"}, {"font_colornavytarget_categoryf_559762_medical_professional_1012130", "medical_professional"}, {"supported_education_or_employm_559749_employment_1012106", "employment"}, {"font_colorpurplenumber_of_flie_559768", "num_of_fliers"}, {"font_colornavytarget_categoryf_559762_public_school_1012131", "public_school"}, {"font_colornavytarget_categoryf_559762_policeprison_1012135", "police_prison"}, {"font_colornavytarget_categoryf_559762_university_1012132", "university"}, {"clientvisit_id", "service_id"}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Renamed columns 1", {{"service_id", type text}, {"university", type text}}),
  #"Renamed columns 2" = Table.RenameColumns(#"Changed column type 1", {{"i_select_universityi_559763", "university_name"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns 2", {{"university_name", type text}, {"num_of_people", Int64.Type}, {"push_cards", type text}, {"summary", type text}, {"planned_followup", type text}, {"employment_or_education", type text}, {"contact_type", type text}, {"client_present", type text}, {"contact_name", type text}, {"school", type text}, {"contact_notes", type text}, {"notable_problems", type text}, {"progress_since_last", type text}, {"homework_notes", type text}, {"school_problems", type text}, {"community_organization", type text}, {"name_of_outreach", type text}, {"fliers", type text}, {"mental_health_professional", type text}, {"police_prison", type text}, {"public_school", type text}, {"num_of_fliers", type text}, {"employment", type text}, {"medical_professional", type text}, {"substance_use", type text}, {"mhp", type text}, {"num_of_push_cards", type text}, {"location_notes_2", type text}, {"transition_planning", type text}, {"coord_of_care", type text}, {"others_present", type text}, {"social_human_provider", type text}, {"food", type text}, {"food_snacks", type text}, {"group", type text}, {"planned_fu", type text}, {"contact_name_1", type text}, {"inPerson_virtual", type text}, {"other_voa_staff", type text}, {"epicenter", type text}, {"id_of_resources", type text}, {"link_to_resources", type text}, {"link_to_ed_resources", type text}, {"skills_training", type text}, {"job_fair", type text}, {"location_notes", type text}, {"time_management", type text}, {"iep_consult", type text}, {"desc_of_services", type text}, {"desc_of_serv_1", type text}, {"completing_applications", type text}, {"id_ed_goals", type text}, {"parental_skills_building", type text}, {"ind_living_skills", type text}}),
  #"Merged queries" = Table.NestedJoin(#"Changed column type 2", {"service_id"}, #"raw-credible-services", {"service_id"}, "raw-credible-services", JoinKind.LeftOuter),
  #"Expanded raw-credible-services" = Table.ExpandTableColumn(#"Merged queries", "raw-credible-services", {"duration", "service_date"}, {"duration", "service_date"})
in
  #"Expanded raw-credible-services";
shared #"API - Outreach_DataDestination" = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "74be8ffb-fa88-4278-9a30-358e88a4f13a"]}[Data],
  TableNavigation = Navigation_2{[Id = "raw_credible_outreach", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
shared RangeStart = #datetime(2020, 1, 1, 0, 0, 0) meta [IsParameterQuery = true, IsParameterQueryRequired = false, Type = type datetime];
shared RangeEnd = #datetime(2099, 12, 31, 23, 59, 59) meta [IsParameterQuery = true, IsParameterQueryRequired = false, Type = type datetime];
shared #"raw-credible-services_DataDestination" = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "74be8ffb-fa88-4278-9a30-358e88a4f13a"]}[Data],
  TableNavigation = Navigation_2{[Id = "raw_credible_services", ItemKind = "Table"]}[Data]
in
  TableNavigation;
