[StagingDefinition = [Kind = "FastCopy"]]
section Section1;

// ===== CONFIGURATION PARAMETERS =====
shared WorkspaceId = "4241c9c7-5818-4c56-9220-faf632741770" meta [Description = "Fabric workspace ID"];
shared LakehouseId = "74be8ffb-fa88-4278-9a30-358e88a4f13a" meta [Description = "Lakehouse ID"];
shared CredibleServicesApiUrl = "https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2rfRvTPNU2S5FtAXPwjqgHzA__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3=" meta [Description = "Credible Services API endpoint"];
shared CredibleOutreachApiUrl = "https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2r1OkQYY7dl3jpHEC3CGjVlQ__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3=" meta [Description = "Credible Outreach API endpoint"];

// ===== DATA QUERIES =====

[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "raw-credible-services_DataDestination", IsNewTarget = false], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared #"raw-credible-services" = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2rfRvTPNU2S5FtAXPwjqgHzA__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3=")),
  Navigation = Source{1}[Table], // Navigate to main data table in XML
  #"Expanded Table" = Table.ExpandTableColumn(Navigation, "Table", {"Name", "Table"}, {"Name.1", "Table.1"}), // Expand first level of nested XML tables
  #"Expanded Table.1 1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}), // Expand second level of nested XML tables
  #"Expanded Table 2" = Table.ExpandTableColumn(#"Expanded Table.1 1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}), // Expand third level of nested XML tables
  #"Expanded Table.1 2" = Table.ExpandTableColumn(#"Expanded Table 2", "Table.1", {"clientvisit_id", "client_id", "emp_id", "visittype", "status", "duration", "clientfirstname", "clientlastname", "emp_name", "rate", "units_of_svc", "signature_datetime", "appr_date", "program_id", "non_billable", "contract_rate", "ins_paid_amount", "ins_due", "timeout", "is_late", "manual_update_to_modifier", "auth_id", "timein", "manual_redx", "manual_redx_note", "appr", "cotherapist", "comb_primary", "comb_secondary", "comb_units", "comb_rate", "episode_id", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "delayed_reason_code"}, {"clientvisit_id", "client_id", "emp_id", "visittype", "status", "duration", "clientfirstname", "clientlastname", "emp_name", "rate", "units_of_svc", "signature_datetime", "appr_date", "program_id", "non_billable", "contract_rate", "ins_paid_amount", "ins_due", "timeout", "is_late", "manual_update_to_modifier", "auth_id", "timein", "manual_redx", "manual_redx_note", "appr", "cotherapist", "comb_primary", "comb_secondary", "comb_units", "comb_rate", "episode_id", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "delayed_reason_code"}), // Expand service data columns from XML
  #"Removed columns" = Table.RemoveColumns(#"Expanded Table.1 2", {"Name", "Name.1", "Name.2", "Name.3", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}), // Remove XML navigation and schema metadata columns
  #"Changed column type" = Table.TransformColumnTypes(#"Removed columns", {{"clientvisit_id", type text}, {"client_id", type text}, {"emp_id", type text}, {"visittype", type text}, {"status", type text}, {"duration", type number}, {"clientfirstname", type text}, {"clientlastname", type text}, {"emp_name", type text}, {"rate", type number}, {"units_of_svc", type number}, {"program_id", type text}, {"non_billable", type text}, {"contract_rate", type number}, {"ins_paid_amount", type number}, {"ins_due", type number}, {"is_late", type text}, {"manual_update_to_modifier", type text}, {"auth_id", type text}, {"manual_redx", type text}, {"manual_redx_note", type text}, {"appr", type text}, {"cotherapist", type text}, {"comb_primary", type text}, {"comb_secondary", type text}, {"comb_units", type number}, {"comb_rate", type number}, {"episode_id", type text}, {"delayed_reason_code", type text}}), // Set proper data types for all service fields
  #"Extracted text range" = Table.TransformColumns(#"Changed column type", {{"signature_datetime", each Text.Middle(_, 0, 10), type text}}), // Extract date from signature timestamp
  #"Changed column type 1" = Table.TransformColumnTypes(#"Extracted text range", {{"signature_datetime", type date}}), // Convert signature_datetime to date type
  #"Extracted text range 1" = Table.TransformColumns(#"Changed column type 1", {{"appr_date", each Text.Middle(_, 0, 10), type text}}), // Extract date from approval timestamp
  #"Changed column type 2" = Table.TransformColumnTypes(#"Extracted text range 1", {{"appr_date", type date}}), // Convert appr_date to date type
  #"Changed column type 3" = Table.TransformColumnTypes(#"Changed column type 2", {{"timein", type datetimezone}}), // Convert timein to datetimezone
  #"Extracted time" = Table.TransformColumns(#"Changed column type 3", {{"timein", each DateTime.Time(_), type nullable time}}), // Extract time portion from timein
  #"Inserted text range" = Table.AddColumn(#"Extracted time", "service_date", each Text.Middle([timein], 0, 10), type text), // Extract service date from timein timestamp
  #"Changed column type 4" = Table.TransformColumnTypes(#"Inserted text range", {{"service_date", type date}}), // Convert service_date to date type
  #"Changed column type 5" = Table.TransformColumnTypes(#"Changed column type 4", {{"timeout", type datetimezone}}), // Convert timeout to datetimezone
  #"Extracted time 1" = Table.TransformColumns(#"Changed column type 5", {{"timeout", each DateTime.Time(_), type nullable time}}), // Extract time portion from timeout
  #"Renamed columns" = Table.RenameColumns(#"Extracted time 1", {{"clientvisit_id", "service_id"}, {"client_id", "client_id"}, {"emp_id", "employee_id"}, {"visittype", "service_type"}, {"status", "service_status"}, {"duration", "duration"}, {"clientfirstname", "first_name"}, {"clientlastname", "last_name"}, {"emp_name", "emp_name"}, {"rate", "rate"}, {"units_of_svc", "units"}, {"signature_datetime", "signature_datetime"}, {"appr_date", "appr_date"}, {"program_id", "program_id"}, {"non_billable", "non_billable"}, {"contract_rate", "contract_rate"}, {"ins_paid_amount", "ins_paid_amount"}, {"ins_due", "ins_due"}, {"is_late", "is_late"}, {"manual_update_to_modifier", "manual_update_to_modifier"}, {"auth_id", "auth_id"}, {"manual_redx", "manual_redx"}, {"manual_redx_note", "manual_redx_note"}, {"appr", "appr"}, {"cotherapist", "cotherapist"}, {"comb_primary", "comb_primary"}, {"comb_secondary", "comb_secondary"}, {"comb_units", "comb_units"}, {"comb_rate", "comb_rate"}, {"episode_id", "episode_id"}, {"delayed_reason_code", "delayed_reason_code"}}), // Rename columns to standard field names
  #"Sorted rows" = Table.Sort(#"Renamed columns", {{"service_date", Order.Descending}}) // Sort by service date, most recent first
in
  #"Sorted rows";

[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "API - Outreach_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared #"API - Outreach" = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2r1OkQYY7dl3jpHEC3CGjVlQ__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3="), null, 65001),
  #"Navigation 1" = Source{1}[Table], // Navigate to main data table in XML
  #"Expanded Table" = Table.ExpandTableColumn(#"Navigation 1", "Table", {"Name", "Table"}, {"Name.1", "Table.1"}), // Expand first level of nested XML tables
  #"Expanded Table.1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}), // Expand second level of nested XML tables
  #"Expanded Table 1" = Table.ExpandTableColumn(#"Expanded Table.1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}), // Expand third level of nested XML tables
  #"Expanded Table.1 1" = Table.ExpandTableColumn(#"Expanded Table 1", "Table.1", {"clientvisit_id", "font_colornavytarget_categoryf_559762_university_1012132", "i_select_universityi_559763", "font_colornavynumber_of_people_559765", "font_colornavymarketing_materi_559767_push_cards_1012189", "font_colornavybrief_summary_of_559770_notes", "font_colornavyfollowup_planned_559771", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "supported_education_or_employm_559749_education_1012105", "type_of_contact_559750", "was_the_client_present_559755", "name_of_contact_or_persons_pre_559753", "name_of_institutionschoolcolle_559754", "brief_description_of_contact_559756_notes", "are_there_any_notable_problems_559757", "progress_since_last_session_559758", "next_scheduled_checkin_559759", "ihomework_what_will_be_address_559761_notes", "are_there_any_notable_problems_559757_notes", "font_colornavytarget_categoryf_559762_community_organization_1012137", "font_colornavyname_of_outreach_559963", "font_colornavymarketing_materi_559767_fliers_1012188", "font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "font_colornavytarget_categoryf_559762_policeprison_1012135", "font_colornavytarget_categoryf_559762_public_school_1012131", "font_colorpurplenumber_of_flie_559768", "supported_education_or_employm_559749_employment_1012106", "font_colornavytarget_categoryf_559762_medical_professional_1012130", "font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "i_select_mental_health_profess_559764", "font_colorpurplenumber_of_push_559769", "location_of_contact_559751", "purpose_of_this_sed_service_559752_transition_planning_1012118", "purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "were_other_individuals_present_574585", "font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "purpose_of_this_sed_service_559752_identification_of_educational__1012114", "purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "bdescription_of_serviceb_585056", "bdescription_of_serviceb_585056_notes", "purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "location_of_contact_559751_notes", "purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "purpose_of_this_sed_service_559752_employment_skills_training_1035701", "purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "font_colornavyprograms_include_594438_epicenter_1066407", "font_colornavyother_voa_staff__594468", "font_colornavytype_of_contactf_594470_inperson_1066517", "font_colornavypersons_spoke_to_594469", "font_colornavyfollowup_planned_559771_notes", "font_colornavyprograms_include_594438_visions_of_hope_groups_1066409", "font_colornavymarketing_materi_559767_foodsnacks_1066748", "font_colorpurpletype_of_foodsn_594624"}, {"clientvisit_id", "font_colornavytarget_categoryf_559762_university_1012132", "i_select_universityi_559763", "font_colornavynumber_of_people_559765", "font_colornavymarketing_materi_559767_push_cards_1012189", "font_colornavybrief_summary_of_559770_notes", "font_colornavyfollowup_planned_559771", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "supported_education_or_employm_559749_education_1012105", "type_of_contact_559750", "was_the_client_present_559755", "name_of_contact_or_persons_pre_559753", "name_of_institutionschoolcolle_559754", "brief_description_of_contact_559756_notes", "are_there_any_notable_problems_559757", "progress_since_last_session_559758", "next_scheduled_checkin_559759", "ihomework_what_will_be_address_559761_notes", "are_there_any_notable_problems_559757_notes", "font_colornavytarget_categoryf_559762_community_organization_1012137", "font_colornavyname_of_outreach_559963", "font_colornavymarketing_materi_559767_fliers_1012188", "font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "font_colornavytarget_categoryf_559762_policeprison_1012135", "font_colornavytarget_categoryf_559762_public_school_1012131", "font_colorpurplenumber_of_flie_559768", "supported_education_or_employm_559749_employment_1012106", "font_colornavytarget_categoryf_559762_medical_professional_1012130", "font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "i_select_mental_health_profess_559764", "font_colorpurplenumber_of_push_559769", "location_of_contact_559751", "purpose_of_this_sed_service_559752_transition_planning_1012118", "purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "were_other_individuals_present_574585", "font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "purpose_of_this_sed_service_559752_identification_of_educational__1012114", "purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "bdescription_of_serviceb_585056", "bdescription_of_serviceb_585056_notes", "purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "location_of_contact_559751_notes", "purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "purpose_of_this_sed_service_559752_employment_skills_training_1035701", "purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "font_colornavyprograms_include_594438_epicenter_1066407", "font_colornavyother_voa_staff__594468", "font_colornavytype_of_contactf_594470_inperson_1066517", "font_colornavypersons_spoke_to_594469", "font_colornavyfollowup_planned_559771_notes", "font_colornavyprograms_include_594438_visions_of_hope_groups_1066409", "font_colornavymarketing_materi_559767_foodsnacks_1066748", "font_colorpurpletype_of_foodsn_594624"}), // Expand all outreach tracking fields from XML
  #"Removed columns" = Table.RemoveColumns(#"Expanded Table.1 1", {"Name.3", "Name.2", "Name.1", "Name", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}), // Remove XML navigation and schema metadata columns
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"font_colornavynumber_of_people_559765", "num_of_people"}, {"font_colornavymarketing_materi_559767_push_cards_1012189", "push_cards"}, {"font_colornavybrief_summary_of_559770_notes", "summary"}, {"font_colornavyfollowup_planned_559771", "planned_followup"}, {"supported_education_or_employm_559749_education_1012105", "employment_or_education"}, {"type_of_contact_559750", "contact_type"}, {"was_the_client_present_559755", "client_present"}, {"name_of_contact_or_persons_pre_559753", "contact_name"}, {"name_of_institutionschoolcolle_559754", "school"}, {"brief_description_of_contact_559756_notes", "contact_notes"}, {"are_there_any_notable_problems_559757", "notable_problems"}, {"progress_since_last_session_559758", "progress_since_last"}, {"next_scheduled_checkin_559759", "next_checkin"}}), // Rename first batch of outreach fields to readable names
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed columns", {{"next_checkin", type date}}), // Convert next_checkin to date type
  #"Renamed columns 1" = Table.RenameColumns(#"Changed column type", {{"ihomework_what_will_be_address_559761_notes", "homework_notes"}, {"are_there_any_notable_problems_559757_notes", "school_problems"}, {"font_colornavytarget_categoryf_559762_community_organization_1012137", "community_organization"}, {"font_colornavyname_of_outreach_559963", "name_of_outreach"}, {"font_colornavymarketing_materi_559767_fliers_1012188", "fliers"}, {"font_colornavytarget_categoryf_559762_mental_health_professional_1012134", "mental_health_professional"}, {"font_colorpurpletype_of_foodsn_594624", "food"}, {"font_colornavymarketing_materi_559767_foodsnacks_1066748", "food_snacks"}, {"font_colornavyprograms_include_594438_visions_of_hope_groups_1066409", "group"}, {"font_colornavyfollowup_planned_559771_notes", "planned_fu"}, {"font_colornavypersons_spoke_to_594469", "contact_name_1"}, {"font_colornavytype_of_contactf_594470_inperson_1066517", "inPerson_virtual"}, {"font_colornavyother_voa_staff__594468", "other_voa_staff"}, {"font_colornavyprograms_include_594438_epicenter_1066407", "epicenter"}, {"purpose_of_this_sed_service_559752_identification_of_sources_of_f_1012115", "id_of_resources"}, {"purpose_of_this_sed_service_559752_linkage_to_community_resources_1035702", "link_to_resources"}, {"purpose_of_this_sed_service_559752_linkage_to_resources_for_educa_1035703", "link_to_ed_resources"}, {"purpose_of_this_sed_service_559752_employment_skills_training_1035701", "skills_training"}, {"purpose_of_this_sed_service_559752_job_faircommunity_event_1035700", "job_fair"}, {"location_of_contact_559751_notes", "location_notes"}, {"purpose_of_this_sed_service_559752_timeorganization_management_sk_1012117", "time_management"}, {"purpose_of_this_sed_service_559752_iep54_meetingconsultation_1035697", "iep_consult"}, {"bdescription_of_serviceb_585056_notes", "desc_of_services"}, {"bdescription_of_serviceb_585056", "desc_of_serv_1"}, {"purpose_of_this_sed_service_559752_completing_applications_andor__1012116", "completing_applications"}, {"purpose_of_this_sed_service_559752_identification_of_educational__1012114", "id_ed_goals"}, {"purpose_of_this_sed_service_559752_parental_supportskills_buildin_1035699", "parental_skills_building"}, {"purpose_of_this_sed_service_559752_independent_living_skills_trai_1035705", "ind_living_skills"}, {"font_colornavytarget_categoryf_559762_socialhuman_service_provider_1012139", "social_human_provider"}, {"were_other_individuals_present_574585", "others_present"}, {"purpose_of_this_sed_service_559752_coordination_of_care_with_scho_1035698", "coord_of_care"}, {"purpose_of_this_sed_service_559752_transition_planning_1012118", "transition_planning"}, {"location_of_contact_559751", "location_notes_2"}, {"font_colorpurplenumber_of_push_559769", "num_of_push_cards"}, {"i_select_mental_health_profess_559764", "mhp"}, {"font_colornavytarget_categoryf_559762_substance_abuse_counselorcente_1012136", "substance_use"}, {"font_colornavytarget_categoryf_559762_medical_professional_1012130", "medical_professional"}, {"supported_education_or_employm_559749_employment_1012106", "employment"}, {"font_colorpurplenumber_of_flie_559768", "num_of_fliers"}, {"font_colornavytarget_categoryf_559762_public_school_1012131", "public_school"}, {"font_colornavytarget_categoryf_559762_policeprison_1012135", "police_prison"}, {"font_colornavytarget_categoryf_559762_university_1012132", "university"}, {"clientvisit_id", "service_id"}}), // Rename second batch of outreach fields (contact targets, service purposes, materials distributed)
  #"Changed column type 1" = Table.TransformColumnTypes(#"Renamed columns 1", {{"service_id", type text}, {"university", type text}}), // Convert service_id and university to text types
  #"Renamed columns 2" = Table.RenameColumns(#"Changed column type 1", {{"i_select_universityi_559763", "university_name"}}), // Rename university name field
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns 2", {{"university_name", type text}, {"num_of_people", Int64.Type}, {"push_cards", type text}, {"summary", type text}, {"planned_followup", type text}, {"employment_or_education", type text}, {"contact_type", type text}, {"client_present", type text}, {"contact_name", type text}, {"school", type text}, {"contact_notes", type text}, {"notable_problems", type text}, {"progress_since_last", type text}, {"homework_notes", type text}, {"school_problems", type text}, {"community_organization", type text}, {"name_of_outreach", type text}, {"fliers", type text}, {"mental_health_professional", type text}, {"police_prison", type text}, {"public_school", type text}, {"num_of_fliers", type text}, {"employment", type text}, {"medical_professional", type text}, {"substance_use", type text}, {"mhp", type text}, {"num_of_push_cards", type text}, {"location_notes_2", type text}, {"transition_planning", type text}, {"coord_of_care", type text}, {"others_present", type text}, {"social_human_provider", type text}, {"food", type text}, {"food_snacks", type text}, {"group", type text}, {"planned_fu", type text}, {"contact_name_1", type text}, {"inPerson_virtual", type text}, {"other_voa_staff", type text}, {"epicenter", type text}, {"id_of_resources", type text}, {"link_to_resources", type text}, {"link_to_ed_resources", type text}, {"skills_training", type text}, {"job_fair", type text}, {"location_notes", type text}, {"time_management", type text}, {"iep_consult", type text}, {"desc_of_services", type text}, {"desc_of_serv_1", type text}, {"completing_applications", type text}, {"id_ed_goals", type text}, {"parental_skills_building", type text}, {"ind_living_skills", type text}}), // Set proper data types for all outreach fields
  #"Merged queries" = Table.NestedJoin(#"Changed column type 2", {"service_id"}, #"raw-credible-services", {"service_id"}, "raw-credible-services", JoinKind.LeftOuter), // Join outreach data with base service data on service_id
  #"Expanded raw-credible-services" = Table.ExpandTableColumn(#"Merged queries", "raw-credible-services", {"duration", "service_date"}, {"duration", "service_date"}) // Add duration and service_date from base service table
in
  #"Expanded raw-credible-services";
shared #"API - Outreach_DataDestination" = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "74be8ffb-fa88-4278-9a30-358e88a4f13a"]}[Data],
  TableNavigation = Navigation_2{[Id = "raw_credible_outreach", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;

shared #"raw-credible-services_DataDestination" = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "74be8ffb-fa88-4278-9a30-358e88a4f13a"]}[Data],
  TableNavigation = Navigation_2{[Id = "raw_credible_services", ItemKind = "Table"]}[Data]
in
  TableNavigation;
