[DefaultOutputDestinationSettings = [DestinationDefinition = [Kind = "Reference", QueryName = "DefaultDestination", IsNewTarget = true], UpdateMethod = [Kind = "Append"], DestinationTypeSettings = [Kind = "Table"]], StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "raw-credible-brs_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "clientvisit_id", DestinationColumnName = "clientvisit_id"], [SourceColumnName = "max_timein", DestinationColumnName = "max_timein"], [SourceColumnName = "max_client_id", DestinationColumnName = "max_client_id"], [SourceColumnName = "max_cptcode", DestinationColumnName = "max_cptcode"], [SourceColumnName = "max_program_desc", DestinationColumnName = "max_program_desc"], [SourceColumnName = "max_status", DestinationColumnName = "max_status"], [SourceColumnName = "avg_rate", DestinationColumnName = "avg_rate"], [SourceColumnName = "max_balance", DestinationColumnName = "max_balance"], [SourceColumnName = "max_billing_review_status_id", DestinationColumnName = "max_billing_review_status_id"], [SourceColumnName = "max_lookup_desc", DestinationColumnName = "max_lookup_desc"], [SourceColumnName = "max_payer_description", DestinationColumnName = "max_payer_description"], [SourceColumnName = "max_emp_name", DestinationColumnName = "max_emp_name"], [SourceColumnName = "max_visittype", DestinationColumnName = "max_visittype"], [SourceColumnName = "sign_date", DestinationColumnName = "sign_date"], [SourceColumnName = "max_last_name", DestinationColumnName = "max_last_name"], [SourceColumnName = "max_first_name", DestinationColumnName = "max_first_name"], [SourceColumnName = "max_visittype_id", DestinationColumnName = "max_visittype_id"], [SourceColumnName = "icn", DestinationColumnName = "icn"], [SourceColumnName = "max_action_date", DestinationColumnName = "max_action_date"], [SourceColumnName = "max_claim_id", DestinationColumnName = "max_claim_id"], [SourceColumnName = "adjustment_group_code", DestinationColumnName = "adjustment_group_code"], [SourceColumnName = "adjustment_reason_code", DestinationColumnName = "adjustment_reason_code"], [SourceColumnName = "max_description", DestinationColumnName = "max_description"], [SourceColumnName = "adjustmenttype_id", DestinationColumnName = "adjustmenttype_id"], [SourceColumnName = "max_notes", DestinationColumnName = "max_notes"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared #"raw-credible-brs" = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2r309sURypsXrRtrWKpewbmQ__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3=")),
  #"Navigation 1" = Source{1}[Table],
  #"Expanded Table" = Table.ExpandTableColumn(#"Navigation 1", "Table", {"Name", "Table"}, {"Name.1", "Table.1"}),
  #"Expanded Table.1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}),
  #"Expanded Table 2" = Table.ExpandTableColumn(#"Expanded Table.1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}),
  #"Expanded Table.1 1" = Table.ExpandTableColumn(#"Expanded Table 2", "Table.1", {"clientvisit_id", "max_timein", "max_client_id", "max_cptcode", "max_program_desc", "max_status", "avg_rate", "max_balance", "max_billing_review_status_id", "max_lookup_desc", "max_payer_description", "max_emp_name", "max_visittype", "sign_date", "max_last_name", "max_first_name", "max_visittype_id", "icn", "max_action_date", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "max_claim_id", "adjustment_group_code", "adjustment_reason_code", "max_description", "adjustmenttype_id", "max_notes"}, {"clientvisit_id", "max_timein", "max_client_id", "max_cptcode", "max_program_desc", "max_status", "avg_rate", "max_balance", "max_billing_review_status_id", "max_lookup_desc", "max_payer_description", "max_emp_name", "max_visittype", "sign_date", "max_last_name", "max_first_name", "max_visittype_id", "icn", "max_action_date", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "max_claim_id", "adjustment_group_code", "adjustment_reason_code", "max_description", "adjustmenttype_id", "max_notes"}),
  #"Removed columns" = Table.RemoveColumns(#"Expanded Table.1 1", {"Name", "Name.1", "Name.2", "Name.3", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Removed columns", {"sign_date", type datetime}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type",  {"sign_date", type date}),
  #"Extracted text before delimiter" = Table.TransformColumns(#"Changed column type 1", {{"max_action_date", each Text.BeforeDelimiter(Text.From(_), "T", 0), type text}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Extracted text before delimiter", {{"max_action_date", type date}, {"clientvisit_id", type text}, {"max_timein", type text}, {"max_client_id", type text}, {"max_cptcode", type text}, {"max_program_desc", type text}, {"max_status", type text}, {"max_billing_review_status_id", type text}, {"max_lookup_desc", type text}, {"max_payer_description", type text}, {"max_emp_name", type text}, {"max_visittype", type text}, {"max_last_name", type text}, {"max_first_name", type text}, {"max_visittype_id", type text}, {"icn", type text}, {"max_claim_id", type text}, {"adjustment_group_code", type text}, {"adjustment_reason_code", type text}, {"max_description", type text}, {"adjustmenttype_id", type text}, {"max_notes", type text}, {"avg_rate", type number}, {"max_balance", type number}})
in
  #"Changed column type 2";
shared DefaultDestination = Fabric.Warehouse([CreateNavigationProperties = false]){[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data]{[warehouseId = "e4d2de35-5f5d-457f-8e5b-43f758299057"]}[Data];
shared #"raw-credible-brs_DataDestination" = let
  Pattern = Fabric.Warehouse([HierarchicalNavigation = null, CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "e4d2de35-5f5d-457f-8e5b-43f758299057"]}[Data],
  TableNavigation = Navigation_2{[Item = "raw-credible-brs-v2", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
