table raw_sp_services
	lineageTag: a6f7ac95-d883-45f7-93ce-4b89c2700aaf

	column client_id
		dataType: string
		lineageTag: c2b0cbd7-d5d2-4233-bdb1-81a3226631b2
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column 1st_9_count
		dataType: int64
		formatString: 0
		lineageTag: f4e364e1-c8a5-4974-bc6f-b7a4ed71d140
		summarizeBy: sum
		sourceColumn: 1st_9_count

		annotation SummarizationSetBy = Automatic

	partition raw_sp_services = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "ServicePoint"),
				    dbo_raw_sp_services = Source{[Schema="dbo",Item="raw_sp_services"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_raw_sp_services, each [service_date] >= #date(2025, 9, 1) and [service_date] <= #date(2025, 10, 31)),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"client_id"}, {{"Count", each Table.RowCount(Table.Distinct(_)), Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Grouped Rows",{{"Count", "1st_9_count"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

