[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "caddo_tests_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared caddo_tests = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "1b643108-97a2-432c-a0c0-391df26e0eea"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "Files", ItemKind = "Folder"]}[Data],
  #"Navigation 3" = #"Navigation 2"{[Name = "JCAMPUS"]}[Content],
  #"Navigation 4" = #"Navigation 3"{[Name = "caddo_tests"]}[Content],
  #"Drill down" = #"Navigation 4"{0}[Content],
  #"Imported Excel workbook" = Excel.Workbook(#"Drill down", null, true),
  #"Expanded Data" = Table.ExpandTableColumn(#"Imported Excel workbook", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121"}),
  #"Promoted headers" = Table.PromoteHeaders(#"Expanded Data", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"School", Int64.Type}, {"Student Name", type text}, {"SASID", Int64.Type}, {"SIDNO", Int64.Type}, {"Grade", type text}, {"Sex", type text}, {"Ethnic", Int64.Type}, {"Homeroom", type text}, {"Sped", type text}, {"504", Int64.Type}, {"ELL", type text}, {"Cumulative GPA", Int64.Type}, {"Passed <BR> Requirements", type text}, {"Dual <BR> Enrollment", Int64.Type}, {"Honor <BR> Courses", Int64.Type}, {"LEAP 2025 Grade 3-8 Test Date", type date}, {"ELA               ", type text}, {"Math               ", type text}, {"Science               ", type text}, {"Social Studies               ", type text}, {"Civics               ", type text}, {"ELA               ", type text}, {"Math               ", type text}, {"Science               ", type text}, {"Social Studies               ", type text}, {"Civics               ", type text}, {"WK 2.0 - Overall", type text}, {"MOY", type text}, {"ELPT", type text}, {"Total Hours", Int64.Type}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"grStudentAccountabilitytracker_"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"School", "school_id"}, {"Student Name", "student_name"}, {"SASID", "sasid"}, {"SIDNO", "sidno"}, {"Grade", "grade"}, {"Sex", "gender"}, {"Ethnic", "ethnicity"}, {"Student Email", "student_email"}, {"Homeroom", "homeroom"}, {"Cohort Year", "cohort_year"}, {"FAFSA", "fafsa"}, {"Sped", "sped"}, {"ELL", "ell"}, {"ACT 833 (April Dunn Act)", "act_833"}, {"Cumulative GPA", "cum_gpa"}, {"Graduation Pathway", "graduation_pathway"}, {"Passed <BR> Requirements", "passed_requirements"}, {"Diploma Endorsements", "diploma_endorsements"}, {"Dual <BR> Enrollment", "dual_enrollment"}, {"Honor <BR> Courses", "honor_courses"}, {"Career Options", "career_options"}, {"IBC", "ibc"}, {"EOC Test Date", "eoc_test_date"}, {"ALG I", "alg_1"}, {"GEO", "geo"}, {"ENG II", "english_2"}, {"ENG III", "english_3"}, {"BIO", "bio"}, {"AM HIS", "am_his"}, {"Algebra I", "algebra_1"}, {"Geometry", "geometry"}, {"English II", "english_ii"}, {"English III", "english_iii"}, {"Biology", "biology"}, {"American History", "american_history"}, {"LEAP 2025 Test Date", "leap_2025_test_date"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns", {"ALG I             ", "GEO             ", "ENG I             ", "ENG II             ", "BIO             ", "AM HIS             ", "Civics             ", "Algebra I             ", "Geometry             ", "English I             ", "English II             ", "Biology             ", "American History             ", "Civics              "}),
  #"Renamed columns 1" = Table.RenameColumns(#"Removed columns 1", {{"Math Pair Flag Passed Requirement", "math_pair_passed"}, {"English Pair Flag Passed Requirement", "english_pair_passed"}, {"History-Science Pair Flag Passed Requirement", "historyScience_pair_passed"}, {"Civics-Science Pair Flag Passed Requirement ", "civicsScience_pair_passed"}, {"LEAP 2025 Grade 3-8 Test Date", "leap_2025_3rdto8th_test_date"}, {"ELA               ", "ela"}, {"Math               ", "math"}, {"Science               ", "science"}, {"Social Studies               ", "social_studies"}, {"Civics               ", "civics"}, {"ELA               ", "ela1"}, {"BOY", "literacy_boy"}, {"MOY", "literacy_moy"}, {"EOY", "literacy_eoy"}, {"ELPT", "elpt"}, {"Clep Score", "clep_score"}, {"AP", "ap"}, {"AP Test Score", "ap_test_score"}, {"AP Exam Name", "ap_exam_name"}, {"Community Service Hrs", "community_service_hours"}, {"Total Hours", "total_hours"}, {"TSS E", "tss_e"}, {"TSS M", "tss_m"}, {"TSS R", "tss_r"}, {"TSS S", "tss_s"}, {"TSS C", "tss_c"}, {"TSS STEM", "tss_stem"}, {"SRS PW", "srs_pw"}, {"SRS KL", "srs_kl"}, {"SRS CSE", "srs_cse"}, {"SRS PHM", "srs_phm"}, {"SRS NQ", "srs_nq"}, {"SRS A", "srs_a"}, {"SRS F", "srs_f"}}),
  #"Removed columns 2" = Table.RemoveColumns(#"Renamed columns 1", {"false", "Sheet", "grStudentAccountabilitytracker__1"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Removed columns 2", {{"SRS EMIER", "srs_emier"}, {"SRS SI", "srs_si"}, {"SRS ID", "srs_id"}, {"SRS IKI", "srs_iki"}, {"SRS CS", "srs_cs"}, {"SRS KID", "srs_kid"}, {"SRS M", "srs_m"}, {"SRS IES", "srs_ies"}, {"SRS SP", "srs_sp"}, {"SRS G", "srs_g"}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Renamed columns 2", {{"tss_stem", type text}, {"srs_pw", type text}, {"srs_kl", type text}, {"srs_cse", type text}, {"srs_phm", type text}, {"srs_nq", type text}, {"srs_a", type text}, {"srs_f", type text}, {"srs_g", type text}, {"srs_sp", type text}, {"srs_ies", type text}, {"srs_m", type text}, {"srs_kid", type text}, {"srs_cs", type text}, {"srs_iki", type text}, {"srs_id", type text}, {"srs_si", type text}, {"srs_emier", type text}, {"cohort_year", type text}, {"fafsa", type text}, {"act_833", type text}, {"literacy_boy", type text}, {"tss_e", type text}, {"community_service_hours", type text}, {"ap_exam_name", type text}, {"ap_test_score", type text}, {"ap", type text}, {"clep_score", type text}, {"tss_m", type text}, {"tss_r", type text}, {"tss_s", type text}, {"tss_c", type text}}),
  #"Renamed columns 3" = Table.RenameColumns(#"Changed column type 1", {{"WK – W-GL", "wk_w_gl"}, {"WK – W-AM", "w_am"}, {"ACT Composite", "act_composite"}, {"ACT - M", "act_m"}, {"ACT - R", "act_r"}, {"ACT - S", "act_s"}, {"ACT - E", "act_e"}, {"Explore Score", "explore_score"}, {"Plan Score", "plan_score"}}),
  #"Removed columns 3" = Table.RemoveColumns(#"Renamed columns 3", {"LEAP 2025 Connect Test Date", "ELA               ", "Math               ", "Science               ", "ELA               ", "Math               ", "Science               "}),
  #"Renamed columns 4" = Table.RenameColumns(#"Removed columns 3", {{"Math               ", "math1"}, {"Science               ", "science1"}, {"Social Studies               ", "social_studies1"}, {"Civics               ", "civics1"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns 4", {{"plan_score", type text}, {"explore_score", type text}, {"act_e", type text}, {"act_m", type text}, {"act_r", type text}, {"act_s", type text}, {"act_composite", type text}, {"w_am", type text}, {"wk_w_gl", type text}, {"WK – W-WD", type text}, {"WK - RFI", type text}, {"WK - LI", type text}, {"WK - AM", type text}, {"WK - Overall", type text}, {"WK 2.0 - Overall", type text}}),
  #"Renamed columns 5" = Table.RenameColumns(#"Changed column type 2", {{"WK – W-WD", "w_wd"}, {"WK - RFI", "wk_rfi"}, {"WK - LI", "wk_li"}, {"WK - AM", "wk_am"}, {"WK - Overall", "wk_overall"}, {"WK 2.0 - Overall", "wk2_overall"}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Renamed columns 5", {{"sasid", type text}, {"sidno", type text}, {"school_id", type text}, {"student_email", type text}, {"graduation_pathway", type text}, {"diploma_endorsements", type text}, {"ibc", type text}, {"eoc_test_date", type text}, {"alg_1", type text}, {"geo", type text}, {"english_2", type text}, {"english_3", type text}, {"bio", type text}, {"am_his", type text}, {"algebra_1", type text}, {"geometry", type text}, {"english_ii", type text}, {"english_iii", type text}, {"biology", type text}, {"american_history", type text}, {"leap_2025_test_date", type text}, {"math_pair_passed", type text}, {"english_pair_passed", type text}, {"historyScience_pair_passed", type text}, {"civicsScience_pair_passed", type text}, {"career_options", type text}, {"literacy_eoy", type text}})
in
  #"Changed column type 3";
shared caddo_tests_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "1b643108-97a2-432c-a0c0-391df26e0eea"]}[Data],
  TableNavigation = Navigation_2{[Id = "jcampus_caddo_tests", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
