[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "raw-credible-ledger-v3_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Old Service Type", DestinationColumnName = "Old Service Type"], [SourceColumnName = "clientvisit_id", DestinationColumnName = "clientvisit_id"], [SourceColumnName = "serviceledger_id", DestinationColumnName = "serviceledger_id"], [SourceColumnName = "payment_id", DestinationColumnName = "payment_id"], [SourceColumnName = "action_type", DestinationColumnName = "action_type"], [SourceColumnName = "emp_id", DestinationColumnName = "emp_id"], [SourceColumnName = "is_reversal", DestinationColumnName = "is_reversal"], [SourceColumnName = "balance", DestinationColumnName = "balance"], [SourceColumnName = "action_date", DestinationColumnName = "action_date"], [SourceColumnName = "is_reversed", DestinationColumnName = "is_reversed"], [SourceColumnName = "ins_due", DestinationColumnName = "ins_due"], [SourceColumnName = "client_due", DestinationColumnName = "client_due"], [SourceColumnName = "new_version", DestinationColumnName = "new_version"], [SourceColumnName = "ledgerbatch_id", DestinationColumnName = "ledgerbatch_id"], [SourceColumnName = "other_due", DestinationColumnName = "other_due"], [SourceColumnName = "is_claim_note", DestinationColumnName = "is_claim_note"], [SourceColumnName = "payer_id", DestinationColumnName = "payer_id"], [SourceColumnName = "freehand", DestinationColumnName = "freehand"], [SourceColumnName = "accounting_date", DestinationColumnName = "accounting_date"], [SourceColumnName = "revenue_code", DestinationColumnName = "revenue_code"], [SourceColumnName = "receipt_code", DestinationColumnName = "receipt_code"], [SourceColumnName = "debit_account", DestinationColumnName = "debit_account"], [SourceColumnName = "credit_account", DestinationColumnName = "credit_account"], [SourceColumnName = "is_fixed", DestinationColumnName = "is_fixed"], [SourceColumnName = "is_fixed1", DestinationColumnName = "is_fixed1"], [SourceColumnName = "action_date_utc", DestinationColumnName = "action_date_utc"], [SourceColumnName = "out_of_balance", DestinationColumnName = "out_of_balance"], [SourceColumnName = "description", DestinationColumnName = "description"], [SourceColumnName = "client_id", DestinationColumnName = "client_id"], [SourceColumnName = "clientvisit_order", DestinationColumnName = "clientvisit_order"], [SourceColumnName = "parent_serviceledger_id", DestinationColumnName = "parent_serviceledger_id"], [SourceColumnName = "clientins_id", DestinationColumnName = "clientins_id"], [SourceColumnName = "claim_id", DestinationColumnName = "claim_id"], [SourceColumnName = "batch_id", DestinationColumnName = "batch_id"], [SourceColumnName = "prev_visit_status", DestinationColumnName = "prev_visit_status"], [SourceColumnName = "load835item_id", DestinationColumnName = "load835item_id"], [SourceColumnName = "prev_billing_ord", DestinationColumnName = "prev_billing_ord"], [SourceColumnName = "prev_claim_status", DestinationColumnName = "prev_claim_status"], [SourceColumnName = "adjustmenttype_id", DestinationColumnName = "adjustmenttype_id"], [SourceColumnName = "adjustment_group_code", DestinationColumnName = "adjustment_group_code"], [SourceColumnName = "adjustment_reason_code", DestinationColumnName = "adjustment_reason_code"], [SourceColumnName = "undo_serviceledger_id", DestinationColumnName = "undo_serviceledger_id"], [SourceColumnName = "approvalrole_id", DestinationColumnName = "approvalrole_id"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared #"raw-credible-ledger-v3" = let
  Source = Xml.Tables(Web.Contents("https://reportservices.crediblebh.com/reports/ExportService.asmx/ExportDataSet?connection=N6wxVSQqPQ90HFOKAHmM!4HkQk7KeoTxbDm6GvoVakMDpuCQwjSxuu7oMphvGM2r3QkBIGNowSYsjC-6d2HnJQ__&start_date=&end_date=&custom_param1=&custom_param2=&custom_param3=")),
  #"Navigation 1" = Source{1}[Table],
  #"Expanded Table" = Table.ExpandTableColumn(#"Navigation 1", "Table", {"Name", "Table"}, {"Name.1", "Table.1"}),
  #"Expanded Table.1" = Table.ExpandTableColumn(#"Expanded Table", "Table.1", {"Name", "Table"}, {"Name.2", "Table"}),
  #"Expanded Table 1" = Table.ExpandTableColumn(#"Expanded Table.1", "Table", {"Name", "Table"}, {"Name.3", "Table.1"}),
  #"Expanded Table.1 1" = Table.ExpandTableColumn(#"Expanded Table 1", "Table.1", {"serviceledger_id", "payment_id", "action_type", "emp_id", "amount", "is_reversal", "balance", "action_date", "is_reversed", "ins_due", "client_due", "new_version", "ledgerbatch_id", "other_due", "is_claim_note", "payer_id", "freehand", "accounting_date", "revenue_code", "receipt_code", "debit_account", "credit_account", "is_fixed", "is_fixed1", "action_date_utc", "out_of_balance", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "description", "client_id", "clientvisit_id", "clientvisit_order", "parent_serviceledger_id", "clientins_id", "claim_id", "batch_id", "prev_visit_status", "load835item_id", "prev_billing_ord", "prev_claim_status", "adjustmenttype_id", "adjustment_group_code", "adjustment_reason_code", "undo_serviceledger_id", "approvalrole_id"}, {"serviceledger_id", "payment_id", "action_type", "emp_id", "amount", "is_reversal", "balance", "action_date", "is_reversed", "ins_due", "client_due", "new_version", "ledgerbatch_id", "other_due", "is_claim_note", "payer_id", "freehand", "accounting_date", "revenue_code", "receipt_code", "debit_account", "credit_account", "is_fixed", "is_fixed1", "action_date_utc", "out_of_balance", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata", "description", "client_id", "clientvisit_id", "clientvisit_order", "parent_serviceledger_id", "clientins_id", "claim_id", "batch_id", "prev_visit_status", "load835item_id", "prev_billing_ord", "prev_claim_status", "adjustmenttype_id", "adjustment_group_code", "adjustment_reason_code", "undo_serviceledger_id", "approvalrole_id"}),
  #"Removed columns" = Table.RemoveColumns(#"Expanded Table.1 1", {"Name", "Name.1", "Name.2", "Name.3", "urn:schemas-microsoft-com:xml-diffgram-v1", "urn:schemas-microsoft-com:xml-msdata"}),
  #"Extracted text range" = Table.TransformColumns(#"Removed columns", {{"action_date_utc", each Text.Middle(Text.From(_), 0, 10), type text}}),
  #"Filtered rows" = Table.SelectRows(#"Extracted text range", each ([action_type] = "CLIENT REVENUE" or [action_type] = "INSURANCE REVENUE" or [action_type] = "NO INSURANCE" or [action_type] = "OTHER REVENUE" or [action_type] = "UNDO CLIENT REVENUE" or [action_type] = "UNDO INSURANCE REVENUE" or [action_type] = "UNDO OTHER REVENUE")),
  #"Extracted text range 1" = Table.TransformColumns(#"Filtered rows", {{"accounting_date", each Text.Middle(Text.From(_), 0, 10), type text}}),
  #"Extracted text range 2" = Table.TransformColumns(#"Extracted text range 1", {{"action_date", each Text.Middle(Text.From(_), 0, 10), type text}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Extracted text range 2", {{"action_date", type date}, {"accounting_date", type date}, {"action_date_utc", type date}}),
  #"Transform columns" = Table.TransformColumnTypes(#"Changed column type", {{"serviceledger_id", type text}, {"payment_id", type text}, {"action_type", type text}, {"emp_id", type text}, {"amount", type text}, {"is_reversal", type text}, {"balance", type text}, {"is_reversed", type text}, {"ins_due", type text}, {"client_due", type text}, {"new_version", type text}, {"ledgerbatch_id", type text}, {"other_due", type text}, {"is_claim_note", type text}, {"payer_id", type text}, {"freehand", type text}, {"revenue_code", type text}, {"receipt_code", type text}, {"debit_account", type text}, {"credit_account", type text}, {"is_fixed", type text}, {"is_fixed1", type text}, {"out_of_balance", type text}, {"description", type text}, {"client_id", type text}, {"clientvisit_id", type text}, {"clientvisit_order", type text}, {"parent_serviceledger_id", type text}, {"clientins_id", type text}, {"claim_id", type text}, {"batch_id", type text}, {"prev_visit_status", type text}, {"load835item_id", type text}, {"prev_billing_ord", type text}, {"prev_claim_status", type text}, {"adjustmenttype_id", type text}, {"adjustment_group_code", type text}, {"adjustment_reason_code", type text}, {"undo_serviceledger_id", type text}, {"approvalrole_id", type text}}),
  #"Replace errors" = Table.ReplaceErrorValues(#"Transform columns", {{"serviceledger_id", null}, {"payment_id", null}, {"action_type", null}, {"emp_id", null}, {"amount", null}, {"is_reversal", null}, {"balance", null}, {"is_reversed", null}, {"ins_due", null}, {"client_due", null}, {"new_version", null}, {"ledgerbatch_id", null}, {"other_due", null}, {"is_claim_note", null}, {"payer_id", null}, {"freehand", null}, {"revenue_code", null}, {"receipt_code", null}, {"debit_account", null}, {"credit_account", null}, {"is_fixed", null}, {"is_fixed1", null}, {"out_of_balance", null}, {"description", null}, {"client_id", null}, {"clientvisit_id", null}, {"clientvisit_order", null}, {"parent_serviceledger_id", null}, {"clientins_id", null}, {"claim_id", null}, {"batch_id", null}, {"prev_visit_status", null}, {"load835item_id", null}, {"prev_billing_ord", null}, {"prev_claim_status", null}, {"adjustmenttype_id", null}, {"adjustment_group_code", null}, {"adjustment_reason_code", null}, {"undo_serviceledger_id", null}, {"approvalrole_id", null}}),
  #"Sorted rows" = Table.Sort(#"Replace errors", {{"action_date", Order.Descending}}),
  #"Reordered columns" = Table.ReorderColumns(#"Sorted rows", {"clientvisit_id", "serviceledger_id", "payment_id", "action_type", "emp_id", "amount", "is_reversal", "balance", "action_date", "is_reversed", "ins_due", "client_due", "new_version", "ledgerbatch_id", "other_due", "is_claim_note", "payer_id", "freehand", "accounting_date", "revenue_code", "receipt_code", "debit_account", "credit_account", "is_fixed", "is_fixed1", "action_date_utc", "out_of_balance", "description", "client_id", "clientvisit_order", "parent_serviceledger_id", "clientins_id", "claim_id", "batch_id", "prev_visit_status", "load835item_id", "prev_billing_ord", "prev_claim_status", "adjustmenttype_id", "adjustment_group_code", "adjustment_reason_code", "undo_serviceledger_id", "approvalrole_id"}),
  #"Inserted conditional column" = Table.AddColumn(#"Reordered columns", "Old Service Type", each if [amount] = "-53.72" then "Psychotherapy" else if [amount] = "-33.86" then "Psychotherapy" else if [amount] = "-125.00" then "Psychotherapy" else if [amount] = "-41.14" then "Psychotherapy" else if [amount] = "-81.12" then "PSR" else if [amount] = "-42.42" then "PSR" else if [amount] = "-900.00" then "Bundle" else if [amount] = "-136.05" then "CPST" else if [amount] = "-128.58" then "CPST" else if [amount] = "-108.84" then "CPST" else if [amount] = "-190.47" then "CPST" else if [amount] = "-81.63" then "CPST" else if [amount] = "-217.68" then "CPST" else if [amount] = "-56.56" then "PSR" else if [amount] = "-70.70" then "PSR" else if [amount] = "-14.14" then "PSR" else if [amount] = "-101.40" then "PSR" else if [amount] = "-63.38" then "PSR" else if [amount] = "-40.56" then "PSR" else if [amount] = "-163.26" then "CPST" else if [amount] = "-54.42" then "CPST" else if [amount] = "-60.84" then "PSR" else if [amount] = "-14.14" then "PSR" else if [amount] = "-101.40" then "PSR" else if [amount] = "-63.38" then "PSR" else if [amount] = "-40.56" then "PSR" else if [amount] = "-28.28" then "PSR" else if [amount] = "-84.84" then "PSR" else if [amount] = "-98.98" then "PSR" else if [amount] = "-121.68" then "PSR" else if [amount] = "-113.12" then "PSR" else if [amount] = "-141.96" then "PSR" else if [amount] = "-48.04" then "PSR" else if [amount] = "-163.26" then "CPST" else if [amount] = "-54.42" then "CPST" else if [amount] = "-162.24" then "CPST" else if [amount] = "-85.72" then "CPST" else if [amount] = "-158.45" then "Crisis f/u" else if [amount] = "-353.65" then "Crisis Int" else if [amount] = "-44.08" then "Med Mgt" else if [amount] = "-20.28" then "PSR" else if [amount] = "-244.89" then "CPST" else if [amount] = "-126.76" then "Crisis f/u" else if [amount] = "-1074.84" then "PSR" else ""),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Inserted conditional column", {{"amount", Currency.Type}}),
  #"Reordered columns 1" = Table.ReorderColumns(#"Changed column type 1", {"Old Service Type", "clientvisit_id", "serviceledger_id", "payment_id", "action_type", "emp_id", "amount", "is_reversal", "balance", "action_date", "is_reversed", "ins_due", "client_due", "new_version", "ledgerbatch_id", "other_due", "is_claim_note", "payer_id", "freehand", "accounting_date", "revenue_code", "receipt_code", "debit_account", "credit_account", "is_fixed", "is_fixed1", "action_date_utc", "out_of_balance", "description", "client_id", "clientvisit_order", "parent_serviceledger_id", "clientins_id", "claim_id", "batch_id", "prev_visit_status", "load835item_id", "prev_billing_ord", "prev_claim_status", "adjustmenttype_id", "adjustment_group_code", "adjustment_reason_code", "undo_serviceledger_id", "approvalrole_id"}),
  #"Transform columns 1" = Table.TransformColumnTypes(#"Reordered columns 1", {{"Old Service Type", type text}})
in
  #"Transform columns 1";
shared #"raw-credible-ledger-v3_DataDestination" = let
  Pattern = Fabric.Warehouse([HierarchicalNavigation = null, CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "e4d2de35-5f5d-457f-8e5b-43f758299057"]}[Data],
  TableNavigation = Navigation_2{[Item = "raw-credible-ledger-v3", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
