[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "sp_lighthouse_registration csv_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Client ID", DestinationColumnName = "Client ID"], [SourceColumnName = "Address", DestinationColumnName = "Address"], [SourceColumnName = "Bus number:", DestinationColumnName = "Bus number:"], [SourceColumnName = "VOANLA - Zip Code", DestinationColumnName = "VOANLA - Zip Code"], [SourceColumnName = "Cell Phone", DestinationColumnName = "Cell Phone"], [SourceColumnName = "City", DestinationColumnName = "City"], [SourceColumnName = "Does child ride the bus?", DestinationColumnName = "Does child ride the bus?"], [SourceColumnName = "Does your child receive behavioral health services?", DestinationColumnName = "Does your child receive behavioral health services?"], [SourceColumnName = "Education Release Effective for School Year:", DestinationColumnName = "Education Release Effective for School Year:"], [SourceColumnName = "Education Release on file?", DestinationColumnName = "Education Release on file?"], [SourceColumnName = "Email Address", DestinationColumnName = "Email Address"], [SourceColumnName = "Food Stamps", DestinationColumnName = "Food Stamps"], [SourceColumnName = "Household Type", DestinationColumnName = "Household Type"], [SourceColumnName = "If yes, please list the provider", DestinationColumnName = "If yes_ please list the provider"], [SourceColumnName = "Is student enrolled in CIS?", DestinationColumnName = "Is student enrolled in CIS?"], [SourceColumnName = "JCAMPUS signed permission on file?", DestinationColumnName = "JCAMPUS signed permission on file?"], [SourceColumnName = "JCAMPUS/School Loop Password:", DestinationColumnName = "JCAMPUS/School Loop Password:"], [SourceColumnName = "JCAMPUS/School Loop Username:", DestinationColumnName = "JCAMPUS/School Loop Username:"], [SourceColumnName = "Media Release Effective for School Year:", DestinationColumnName = "Media Release Effective for School Year:"], [SourceColumnName = "Media Release on file?", DestinationColumnName = "Media Release on file?"], [SourceColumnName = "Name Of Teacher/Homeroom Teacher", DestinationColumnName = "Name Of Teacher/Homeroom Teacher"], [SourceColumnName = "Program Contract Effective for School Year:", DestinationColumnName = "Program Contract Effective for School Year:"], [SourceColumnName = "Program Contract Signed and On File?", DestinationColumnName = "Program Contract Signed and On File?"], [SourceColumnName = "School Year", DestinationColumnName = "School Year"], [SourceColumnName = "ServicePoint Release of Information on File?", DestinationColumnName = "ServicePoint Release of Information on File?"], [SourceColumnName = "State", DestinationColumnName = "State"], [SourceColumnName = "Student ID#", DestinationColumnName = "Student ID#"], [SourceColumnName = "Summer Session", DestinationColumnName = "Summer Session"], [SourceColumnName = "Total number of Persons Living at the Address", DestinationColumnName = "Total number of Persons Living at the Address"], [SourceColumnName = "Allergy/Medical Condition?", DestinationColumnName = "Allergy/Medical Condition?"], [SourceColumnName = "Application Date", DestinationColumnName = "Application Date"], [SourceColumnName = "Contact #1 Name", DestinationColumnName = "Contact #1 Name"], [SourceColumnName = "Contact #1 Phone", DestinationColumnName = "Contact #1 Phone"], [SourceColumnName = "Contact #2 Name", DestinationColumnName = "Contact #2 Name"], [SourceColumnName = "Contact #2 Phone", DestinationColumnName = "Contact #2 Phone"], [SourceColumnName = "Clinic or Doctor's Name", DestinationColumnName = "Clinic or Doctor's Name"], [SourceColumnName = "Doctor's Phone", DestinationColumnName = "Doctor's Phone"], [SourceColumnName = "Does your child have an Individual Education Plan (IEP)?", DestinationColumnName = "Does your child have an Individual Education Plan _IEP_?"], [SourceColumnName = "Drop-off location:", DestinationColumnName = "Drop-off location:"], [SourceColumnName = "If yes, pickup location:", DestinationColumnName = "If yes_ pickup location:"], [SourceColumnName = "Current Grade Level", DestinationColumnName = "Current Grade Level"], [SourceColumnName = "Has your child been placed in special education by the school system?", DestinationColumnName = "Has your child been placed in special education by the school system?"], [SourceColumnName = "Home Phone", DestinationColumnName = "Home Phone"], [SourceColumnName = "If yes, please explain:", DestinationColumnName = "If yes_ please explain:"], [SourceColumnName = "If yes, please list:", DestinationColumnName = "If yes_ please list:"], [SourceColumnName = "Lighthouse Location Enrolling", DestinationColumnName = "Lighthouse Location Enrolling"], [SourceColumnName = "Medication at site during program hours?", DestinationColumnName = "Medication at site during program hours?"], [SourceColumnName = "Parent/Guardian Name", DestinationColumnName = "Parent/Guardian Name"], [SourceColumnName = "Place of Employment", DestinationColumnName = "Place of Employment"], [SourceColumnName = "School District", DestinationColumnName = "School District"], [SourceColumnName = "School Name", DestinationColumnName = "School Name"], [SourceColumnName = "School Phone Number", DestinationColumnName = "School Phone Number"], [SourceColumnName = "Social Security", DestinationColumnName = "Social Security"], [SourceColumnName = "SSI", DestinationColumnName = "SSI"], [SourceColumnName = "Total Annual Income", DestinationColumnName = "Total Annual Income"], [SourceColumnName = "Van Information", DestinationColumnName = "Van Information"], [SourceColumnName = "Welfare (TANF)", DestinationColumnName = "Welfare _TANF_"], [SourceColumnName = "Does the child need to be picked up in a VOA van before Camp Glow?", DestinationColumnName = "Does the child need to be picked up in a VOA van before Camp Glow?"], [SourceColumnName = "Relationship to Child", DestinationColumnName = "Relationship to Child"], [SourceColumnName = "WIOA?", DestinationColumnName = "WIOA?"], [SourceColumnName = "Will this provider want to visit during the program?", DestinationColumnName = "Will this provider want to visit during the program?"], [SourceColumnName = "Work Phone", DestinationColumnName = "Work Phone"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared sp_lighthouse_registration = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "1b643108-97a2-432c-a0c0-391df26e0eea"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "Files", ItemKind = "Folder"]}[Data],
  #"Navigation 3" = #"Navigation 2"{[Name = "ServicePoint"]}[Content],
  #"Navigation 4" = #"Navigation 3"{[Name = "sp_lighthouse_registration.csv"]}[Content],
  #"Imported CSV" = Csv.Document(#"Navigation 4", [Delimiter = ",", Columns = 62, QuoteStyle = QuoteStyle.None]),
  #"Promoted headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Client ID", Int64.Type}, {"Address", type text}, {"Bus number:", type text}, {"VOANLA - Zip Code", Int64.Type}, {"Cell Phone", type text}, {"City", type text}, {"Does child ride the bus?", type text}, {"Does your child receive behavioral health services?", type text}, {"Education Release Effective for School Year:", type text}, {"Education Release on file?", type text}, {"Email Address", type text}, {"Food Stamps", type text}, {"Household Type", type text}, {"If yes, please list the provider", type text}, {"Is student enrolled in CIS?", type text}, {"JCAMPUS signed permission on file?", type text}, {"JCAMPUS/School Loop Password:", type text}, {"JCAMPUS/School Loop Username:", type text}, {"Media Release Effective for School Year:", type text}, {"Media Release on file?", type text}, {"Name Of Teacher/Homeroom Teacher", type text}, {"Program Contract Effective for School Year:", type text}, {"Program Contract Signed and On File?", type text}, {"School Year", type text}, {"ServicePoint Release of Information on File?", type text}, {"State", type text}, {"Student ID#", type text}, {"Summer Session", type text}, {"Total number of Persons Living at the Address", Int64.Type}, {"Allergy/Medical Condition?", type text}, {"Application Date", type date}, {"Contact #1 Name", type text}, {"Contact #1 Phone", type text}, {"Contact #2 Name", type text}, {"Contact #2 Phone", type text}, {"Clinic or Doctor's Name", type text}, {"Doctor's Phone", type text}, {"Does your child have an Individual Education Plan (IEP)?", type text}, {"Drop-off location:", type text}, {"If yes, pickup location:", type text}, {"Current Grade Level", type text}, {"Has your child been placed in special education by the school system?", type text}, {"Home Phone", type text}, {"If yes, please explain:", type text}, {"If yes, please list:", type text}, {"Lighthouse Location Enrolling", type text}, {"Medication at site during program hours?", type text}, {"Parent/Guardian Name", type text}, {"Place of Employment", type text}, {"School District", type text}, {"School Name", type text}, {"School Phone Number", type text}, {"Social Security", type text}, {"SSI", type text}, {"Total Annual Income", type number}, {"Van Information", type text}, {"Welfare (TANF)", type text}, {"Does the child need to be picked up in a VOA van before Camp Glow?", type text}, {"Relationship to Child", type text}, {"WIOA?", type text}, {"Will this provider want to visit during the program?", type text}, {"Work Phone", type text}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type", {{"Client ID", type text}}),
  #"Removed errors" = Table.RemoveRowsWithErrors(#"Changed column type 1", {"VOANLA - Zip Code"}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Removed errors", {{"Total Annual Income", type text}}),
  #"Removed errors 1" = Table.RemoveRowsWithErrors(#"Changed column type 2", {"Total Annual Income"})
in
  #"Removed errors 1";
shared #"sp_lighthouse_registration csv_DataDestination" = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "ea227a8a-7257-406d-9d09-8fb6f312cadc"]}[Data],
  TableNavigation = Navigation_2{[Item = "raw_lighthouse_registration", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
