table 'cis cis_behavior_positive_count'
	lineageTag: 5fe82117-0fda-4c3d-bfe4-5fbc1451466b

	measure 'All Behavior Clients' = SUM('Aggregated Behavior Goals'[all_monitored])
		formatString: 0
		lineageTag: 7bdec8f4-4dea-4c44-b0be-dacf434cf840

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Positive Behavior Clients' = SUM('cis cis_behavior_positive_count'[positive_progress])
		formatString: 0
		lineageTag: 6b8e6d6a-106e-476f-9128-1f8b42afdeef

	measure 'Cumulative Behavior Percentage' = DIVIDE([Positive Behavior Clients], [All Behavior Clients])
		formatString: 0%;-0%;0%
		lineageTag: 9140acdb-e7b3-4de7-9dec-e1430e88f469

	column school_name
		dataType: string
		lineageTag: ed8988bb-32f4-4a70-8d29-97d28a72c3b3
		summarizeBy: none
		sourceColumn: school_name

		annotation SummarizationSetBy = Automatic

	column positive_progress
		dataType: int64
		formatString: 0
		lineageTag: 46356a6a-eff8-418d-a501-3fe5eb08bf5a
		summarizeBy: sum
		sourceColumn: positive_progress

		annotation SummarizationSetBy = Automatic

	column all_monitored
		dataType: int64
		formatString: 0
		lineageTag: b6789d53-d011-45c1-b3d5-99098418797e
		summarizeBy: sum
		sourceColumn: all_monitored

		annotation SummarizationSetBy = Automatic

	column positive_percentage
		dataType: double
		lineageTag: 14511323-afe3-4d58-875a-f2e16cdcda13
		summarizeBy: none
		sourceColumn: positive_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goal
		dataType: string
		lineageTag: 4916746d-4228-45a5-bc29-230efea2e385
		summarizeBy: none
		sourceColumn: goal

		annotation SummarizationSetBy = Automatic

	partition 'cis cis_behavior_positive_count' = m
		mode: import
		source =
				let
				    Source = Sql.Database("nzrmcoc5w6tebmq3bkxbdeohga-y7eucqqylblezera7l3de5axoa.datawarehouse.fabric.microsoft.com", "Bronze"),
				    cis_cis_behavior_positive_count = Source{[Schema="cis",Item="cis_behavior_positive_count"]}[Data],
				    #"Added Custom" = Table.AddColumn(cis_cis_behavior_positive_count, "goal", each "Behavior")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

