[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Maintenance Request and History_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared #"Maintenance Request and History" = let
  Source = SharePoint.Tables("https://voanorthlaorg.sharepoint.com/sites/TheVOAHub", [Implementation = "2.0", ViewMode = "All"]),
  #"Navigation 1" = Source{[Id = "668581fb-99d7-4500-86f8-db20fb18ad8b"]}[Items],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"Item is a Record", "Custom ID Number", "Color Tag"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"If residential, permission to enter?", "perm_to_enter"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns", {"Compliance Asset Id", "App Modified By", "App Created By", "Label applied by", "Retention label Applied", "Retention label", "Label setting", "Folder Child Count", "Item Child Count", "Type", "Edit", "Attachments", "Version", "Modified By"}),
  #"Expanded Created By 2" = Table.ExpandListColumn(#"Removed columns 1", "Created By"),
  #"Expanded Created By 3" = Table.ExpandRecordColumn(#"Expanded Created By 2", "Created By", {"id", "title", "email", "sip", "picture", "department", "jobTitle"}, {"id.1", "title", "email", "sip", "picture", "department", "jobTitle"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Expanded Created By 3", {{"title", "submitter"}, {"email", "submitter_email"}, {"Created", "created_date"}, {"Modified", "modified_date"}}),
  #"Removed columns 4" = Table.RemoveColumns(#"Renamed columns 1", {"id.1", "sip", "picture"}),
  #"Removed columns 2" = Table.RemoveColumns(#"Removed columns 4", {"Content Type"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Removed columns 2", {{"EPOCH", "epoch"}, {"Ticket Resolution", "resolution"}, {"Tech String", "tech"}, {"Approved", "approved"}, {"Completed", "completed"}}),
  #"Removed columns 3" = Table.RemoveColumns(#"Renamed columns 2", {"ID", "Spacer"}),
  #"Renamed columns 3" = Table.RenameColumns(#"Removed columns 3", {{"Date Approved", "approval_date"}, {"Ticket Status", "status"}, {"Parts Used?", "parts_used"}, {"Date Completed", "completion_date"}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed columns 3", {{"completion_date", type date}}),
  #"Expanded Technician" = Table.ExpandListColumn(#"Changed column type", "Technician"),
  #"Expanded Technician 1" = Table.ExpandRecordColumn(#"Expanded Technician", "Technician", {"lookupValue"}, {"lookupValue"}),
  #"Renamed columns 4" = Table.RenameColumns(#"Expanded Technician 1", {{"lookupValue", "tech_email"}, {"Description", "description"}, {"Service Type", "service_type"}, {"Service Issue", "issue"}, {"Repeat Issue?", "repeat_issue"}, {"Request Type:", "request_type"}, {"Request Date", "request_date"}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Renamed columns 4", {{"request_date", type date}}),
  #"Renamed columns 5" = Table.RenameColumns(#"Changed column type 1", {{"Entry Notes", "notes"}, {"Permission to enter if residential?", "perm2enter"}, {"Unit #", "unit"}, {"Location Detail", "loaction_detail"}, {"Location", "location"}, {"Program", "program"}, {"Requester Phone #", "requester_phone"}, {"Requester", "requester"}, {"Ticket Nbr", "ticket_num"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns 5", {{"department", type text}, {"submitter_email", type text}, {"submitter", type text}, {"created_date", type date}, {"modified_date", type date}, {"approval_date", type date}, {"tech_email", type text}}),
  #"Sorted rows" = Table.Sort(#"Changed column type 2", {{"request_date", Order.Descending}}),
  #"Replaced value" = Table.ReplaceValue(#"Sorted rows", "", "No", Replacer.ReplaceValue, {"approved"}),
  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", "", "No", Replacer.ReplaceValue, {"completed"}),
  #"Inserted start of month" = Table.AddColumn(#"Replaced value 1", "Start of month", each Date.StartOfMonth([request_date]), type nullable date),
  #"Duplicated column" = Table.DuplicateColumn(#"Inserted start of month", "Start of month", "Start of month - Copy"),
  #"Extracted year" = Table.TransformColumns(#"Duplicated column", {{"Start of month - Copy", each Date.Year(_), type nullable number}}),
  #"Extracted month name" = Table.TransformColumns(#"Extracted year", {{"Start of month", each Date.MonthName(_), type nullable text}}),
  #"Merged columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Extracted month name", {{"Start of month - Copy", type text}}), {"Start of month", "Start of month - Copy"}, Combiner.CombineTextByDelimiter(" ", QuoteStyle.None), "request_month"),
  #"Inserted start of month 1" = Table.AddColumn(#"Merged columns", "Start of month", each Date.StartOfMonth([request_date]), type nullable date),
  #"Renamed columns 6" = Table.RenameColumns(#"Inserted start of month 1", {{"Start of month", "month_control"}}),
  #"Added custom" = Table.AddColumn(#"Renamed columns 6", "Custom", each Duration.Days([request_date] - [completion_date])),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Added custom", {{"Custom", Int64.Type}}),
  #"Calculated absolute value" = Table.TransformColumns(#"Changed column type 3", {{"Custom", each Number.Abs(_), type nullable number}}),
  #"Renamed columns 7" = Table.RenameColumns(#"Calculated absolute value", {{"Custom", "days_to_complete"}}),
  #"Added custom 1" = Table.TransformColumnTypes(Table.AddColumn(#"Renamed columns 7", "today", each Date.From(DateTime.LocalNow())), {{"today", type date}}),
  #"Added custom 2" = Table.AddColumn(#"Added custom 1", "days_open", each Duration.Days([request_date] - [today])),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Added custom 2", {{"days_open", Int64.Type}}),
  #"Calculated absolute value 1" = Table.TransformColumns(#"Changed column type 4", {{"days_open", each Number.Abs(_), type nullable number}}),
  #"Inserted conditional column" = Table.AddColumn(#"Calculated absolute value 1", "Custom", each if [completion_date] = null then [days_open] else [days_to_complete]),
  #"Renamed columns 8" = Table.RenameColumns(#"Inserted conditional column", {{"Custom", "comb_open_days"}}),
  #"Changed column type 5" = Table.TransformColumnTypes(#"Renamed columns 8", {{"comb_open_days", Int64.Type}, {"jobTitle", type text}})
in
  #"Changed column type 5";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "maintenance_avg_days_open_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared maintenance_avg_days_open = let
  Source = SharePoint.Tables("https://voanorthlaorg.sharepoint.com/sites/TheVOAHub", [Implementation = "2.0", ViewMode = "All"]),
  #"Navigation 1" = Source{[Id = "668581fb-99d7-4500-86f8-db20fb18ad8b"]}[Items],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"Item is a Record", "Custom ID Number", "Color Tag"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"If residential, permission to enter?", "perm_to_enter"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns", {"Compliance Asset Id", "App Modified By", "App Created By", "Label applied by", "Retention label Applied", "Retention label", "Label setting", "Folder Child Count", "Item Child Count", "Type", "Edit", "Attachments", "Version", "Modified By"}),
  #"Expanded Created By 2" = Table.ExpandListColumn(#"Removed columns 1", "Created By"),
  #"Expanded Created By 3" = Table.ExpandRecordColumn(#"Expanded Created By 2", "Created By", {"id", "title", "email", "sip", "picture", "department", "jobTitle"}, {"id.1", "title", "email", "sip", "picture", "department", "jobTitle"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Expanded Created By 3", {{"title", "submitter"}, {"email", "submitter_email"}, {"Created", "created_date"}, {"Modified", "modified_date"}}),
  #"Removed columns 4" = Table.RemoveColumns(#"Renamed columns 1", {"id.1", "sip", "picture"}),
  #"Removed columns 2" = Table.RemoveColumns(#"Removed columns 4", {"Content Type"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Removed columns 2", {{"EPOCH", "epoch"}, {"Ticket Resolution", "resolution"}, {"Tech String", "tech"}, {"Approved", "approved"}, {"Completed", "completed"}}),
  #"Removed columns 3" = Table.RemoveColumns(#"Renamed columns 2", {"ID", "Spacer"}),
  #"Renamed columns 3" = Table.RenameColumns(#"Removed columns 3", {{"Date Approved", "approval_date"}, {"Ticket Status", "status"}, {"Parts Used?", "parts_used"}, {"Date Completed", "completion_date"}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed columns 3", {{"completion_date", type date}}),
  #"Expanded Technician" = Table.ExpandListColumn(#"Changed column type", "Technician"),
  #"Expanded Technician 1" = Table.ExpandRecordColumn(#"Expanded Technician", "Technician", {"lookupValue"}, {"lookupValue"}),
  #"Renamed columns 4" = Table.RenameColumns(#"Expanded Technician 1", {{"lookupValue", "tech_email"}, {"Description", "description"}, {"Service Type", "service_type"}, {"Service Issue", "issue"}, {"Repeat Issue?", "repeat_issue"}, {"Request Type:", "request_type"}, {"Request Date", "request_date"}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Renamed columns 4", {{"request_date", type date}}),
  #"Renamed columns 5" = Table.RenameColumns(#"Changed column type 1", {{"Entry Notes", "notes"}, {"Permission to enter if residential?", "perm2enter"}, {"Unit #", "unit"}, {"Location Detail", "loaction_detail"}, {"Location", "location"}, {"Program", "program"}, {"Requester Phone #", "requester_phone"}, {"Requester", "requester"}, {"Ticket Nbr", "ticket_num"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns 5", {{"department", type text}, {"submitter_email", type text}, {"submitter", type text}, {"created_date", type date}, {"modified_date", type date}, {"approval_date", type date}, {"tech_email", type text}}),
  #"Sorted rows" = Table.Sort(#"Changed column type 2", {{"request_date", Order.Descending}}),
  #"Replaced value" = Table.ReplaceValue(#"Sorted rows", "", "No", Replacer.ReplaceValue, {"approved"}),
  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", "", "No", Replacer.ReplaceValue, {"completed"}),
  #"Inserted start of month" = Table.AddColumn(#"Replaced value 1", "Start of month", each Date.StartOfMonth([request_date]), type nullable date),
  #"Duplicated column" = Table.DuplicateColumn(#"Inserted start of month", "Start of month", "Start of month - Copy"),
  #"Extracted year" = Table.TransformColumns(#"Duplicated column", {{"Start of month - Copy", each Date.Year(_), type nullable number}}),
  #"Extracted month name" = Table.TransformColumns(#"Extracted year", {{"Start of month", each Date.MonthName(_), type nullable text}}),
  #"Merged columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Extracted month name", {{"Start of month - Copy", type text}}), {"Start of month", "Start of month - Copy"}, Combiner.CombineTextByDelimiter(" ", QuoteStyle.None), "request_month"),
  #"Inserted start of month 1" = Table.AddColumn(#"Merged columns", "Start of month", each Date.StartOfMonth([request_date]), type nullable date),
  #"Renamed columns 6" = Table.RenameColumns(#"Inserted start of month 1", {{"Start of month", "month_control"}}),
  #"Added custom" = Table.AddColumn(#"Renamed columns 6", "Custom", each Duration.Days([request_date] - [completion_date])),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Added custom", {{"Custom", Int64.Type}}),
  #"Calculated absolute value" = Table.TransformColumns(#"Changed column type 3", {{"Custom", each Number.Abs(_), type nullable number}}),
  #"Renamed columns 7" = Table.RenameColumns(#"Calculated absolute value", {{"Custom", "days_to_complete"}}),
  #"Added custom 1" = Table.TransformColumnTypes(Table.AddColumn(#"Renamed columns 7", "today", each Date.From(DateTime.LocalNow())), {{"today", type date}}),
  #"Added custom 2" = Table.AddColumn(#"Added custom 1", "days_open", each Duration.Days([request_date] - [today])),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Added custom 2", {{"days_open", Int64.Type}}),
  #"Calculated absolute value 1" = Table.TransformColumns(#"Changed column type 4", {{"days_open", each Number.Abs(_), type nullable number}}),
  #"Inserted conditional column" = Table.AddColumn(#"Calculated absolute value 1", "Custom", each if [completion_date] = null then [days_open] else [days_to_complete]),
  #"Renamed columns 8" = Table.RenameColumns(#"Inserted conditional column", {{"Custom", "comb_open_days"}}),
  #"Grouped rows" = Table.Group(#"Renamed columns 8", {"request_month", "month_control"}, {{"avg_days_open", each List.Average([comb_open_days]), type any}}),
  #"Changed column type 5" = Table.TransformColumnTypes(#"Grouped rows", {{"avg_days_open", type number}}),
  #"Rounded up" = Table.TransformColumns(#"Changed column type 5", {{"avg_days_open", each Number.RoundUp(_), type nullable Int64.Type}}),
  #"Filtered rows" = Table.SelectRows(#"Rounded up", each ([request_month] <> " "))
in
  #"Filtered rows";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "maintenance_avg_days_to_complete_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared maintenance_avg_days_to_complete = let
  Source = SharePoint.Tables("https://voanorthlaorg.sharepoint.com/sites/TheVOAHub", [Implementation = "2.0", ViewMode = "All"]),
  #"Navigation 1" = Source{[Id = "668581fb-99d7-4500-86f8-db20fb18ad8b"]}[Items],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"Item is a Record", "Custom ID Number", "Color Tag"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"If residential, permission to enter?", "perm_to_enter"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns", {"Compliance Asset Id", "App Modified By", "App Created By", "Label applied by", "Retention label Applied", "Retention label", "Label setting", "Folder Child Count", "Item Child Count", "Type", "Edit", "Attachments", "Version", "Modified By"}),
  #"Expanded Created By 2" = Table.ExpandListColumn(#"Removed columns 1", "Created By"),
  #"Expanded Created By 3" = Table.ExpandRecordColumn(#"Expanded Created By 2", "Created By", {"id", "title", "email", "sip", "picture", "department", "jobTitle"}, {"id.1", "title", "email", "sip", "picture", "department", "jobTitle"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Expanded Created By 3", {{"title", "submitter"}, {"email", "submitter_email"}, {"Created", "created_date"}, {"Modified", "modified_date"}}),
  #"Removed columns 4" = Table.RemoveColumns(#"Renamed columns 1", {"id.1", "sip", "picture"}),
  #"Removed columns 2" = Table.RemoveColumns(#"Removed columns 4", {"Content Type"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Removed columns 2", {{"EPOCH", "epoch"}, {"Ticket Resolution", "resolution"}, {"Tech String", "tech"}, {"Approved", "approved"}, {"Completed", "completed"}}),
  #"Removed columns 3" = Table.RemoveColumns(#"Renamed columns 2", {"ID", "Spacer"}),
  #"Renamed columns 3" = Table.RenameColumns(#"Removed columns 3", {{"Date Approved", "approval_date"}, {"Ticket Status", "status"}, {"Parts Used?", "parts_used"}, {"Date Completed", "completion_date"}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed columns 3", {{"completion_date", type date}}),
  #"Expanded Technician" = Table.ExpandListColumn(#"Changed column type", "Technician"),
  #"Expanded Technician 1" = Table.ExpandRecordColumn(#"Expanded Technician", "Technician", {"lookupValue"}, {"lookupValue"}),
  #"Renamed columns 4" = Table.RenameColumns(#"Expanded Technician 1", {{"lookupValue", "tech_email"}, {"Description", "description"}, {"Service Type", "service_type"}, {"Service Issue", "issue"}, {"Repeat Issue?", "repeat_issue"}, {"Request Type:", "request_type"}, {"Request Date", "request_date"}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Renamed columns 4", {{"request_date", type date}}),
  #"Renamed columns 5" = Table.RenameColumns(#"Changed column type 1", {{"Entry Notes", "notes"}, {"Permission to enter if residential?", "perm2enter"}, {"Unit #", "unit"}, {"Location Detail", "loaction_detail"}, {"Location", "location"}, {"Program", "program"}, {"Requester Phone #", "requester_phone"}, {"Requester", "requester"}, {"Ticket Nbr", "ticket_num"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns 5", {{"department", type text}, {"submitter_email", type text}, {"submitter", type text}, {"created_date", type date}, {"modified_date", type date}, {"approval_date", type date}, {"tech_email", type text}}),
  #"Sorted rows" = Table.Sort(#"Changed column type 2", {{"request_date", Order.Descending}}),
  #"Replaced value" = Table.ReplaceValue(#"Sorted rows", "", "No", Replacer.ReplaceValue, {"approved"}),
  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", "", "No", Replacer.ReplaceValue, {"completed"}),
  #"Inserted start of month" = Table.AddColumn(#"Replaced value 1", "Start of month", each Date.StartOfMonth([request_date]), type nullable date),
  #"Duplicated column" = Table.DuplicateColumn(#"Inserted start of month", "Start of month", "Start of month - Copy"),
  #"Extracted year" = Table.TransformColumns(#"Duplicated column", {{"Start of month - Copy", each Date.Year(_), type nullable number}}),
  #"Extracted month name" = Table.TransformColumns(#"Extracted year", {{"Start of month", each Date.MonthName(_), type nullable text}}),
  #"Merged columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Extracted month name", {{"Start of month - Copy", type text}}), {"Start of month", "Start of month - Copy"}, Combiner.CombineTextByDelimiter(" ", QuoteStyle.None), "request_month"),
  #"Inserted start of month 1" = Table.AddColumn(#"Merged columns", "Start of month", each Date.StartOfMonth([request_date]), type nullable date),
  #"Renamed columns 6" = Table.RenameColumns(#"Inserted start of month 1", {{"Start of month", "month_control"}}),
  #"Added custom" = Table.AddColumn(#"Renamed columns 6", "Custom", each Duration.Days([request_date] - [completion_date])),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Added custom", {{"Custom", Int64.Type}}),
  #"Calculated absolute value" = Table.TransformColumns(#"Changed column type 3", {{"Custom", each Number.Abs(_), type nullable number}}),
  #"Renamed columns 7" = Table.RenameColumns(#"Calculated absolute value", {{"Custom", "days_to_complete"}}),
  #"Added custom 1" = Table.TransformColumnTypes(Table.AddColumn(#"Renamed columns 7", "today", each Date.From(DateTime.LocalNow())), {{"today", type date}}),
  #"Added custom 2" = Table.AddColumn(#"Added custom 1", "days_open", each Duration.Days([request_date] - [today])),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Added custom 2", {{"days_open", Int64.Type}}),
  #"Calculated absolute value 1" = Table.TransformColumns(#"Changed column type 4", {{"days_open", each Number.Abs(_), type nullable number}}),
  #"Inserted conditional column" = Table.AddColumn(#"Calculated absolute value 1", "Custom", each if [completion_date] = null then [days_open] else [days_to_complete]),
  #"Renamed columns 8" = Table.RenameColumns(#"Inserted conditional column", {{"Custom", "comb_open_days"}}),
  #"Grouped rows" = Table.Group(#"Renamed columns 8", {"month_control", "request_month"}, {{"avg_days_to_complete", each List.Average([days_to_complete]), type nullable number}}),
  #"Filtered rows" = Table.SelectRows(#"Grouped rows", each ([month_control] <> null)),
  #"Rounded up" = Table.TransformColumns(#"Filtered rows", {{"avg_days_to_complete", each Number.RoundUp(_), type nullable Int64.Type}})
in
  #"Rounded up";
shared maintenance_avg_days_open_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "fccbdcf0-4c42-431d-8e07-ae4b00bda780"]}[Data],
  TableNavigation = Navigation_2{[Id = "maintenance_avg_days_open", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
shared maintenance_avg_days_to_complete_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "fccbdcf0-4c42-431d-8e07-ae4b00bda780"]}[Data],
  TableNavigation = Navigation_2{[Id = "maintenance_avg_days_to_complete", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
shared #"Maintenance Request and History_DataDestination" = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "4241c9c7-5818-4c56-9220-faf632741770"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "fccbdcf0-4c42-431d-8e07-ae4b00bda780"]}[Data],
  TableNavigation = Navigation_2{[Id = "raw_maintenance_requests", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
